### ISSUE TITLE
EDIT ME Include the app name and if it is a Package app or an Install based App

### ISSUE THREAD

**Issue by liulysunix** [Botspot/pi-apps#1966] opened 2022-06-12 04:26 UTC
### What is the name of the app?

Wine(x64)

### (Optional) Where is the app hosted?

winehq and github

### About the app

Run x64 Windows apps with a box64-emulated version of x64 wine*.
To run: wine path/to/file.exe
To configure wine: go to 'Wine configuration' in terminal:  winecfg
Not all Windows applications will work under Wine. It's a good idea to check online if your program can run, or if something can be tweaked to make it work.
Wine (originally an acronym for "Wine Is Not an Emulator") is a compatibility layer capable of running Windows applications on several POSIX-compliant operating systems, such as Linux, macOS, & BSD. Instead of simulating internal Windows logic like a virtual machine or emulator, Wine translates Windows API calls into POSIX calls on-the-fly, eliminating the performance and memory penalties of other methods and allowing you to cleanly integrate Windows applications into your desktop.

### Upload file or Add PR Link

[Wine(x64).zip](https://github.com/Botspot/pi-apps/files/8885199/Wine.x64.zip)

### Confirmations

- [X] I have confirmed that this app is legal and not piracy.
- [X] I have confirmed that this app has never been discussed in https://github.com/Botspot/pi-apps/issues and https://github.com/Botspot/pi-apps/pulls, and it is not in the Pi Apps app list.
- [X] I have confirmed that this app can run on Raspberry Pi.

**Comment by theofficialgman** [comment] 2022-06-12 04:40
>  I have confirmed that this app has never been discussed in https://github.com/Botspot/pi-apps/issues and https://github.com/Botspot/pi-apps/pulls, and it is not in the Pi Apps app list.

you did not confirm this

closing as duplicate of https://github.com/Botspot/pi-apps/issues/807

if you have improvements to make to the zip already there, please post there or create a PR with referencing the that issue and the changes you have made

**Closed by theofficialgman** 2022-06-12 04:40 UTC
Labels: App Request, Zip/PR included

**Comment by liulysunix** [comment] 2022-06-12 05:04
Before I saw this post (https://github.com/Botspot/pi-apps/pulls).I made one myself.I didn"t find any similarities until Iuploaded.I use environment varibles to configure.

"echo 'export WINE64_HOME=~/wine64/opt/wine-stable
export PATH=${WINE64_HOME}/bin:$PATH' >>.profile"

It works quickly.And mine is Wine7.0.0.You can have a try.

**Comment by liulysunix** [comment] 2022-06-12 05:09
And I will debug.
Maybe I won't be here for a few days.Because I have a big test.

**Comment by liulysunix** [comment] 2022-06-12 07:24
use || error "message" for all lines.

**Comment by liulysunix** [comment] 2022-06-12 07:24
[Wine(x64)V2.zip](https://github.com/Botspot/pi-apps/files/8885391/Wine.x64.V2.zip)

**Comment by liulysunix** [comment] 2022-06-12 07:25
It's x86_64 Wine7.0.0 of aarch64

**Comment by liulysunix** [comment] 2022-06-12 07:25
[Wine(x64)V2.zip](https://github.com/Botspot/pi-apps/files/8885394/Wine.x64.V2.zip)
