### ISSUE TITLE
Wine installation issue

### ISSUE THREAD

**Issue by Im-CatDev** [Botspot/pi-apps#2503] opened 2023-12-24 15:49 UTC
### Confirmations

- [X] I searched for similar bug reports in https://github.com/Botspot/pi-apps/issues and found none were relevant.
- [X] I tried updating Pi-Apps and the issue is still not fixed. [How to update Pi-Apps?](https://pi-apps.io/wiki/getting-started/updating-pi-apps/)
- [X] IMPORTANT: I promise to respond to comments on this issue and write a good bug report https://www.softwaretestinghelp.com/how-to-write-good-bug-report/

### What happened?

Wine (x64) installation freezes

### Description

i tried installing wine and it froze on waiting 5 seconds after prefix selection

### What are your system specs (run the following command in your terminal)?

```bash
OS: Debian GNU/Linux 12 (bookworm)
OS architecture: 64-bit
Last updated Pi-Apps on: 12/22/2023 
Kernel: aarch64 6.1.0-rpi7-rpi-v8
Device model: Raspberry Pi 5 Model B Rev 1.0
SOC identifier: bcm2712
Cpu name: Cortex-A76
Ram size: 7.94 GB
Raspberry Pi OS image version: 2023-12-05
Language: en_US.UTF-8
```

### (Recommended) Error log? Terminal output? Debug messages?

```bash
Last part of an installation log, the rest was just a lot of file locations

Creating terminal commands:
  - winecfg
  - wineserver
  - wineboot
  - wine
  - winetricks
Making executable... Done
Cloning into 'wine-stuff'...
Creating Menu launchers... [Desktop Entry]
StartupNotify=true
Terminal=false
Type=Application
Name=Wine Configuration
Exec=wine winecfg
Icon=/opt/wine-8.20/icons/winecfg.png
Categories=System;
Comment=Configure wine
[Desktop Entry]
Name=Winetricks
Comment=Work around problems and install applications under Wine
Exec=bash -c 'BOX64_NOBANNER=1 box64 winetricks --gui'
Terminal=false
Icon=/opt/wine-8.20/icons/winetricks.png
Type=Application
Categories=System;
[Desktop Entry]
Version=1.0
Type=Application
Name=Wine Desktop
Comment=Wine graphical desktop environment to mimic a Windows OS
Icon=/opt/wine-8.20/icons/wine-desktop.png
Exec=wine explorer /desktop=shell,1280x720
Terminal=false
Categories=System;
[Desktop Entry]
Version=1.0
Type=Application
Name=Wine Program Manager
Comment=Install/Remove Windows programs
Icon=/opt/wine-8.20/icons/wine-program-manager.png
Exec=wine uninstaller
Terminal=false
Categories=System;
[Desktop Entry]
Version=1.0
Type=Application
Name=Wine Task Manager
Comment=View running processes within Wine
Icon=/opt/wine-8.20/icons/winetask.png
Exec=wine taskmgr
Terminal=false
Categories=System;
[Desktop Entry]
StartupNotify=false
Version=1.0
Type=Application
Name=Wine Killer
Comment=Terminate any running Wine processes
Icon=/opt/wine-8.20/icons/winestop.png
Exec=wineserver -k
Terminal=false
Categories=System;
[Desktop Entry]
Version=1.0
Type=Application
Name=Wine Reset
Comment=Clean out the default Wine prefix and start over
Icon=/opt/wine-8.20/icons/wine-regenerate.png
Exec=bash -c "yad --window-icon=/opt/wine-8.20/icons/wine-regenerate.png --title='Wine Reset' --text='Are you sure you want to DELETE all data and applications in your Wine prefix and start over?' --center --button=Cancel:1 --button=Yes:0 --on-top && /home/username/pi-apps/etc/terminal-run 'echo y | winetricks annihilate -q ; generate-wine-prefix' 'Generating Wine prefix...'"
Terminal=false
Categories=System;
Done

Checking Wine prefix at /home/username/.wine...
To choose another prefix, set the WINEPREFIX variable.
Waiting 5 seconds...
```

**Comment by theofficialgman** [comment] 2023-12-24 16:10
Please submit a non-truncated full log. You can obtain this from the ~/pi-apps/logs/ folder

**Comment by PTR-inc** [comment] 2023-12-25 03:06
Got the same issue, new pi 4, default image, nothing else installed. Hangs at creating the prefix after the 5 seconds wait

OS: Debian GNU/Linux 12 (bookworm)
OS architecture: 64-bit
Last updated Pi-Apps on: 12/24/2023
Latest Pi-Apps version: 12/24/2023
Kernel: aarch64 6.1.0-rpi7-rpi-v8
Device model: Raspberry Pi 4 Model B Rev 1.5
SOC identifier: bcm2711
Cpu name: Cortex-A72
Ram size: 7.81 GB
Raspberry Pi OS image version: 2023-12-05
Language: en_US.UTF-8

Log attached
[install-incomplete-Wine (x64).log](https://github.com/Botspot/pi-apps/files/13763624/install-incomplete-Wine.x64.log)

**Comment by theofficialgman** [comment] 2023-12-25 04:04
Nothing has changed in wine since November 11th and there were no installation issues at the time of updating.

Please file an issue upstream at box64 as this is likely a regression there when running `wine wineboot` (which is where you are seeing the hang)

**Comment by Botspot** [comment] 2023-12-25 05:26
I can confirm this issue on a Pi5 running Bookworm.

**Comment by Im-CatDev** [comment] 2023-12-25 10:41
Should I still send the logs?

**Comment by hongtm77** [comment] 2023-12-25 14:54
Hi, i got the similar problem on my switchroot L4T Ubuntu Jammy. Previously i have successfully installed on my bionic. The attached is where i stuck forever![image](https://github.com/Botspot/pi-apps/assets/67082163/7045f53d-2b8f-4e5b-946d-ac6eac3070e9)

**Comment by Botspot** [comment] 2023-12-25 16:54
This is fixed now. Please update your apt packages with these commands, then wine should install fine.
```
sudo apt update
sudo apt upgrade -y
```

**Closed by Botspot** 2023-12-25 16:54 UTC
Labels: Upstream Bug

**Comment by theofficialgman** [comment] 2023-12-25 18:36
> This is fixed now. Please update your apt packages with these commands, then wine should install fine.
> 
> ```
> sudo apt update
> sudo apt upgrade -y
> ```

box64 is explicitly upgraded during the wine install script. The user need not perform an upgrade manually. Of course is won't hurt anything if they do.
