### ISSUE TITLE
Suggestion - Blender 2.79b

### ISSUE THREAD

**Issue by MrRKernelPanic** [Botspot/pi-apps#1507] opened 2022-02-18 22:57 UTC
Dear Pi-Apps,

After spending the last 2 hours getting the required files and installing them manually.  Would it be possible for you to add Blender (version 2.79b)  This was last available in the Stretch Repository.  But it's the last 'GOOD' working version of Blender available for the Pi, 2.8 and above require OpenGL3 (no vulkan support yet).  I have instructions on how to install on both 32bit and 64bit Raspberry Pi OS (as they differ due to the architecture.

Let me know if this is something I can help with.  I think people would appreciate this application.  I do, as it allows me to model simple things (or in some cases complex things) and then then 3D print them!!!

Just a thought.

Kind regards,

Mark.

**Comment by Botspot** [comment] 2022-02-18 23:06
You are not the only one trying to get Blender running on Raspberry Pi OS Bullseye. Many are, and if a way arises to makr it work, then I'd gladly add it to Pi-Apps.

I have been monitoring [this forum thread](https://forums.raspberrypi.com/viewtopic.php?p=1975594&hilit=blender#p1975594) to see if anyone can come up with a containerized solution, like an AppImage. @MrRKernelPanic, have you found a way to **safely** install Blender without having to downgrade a bunch of system packages?

**Comment by LeGamerDu92** [comment] 2022-02-20 16:12
just do sudo apt-get install blender but please make it works

**Comment by theofficialgman** [comment] 2022-02-27 01:15
duplicate of issue: https://github.com/Botspot/pi-apps/issues/108

we are aware of blender issues on some pios/debian versions
it will probably be best to wait till vulkan on blender is the default and fully supported for blender to be added to pi-apps
see blender 3.X roadmap for vulkan fully replacing the opengl renderer: https://code.blender.org/2021/10/blender-3-x-roadmap/

**Closed by theofficialgman** 2022-02-27 01:15 UTC
Labels: duplicate, App Request
