### ISSUE TITLE
Steam Crashes on piOS 32bit with 64bit kernel

### ISSUE THREAD

**Issue by Pythonic456** [Botspot/pi-apps#1543] opened 2022-02-28 10:47 UTC
### Confirmations

- [x] I searched for similar bug reports in https://github.com/Botspot/pi-apps/issues and found none were relevant.
- [X] I tried updating Pi Apps and the issue is still not fixed. [How to update Pi Apps?](https://github.com/Botspot/pi-apps#to-update-pi-apps)

### What happened?

Steam won't launch

### Description

Steam won't launch at all. After clicking on the "Steam" option in the launch menu or on the desktop or typing `steam` at a command prompt, it takes about a second to crash. Although it was able to update the first time I launched it, but as soon as it reaches the point of trying to run `/home/pi/.local/share/Steam/ubuntu12_32/steam` it crashes.

The file does exist and here is the `file steam` output:
```
steam: ELF 32-bit LSB shared object, Intel 80386, version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux.so.2, for GNU/Linux 2.6.24, BuildID[sha1]=cea7f50f024709c81230d9271897415cec134c6c, not stripped
```

Thanks in advance!

### What is your operating system?

Raspberry Pi OS 32 bit Buster

### (Optional) Error log? Terminal output? Debug messages?

```bash
pi@raspberrypi4b:~ $ steam
steam.sh[13157]: Running Steam on raspbian 10 64-bit
steam.sh[13157]: STEAM_RUNTIME is enabled by the user
setup.sh[13222]: Steam runtime environment up-to-date!
/home/pi/.local/share/Steam/steam.sh: line 421: /home/pi/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/usr/bin/steam-runtime-check-requirements: cannot execute binary file: Exec format error
steam.sh[13157]: steam-runtime-check-requirements failed with an unexpected nonzero exit status. Trying to continue
/home/pi/.local/share/Steam/steam.sh: line 788: /home/pi/.local/share/Steam/ubuntu12_32/steam: No such file or directory
pi@raspberrypi4b:~ $
```

**Comment by Botspot** [comment] 2022-02-28 15:22
Steam is trying to run 64-bit binaries because it thinks that your operating system is 64-bit.
As Steam is hidden in Pi-Apps on a genuine 64-bit OS, I will assume that you must have the 64-bit kernel enabled. Perhaps an override needs to be made that forces Steam to detect a 32-bit OS. Hopefully that helps. :)

**Comment by Pythonic456** [comment] 2022-03-01 09:05
Any idea on how to do that?

**Comment by theofficialgman** [comment] 2022-04-13 01:28
yeah you could fix it... but it won't be easy. the steam script is VERY stupid
you will need to edit a file within a tar.xz archive

inside the `bootstraplinux_ubuntu12_32.tar.xz` file, there is a file called `steam.sh`
that is a script which does this at some point
```

**Comment by theofficialgman** [comment] 2022-04-13 01:30
you can decompress this file, replace and hardcode it to 32bit
```
function detect_arch()
{
    echo "32-bit"
)
```

**Comment by Botspot** [comment] 2022-04-13 03:43
A potential workaround is to make a custom `uname` script but to place it on a steam-specific location. Then, when running Steam, change the PATH variable so that the `uname` command is replaced by our preferred script.

**Comment by theofficialgman** [comment] 2022-04-13 04:10
> A potential workaround is to make a custom `uname` script but to place it on a steam-specific location. Then, when running Steam, change the PATH variable so that the `uname` command is replaced by our preferred script.

this might even be overkill, to make a script

you can define a function as the same name as a file and it will prefer the function over the file with the same name
so you could just do this:

```
function uname() {
  if [[ "$*" == "-m" ]]; then
    # lie for steam and tell it we are armv7l, this will make it do the "32-bit" test case
    echo "armv7l"     
  else
    command uname "$@"
  fi
}
export -f uname
```

**Comment by Botspot** [comment] 2022-04-13 14:37
> Steam won't launch at all. After clicking on the "Steam" option in the launch menu or on the desktop or typing `steam` at a command prompt, it takes about a second to crash. Although it was able to update the first time I launched it, but as soon as it reaches the point of trying to run `/home/pi/.local/share/Steam/ubuntu12_32/steam` it crashes.

I have the 64-bit kernel enabled on 32-bit PiOS Bullseye, and while running `steam` did say that I was using `raspbian 11 64-bit`, Steam successfully launched. I haven't logged in though. @Pythonic456, exactly *what* did you have to do to cause that crash? If you're unsure, try starting fresh by deleting the `~/.local/share/Steam` folder. First try to replicate the crash, then explain what steps were necessary.

Then, remove your `~/.local/share/Steam` folder again and try running steam like this:
```
function uname() {
  command uname "$@" | sed 's/aarch64/armv7l/'
}
export -f uname

# launch steam
steam
```

**Comment by Pythonic456** [comment] 2022-04-13 18:20
As to exactly what I did, here you go:
Installed Bullseye 32 bit
Installed piapps 
Installed steam

That's it. I will go try enabling the 64 bit kernel and running it then. I will keep you updated.

**Comment by Pythonic456** [comment] 2022-04-13 18:31
Sorry, um...
I forgot to look how old this is. I now use Bullseye, and have no problems (I am using 32 bit user land and 64 bit kernel). Sorry about that! I'm pretty sure it works on Buster but I had probably messed with stuff.

**Comment by Botspot** [comment] 2022-04-13 18:34
Closing this issue, as it seems to be a one-off and is not reproducible. If this error was reproducible on Buster we'd fix it.

**Closed by Botspot** 2022-04-13 18:34 UTC
Labels: bug
