### ISSUE TITLE
Flameshot uploading error...

### ISSUE THREAD

**Issue by cdkw2** [Botspot/pi-apps#2413] opened 2023-08-02 14:30 UTC
### Confirmations

- [X] I searched for similar bug reports in https://github.com/Botspot/pi-apps/issues and found none were relevant.
- [X] I tried updating Pi Apps and the issue is still not fixed. [How to update Pi Apps?](https://github.com/Botspot/pi-apps#to-update-pi-apps)
- [X] IMPORTANT: I promise to respond to comments on this issue and write a good bug report https://www.softwaretestinghelp.com/how-to-write-good-bug-report/

### What happened?

Flameshot is not letting me upload images to Imgur

### Description

So I use this app from your app store a lot called "Flameshot". It has a feature of uploading the screenshot directly to Imgur and I have noticed that It has not been working lately. It just gives me this error screen. Please tell me what should my further steps be?

![image](https://github.com/Botspot/pi-apps/assets/67598073/85c00c18-7f9c-43a8-a1ff-d5be812a528d)

### What are your system specs (run the following command in your terminal)?

```bash
OS: Debian GNU/Linux 11 (bullseye)
OS architecture: 64-bit
Last updated Pi-Apps on: 08/02/2023
Latest Pi-Apps version: 08/02/2023
Kernel: aarch64 6.1.21-v8+
Device model: Raspberry Pi 4 Model B Rev 1.2 
Cpu name: Cortex-A72
Ram size: 3.79 GB
Raspberry Pi OS image version: 2023-05-03
Language: en_US.UTF-8
```

### (Recommended) Error log? Terminal output? Debug messages?

```bash
Nothing here ¯\_(ツ)_/¯
```

**Comment by Botspot** [comment] 2023-08-02 14:35
This is likely a Flameshot issue, and not caused by Pi-Apps.
I see that you have already opened an issue on the Flameshot repo here: https://github.com/flameshot-org/flameshot/issues/3288

Closing this issue for now, as there is nothing I can do for you.

**Closed by Botspot** 2023-08-02 14:35 UTC
Labels: bug

**Comment by cdkw2** [comment] 2023-08-02 14:37
Oh thank you very much I just wanted to know if you guys have experienced this issue before.

**Comment by cdkw2** [comment] 2023-08-02 15:42
Hey @Botspot I just fixed the error by myself. I just uninstalled the app and recompiled on my own from source. That seems to fix the issue. SO maybe, just maybe the fault is with the version present on the app store? Or maybe this is just a big coincidence. Anyways do consult me if you have anything to ask.

**Comment by theofficialgman** [comment] 2023-08-02 15:48
The flameshot Deb from pi-apps comes directly from flameshots official releases on GitHub. There is a pi-apps auto updater but flameshots hasn't made a release since last year.

Best to ask upstream to finally make a release if the issue was already fixed in their master branch.

**Comment by cdkw2** [comment] 2023-08-02 15:49
I completely agree but their community doesn't seem as fast as pi-apps.
