### ISSUE TITLE
RealVNC (64 bit)

### ISSUE THREAD

**Issue by slashtechno** [Botspot/pi-apps#320] opened 2021-02-03 18:16 UTC
Normal Raspberry Pi OS comes with RealVNC but on any 64 bit OS RealVNC does not seem to work. Is it possible to add a way to install RealVNC for **64 bit users only**?  [This forum post](https://www.raspberrypi.org/forums/viewtopic.php?t=288769) should help.

**Comment by Itai-Nelken** [comment] 2021-02-03 18:18
there are 64bit debs in the rpi archive: http://archive.raspberrypi.org/debian/pool/main/r/realvnc-vnc/

**Comment by slashtechno** [comment] 2021-02-03 19:01
I searched up ways to install RealVNC on 64 bit Raspberry Pi and did not find this. Thank you for finding this but I think adding this to Pi-Apps will save others time.

**Comment by Botspot** [comment] 2021-02-03 19:37
> there are 64bit debs in the rpi archive: http://archive.raspberrypi.org/debian/pool/main/r/realvnc-vnc/

I'm surprised those are in there too.  
How did you find that?

**Comment by Itai-Nelken** [comment] 2021-02-03 19:40
> > there are 64bit debs in the rpi archive: http://archive.raspberrypi.org/debian/pool/main/r/realvnc-vnc/
> 
> I'm surprised those are in there too.
> How did you find that?

I wanted to download the armhf deb and I saw there are arm64 ones, never tried them though.

**Comment by slashtechno** [comment] 2021-02-03 21:16
Another problem may arise with Ubuntu 64 bit and other 64 bit operating systems regarding dependencies.

**Comment by Itai-Nelken** [comment] 2021-02-03 21:39
> Another problem may arise with Ubuntu 64 bit and other 64 bit operating systems regarding dependencies.

for the RPi version of VNC sever you need some libs.
they are listed in the video linked here: https://www.raspberrypi.org/forums/viewtopic.php?t=288769

**Comment by slashtechno** [comment] 2021-02-03 22:29
So is this going to be added to Pi-Apps?

**Comment by Botspot** [comment] 2021-02-04 03:44
> So is this going to be added to Pi-Apps?

If someone makes the install script for it. ;)

**Comment by slashtechno** [comment] 2021-02-04 15:17
I **might** be able to make an install script. How do I make it show up only on 64 bit systems? 

ETA 02.06.2021

**Comment by Botspot** [comment] 2021-02-04 15:22
> I **might** be able to make an install script.

It's pretty easy. Thanks for giving it a try.

> How do I make it show up only on 64 bit systems?

Pi-Apps is smart. Each app can have separate install scripts for 64-bit and 32-bit systems.  
If your OS is 32-bit and the given app does not have an `install-32` script, then Pi-Apps is smart enough to hide that app.

The App Maker has an option for that, by the way.

**Comment by slashtechno** [comment] 2021-02-04 15:50
Okay thank you.

**Comment by slashtechno** [comment] 2021-02-04 19:40
Here is the competed install script. However, I do not know how to do this in a .sh file `sudo gedit /etc/gdm3/custom.conf     and Uncomment “WaylandEnable=false”`

```
cd

sudo dpkg --add-architecture armhf

sudo dpkg --print-foreign-architectures

sudo apt update

sudo apt --fix-broken install -y

sudo apt install libx11-6 -y

sudo apt --fix-broken install -y

sudo apt install libc6 -y

sudo apt --fix-broken install -y

sudo apt install libgcc1 -y

sudo apt --fix-broken install -y

sudo apt --fix-broken install -y

sudo apt install libx11-6 -y

sudo apt --fix-broken install -y

sudo apt install libxext6 -y

sudo apt --fix-broken install -y

sudo apt install libxtst6 -y

sudo apt --fix-broken install -y

cd /

cd /usr/lib

sudo wget https://github.com/raspberrypi/firmware/raw/master/opt/vc/lib/libbcm_host.so

sudo wget https://github.com/raspberrypi/firmware/raw/master/opt/vc/lib/libvcos.so

sudo wget https://github.com/raspberrypi/firmware/raw/master/opt/vc/lib/libmmal_core.so

sudo wget https://github.com/raspberrypi/firmware/raw/master/opt/vc/lib/libmmal_components.so

sudo wget https://github.com/raspberrypi/firmware/raw/master/opt/vc/lib/libmmal_util.so

sudo wget https://github.com/raspberrypi/firmware/raw/master/opt/vc/lib/libmmal_vc_client.so

sudo wget https://github.com/raspberrypi/firmware/raw/master/opt/vc/lib/libvchiq_arm.so

sudo wget https://github.com/raspberrypi/firmware/raw/master/opt/vc/lib/libvcsm.so

sudo wget https://github.com/raspberrypi/firmware/raw/master/opt/vc/lib/libcontainers.so

cd /

cd ~

wget http://archive.raspberrypi.org/debian/pool/main/r/realvnc-vnc/realvnc-vnc-server_6.7.2.42622_armhf.deb

sudo dpkg -i realvnc-vnc-server_6.7.2.42622_armhf.deb

sudo systemctl enable vncserver-x11-serviced.service

sudo systemctl enable vncserver-virtuald.service

sudo systemctl start vncserver-x11-serviced.service

sudo systemctl start vncserver-virtuald.service

sudo vnclicensewiz 

sudo apt --fix-broken install

#sudo gedit /etc/gdm3/custom.conf     and Uncomment “WaylandEnable=false”
```

**Comment by Itai-Nelken** [comment] 2021-02-04 20:12
>```bash
>sudo dpkg --add-architecture armhf
>
>sudo dpkg --print-foreign-architectures
>```

this part isn't necessary if you are in a armhf OS, and if you are in a arm64 OS you can use this: http://archive.raspberrypi.org/debian/pool/main/r/realvnc-vnc/realvnc-vnc-server_6.7.2.43081_arm64.deb
and then you son't need it as well.

**Comment by slashtechno** [comment] 2021-02-04 20:16
The reason I did this was because that .deb does not seem to work for me.

**Comment by Itai-Nelken** [comment] 2021-02-04 20:36
those lines:
>```bash
>sudo systemctl enable vncserver-x11-serviced.service
>
>sudo systemctl enable vncserver-virtuald.service
>
>sudo systemctl start vncserver-x11-serviced.service
>
>sudo systemctl start vncserver-virtuald.service
>
>sudo vnclicensewiz 
>```

aren't necessary as part of the script, what they do is enable the vnc service to start in startup (the `sudo systemctl enable ...`) and start vnc server (the `sudo systemctl start ...`).
the `sudo vnclicensewiz ` command just opens the login window that is accessible from the main window.

@slashtechno I'll take your script, improve it, and add it to pi-apps.

**Comment by slashtechno** [comment] 2021-02-04 20:59
Okay, thank you. Could I please be put in the credits?

**Comment by Itai-Nelken** [comment] 2021-02-04 21:01
> Okay, thank you @Itai-Nelken . Could I please be put in the credits?

Of course!

**Comment by Botspot** [comment] 2021-03-01 22:30
How's it going?

**Comment by slashtechno** [comment] 2021-03-01 22:35
> How's it going?

I think @Itai-Nelken is working on this. In #343 @timonrus posted a tutorial on how to install armf RaspSpotify on ARM64.

**Comment by Botspot** [comment] 2021-03-02 03:13
How's it going? I have yet to see this actually work. (But _have_ seen several failed attempts)

**Comment by Itai-Nelken** [comment] 2021-03-02 12:13
@Botspot I'm working on this, but I didn't have the time to start writing the scripts yet.
the idea is to check what OS you are running (Ubuntu, RPiOS, other) and then if needed download some extra libs that are needed. then download the arm64 deb from here: http://archive.raspberrypi.org/debian/pool/main/r/realvnc-vnc/realvnc-vnc-server_6.7.2.43081_arm64.deb
and make a menu shortcut if needed.

**Comment by mobilegmYT** [comment] 2021-04-20 20:14
@Itai-Nelken I used this a while ago for arm64 install on 64-bit RPI OS. https://github.com/mtbiker-s/ubuntu20.10-rpi-install-vnc

**Comment by Itai-Nelken** [comment] 2021-04-20 20:19
> @Itai-Nelken I used this a while ago for arm64 install on 64-bit RPI OS. https://github.com/mtbiker-s/ubuntu20.10-rpi-install-vnc

@CleanMachine1 that's basically what I want to do, thanks for sharing the link. it will help me getting this script done.

**Comment by mobilegmYT** [comment] 2021-04-20 20:20
> > @Itai-Nelken I used this a while ago for arm64 install on 64-bit RPI OS. https://github.com/mtbiker-s/ubuntu20.10-rpi-install-vnc
> 
> @CleanMachine1 that's basically what I want to do, thanks for sharing the link. it will help me getting this script done.

Are you sure you pinged the right guy? I'm Pi News, not CleanMachine.

**Comment by Itai-Nelken** [comment] 2021-04-20 20:22
@mobilegmYT oops, sorry. you have very similar pfp's...

**Comment by CleanMachine1** [comment] 2021-04-20 20:27
@Itai-Nelken https://myoctocat.com/

**Comment by Itai-Nelken** [comment] 2021-04-24 08:29
I got it working using the script you linked @mobilegmYT !
I'm editing the script a bit and writing a uninstall script so it works with pi-apps.
<img width="1440" alt="Screen Shot 2021-04-24 at 11 25 11 AM" src="https://user-images.githubusercontent.com/70802936/115952640-ddc8de80-a4ef-11eb-85c4-0265b6127038.png">

**Comment by Itai-Nelken** [comment] 2021-04-24 10:09
done! but the desktop shortcut isn't launching the launcher script on Ubuntu 21.04.
[RealVNC VNC server.zip](https://github.com/Botspot/pi-apps/files/6369371/RealVNC.VNC.server.zip)

**Comment by Itai-Nelken** [comment] 2021-05-24 17:19
note to myself: maybe using pi-apps's `terminal-run` script will fix the launching issue.

**Comment by Itai-Nelken** [comment] 2021-07-20 10:06
on RPiOS 64bit VNC server is installable from apt and works fine. the problem is non-RPiOS OS's.
I'll modify the script to just `apt install` (with `pkg-install`) it if the OS is RPiOS.

**Comment by Botspot** [comment] 2021-09-15 22:49
I'm interested in adding this to Pi-Apps.
Are there any changes that need to be made for this to be added?

BTW, I don't think the menu launcher to choose to enable or start vnc server is necessary - it's probably better to it mimic `raspi-config`'s VNC setting by enabling and starting the service. I think the menu launcher is unnecessary.

**Comment by slashtechno** [comment] 2021-10-14 02:03
> I'm interested in adding this to Pi-Apps.
> Are there any changes that need to be made for this to be added?
> 
> BTW, I don't think the menu launcher to choose to enable or start vnc server is necessary - it's probably better to it mimic `raspi-config`'s VNC setting by enabling and starting the service. I think the menu launcher is unnecessary.

Is the next step to make an install and uninstall script?

**Comment by Itai-Nelken** [comment] 2021-10-14 15:25
@slashtechno there already is one:https://github.com/Botspot/pi-apps/issues/320#issuecomment-826069266
It just needs a bit of fixing for the launch part.

**Comment by slashtechno** [comment] 2021-10-14 22:06
> @slashtechno there already is one:[#320 (comment)](https://github.com/Botspot/pi-apps/issues/320#issuecomment-826069266) It just needs a bit of fixing for the launch part.

@Itai-Nelken Oh okay, my bad.

**Comment by cycool29** [comment] 2021-10-15 00:21
As of https://github.com/Botspot/pi-apps/issues/320#issuecomment-920444039, I removed the desktop entry and launcher script parts. Not tested since I don't have any aarch or arm64 Linux OS machine but should work.
[realvnc-arm64.zip](https://github.com/Botspot/pi-apps/files/7350002/realvnc-arm64.zip)

**Comment by theofficialgman** [comment] 2022-04-12 21:32
there seems to be a lot of beating around the bush here avoiding building realvnc from source and fixing the problems...

there also seems to be some confusion here as to what is wanted. do you want the server or client? or both?
the server for the computer you want to control.
the client is for the computer you want to control from (I imagine this is what you wanted)

also, why not just use the official packages from the realvnc website?
I imagine they might work without any extra hacks. 

https://www.realvnc.com/en/connect/download/vnc/raspberrypi/
vnc server
https://downloads.realvnc.com/download/file/vnc.files/VNC-Server-6.9.1-Linux-ARM.deb
https://downloads.realvnc.com/download/file/vnc.files/VNC-Server-6.9.1-Linux-ARM64.deb

vnc client
https://downloads.realvnc.com/download/file/viewer.files/VNC-Viewer-6.22.315-Linux-ARM.deb
https://downloads.realvnc.com/download/file/viewer.files/VNC-Viewer-6.22.315-Linux-ARM64.deb

**Comment by Itai-Nelken** [comment] 2022-04-19 20:55
> there seems to be a lot of beating around the bush here avoiding building realvnc from source and fixing the problems...
> 
> there also seems to be some confusion here as to what is wanted. do you want the server or client? or both? the server for the computer you want to control. the client is for the computer you want to control from (I imagine this is what you wanted)
> 
> also, why not just use the official packages from the realvnc website? I imagine they might work without any extra hacks.
> 
> https://www.realvnc.com/en/connect/download/vnc/raspberrypi/ vnc server https://downloads.realvnc.com/download/file/vnc.files/VNC-Server-6.9.1-Linux-ARM.deb https://downloads.realvnc.com/download/file/vnc.files/VNC-Server-6.9.1-Linux-ARM64.deb
> 
> vnc client https://downloads.realvnc.com/download/file/viewer.files/VNC-Viewer-6.22.315-Linux-ARM.deb https://downloads.realvnc.com/download/file/viewer.files/VNC-Viewer-6.22.315-Linux-ARM64.deb

Both the server AND the viewer are wanted.
I had been using the debs from the rpi repo, I hadn't noticed they were uploaded to the RealVNC website.
that will make things easier.

The biggest problem is running on non-rpiOS OSs (Ubuntu for example). If I remember correctly, the viewer works fine, but the server has some problems because of some rpi-specific libraries that it expects in weird locations.
I haven't tested my scripts since https://github.com/Botspot/pi-apps/issues/320#issuecomment-826069266, so I don't know if any of the  problems where fixed with bullseye and/or the new versions on the realVNC website.

There is also the problem of how to enable/disable the server service as I don't think it should be on all the time. I fixed that in my script with a custom yad launcher script.
@Botspot thinks we should mimic RPiOS with a toggle to enable and start / disable and stop. that is a better idea, but the only place I can think of putting the toggle is in a custom launcher.

That is all the remaining problems I think. I don't have time to work on this and probably won't have for a long time, so if someone else can take over and finish it would be great!

**Comment by theofficialgman** [comment] 2024-08-27 18:02
Closing as unable to use on modern (wayland) desktop environments like used on default Ubuntu Noble and PiOS Bookworm.

**Closed by theofficialgman** 2024-08-27 18:02 UTC
Labels: App Request
