### ISSUE TITLE
Installing Hyper or Tabby doesn't add Desktop Entry

### ISSUE THREAD

**Issue by touhidurrr** [Botspot/pi-apps#1733] opened 2022-04-27 19:38 UTC
### Confirmations

- [X] I searched for similar bug reports in https://github.com/Botspot/pi-apps/issues and found none were relevant.
- [X] I tried updating Pi Apps and the issue is still not fixed. [How to update Pi Apps?](https://github.com/Botspot/pi-apps#to-update-pi-apps)

### What happened?

No Desktop Entry on Accessories

### Description

I think Titles already explains it.
I trying restarting but no Desktop Entry of Hyper at Menu > Accessories.

### What is your operating system?

Raspberry Pi OS armhf

**Comment by Botspot** [comment] 2022-04-27 19:44
Thanks for reporting.

I have been able to reproduce this on 32-bit RPiOS. Problem was caused by some faulty code to move the Desktop Entry to Accessories. Rather than moving it to Accessories, it ended up erasing the contents of the Desktop Entry file.
I'll fix it in a few minutes.

**Comment by touhidurrr** [comment] 2022-04-27 19:48
@Botspot it happens on Tabby too

**Comment by Botspot** [comment] 2022-04-27 20:00
Hyper has been fixed with commit c3c1e03fe72b60a73d7b108052c396df71d0b5e2

**Comment by Botspot** [comment] 2022-04-27 20:00
Tabby doesn't have any code that moves the menu category, but I'll install it anyway to see if I can spot a problem.

**Comment by Botspot** [comment] 2022-04-27 20:01
Tabby was in the System Tools category.

**Comment by Botspot** [comment] 2022-04-27 20:23
Tabby's description file said to look for it in the Accessories category, so with commit 03aefb98461774c36119e161839de341bb6566c2 I moved it there.

**Closed by Botspot** 2022-04-27 20:23 UTC
Labels: bug
