### ISSUE TITLE
Pi-apps display issues in fyde os linux(beta) raspberry pi

### ISSUE THREAD

**Issue by sachjith** [Botspot/pi-apps#923] opened 2021-08-19 14:53 UTC
Other hard apps like vscode gparted seems to work in the linux(beta) vm but pi-apps has some display issues

**Comment by Botspot** [comment] 2021-08-19 22:44
We don't have time to install FydeOS on a RPi and determine what you mean by "some display issues". Could you explain?

Does the pi-apps GUI work as intended? When you attempt to install something, does a terminal appear or are you immediately directed right back to Pi-Apps?

**Comment by Jerry8538** [comment] 2021-08-22 10:21
Let me see if I can reproduce this. Just to confirm, this is referring to [FydeOS](https://fydeos.io/download/device/rpi4-fydeos), and not [ChromiumOS](https://github.com/FydeOS/chromium_os-raspberry_pi), right?

**Comment by pranavr2003** [comment] 2021-08-31 05:46
@Botspot @Jerry8538 Have a look at #940

**Comment by Botspot** [comment] 2021-08-31 13:08
> Let me see if I can reproduce this. Just to confirm, this is referring to [FydeOS](https://fydeos.io/download/device/rpi4-fydeos), and not [ChromiumOS](https://github.com/FydeOS/chromium_os-raspberry_pi), right?

@Jerry8538, were you ever able to reproduce this? It seems like an issue on FydeOS's side. Pi-Apps uses a standalone GTK dialog utility called `yad`. There's nothing Pi-Apps could do to cause, or to solve a problem like this.

**Comment by Jerry8538** [comment] 2021-09-01 18:01
Sorry for the late response, but I can reproduce this. I tried running the GUI and installing using the script and neither work. 
The GUI looks like @pranavr2003 's screenshot but the buttons seem to be clickable, and the install script just resulted in a lockup, although this may be my Pi's fault, it's only got 2 gigs of RAM.

**Comment by Jerry8538** [comment] 2021-09-01 18:06
When I run pi-apps from the terminal - 
```
jerr8538@penguin:~$ pi-apps
   ┏━━━┓
┏━━┻━━━┻━━┓
┃  ⬛⬛⬛ ┃  ▕ᑐ • ▁  ʌ
┃  ⬛⬛⬛ ┃  ▕  │   ╱‾╲▕ᑐ ▕ᑐ Ｓ
┃  ⬛⬛⬛ ┃            ▕  ▕
╰━━━━━━━━━╯

Timestamps match.
Reading list file...

(yad:5619): Gdk-WARNING **: 11:04:00.171: ../../../../../gdk/x11/gdkwindow-x11.c:5611 drawable is not a native X11 window
xkbcommon: ERROR: Key "<CAPS>" added to modifier map for multiple modifiers; Using Mod3, ignoring Lock

(yad:5748): Gdk-WARNING **: 11:04:00.928: ../../../../../gdk/x11/gdkwindow-x11.c:5611 drawable is not a native X11 window
xkbcommon: ERROR: Key "<CAPS>" added to modifier map for multiple modifiers; Using Mod3, ignoring Lock

```

**Comment by Jerry8538** [comment] 2021-09-01 18:21
Yeah, I tried installing CommanderPi here's the terminal output - 
```
jerr8538@penguin:~$ pi-apps/manage install CommanderPi
Installing CommanderPi...
Running pkg-install...
Waiting until APT locks are released... Done
Running sudo apt update...

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

Hit:1 https://deb.debian.org/debian buster InRelease
Ign:2 https://storage.googleapis.com/cros-packages/92 buster InRelease
Hit:3 https://deb.debian.org/debian-security buster/updates InRelease
Hit:4 https://storage.googleapis.com/cros-packages/92 buster Release
Reading package lists...
Building dependency tree...
Reading state information...
1 package can be upgraded. Run 'apt list --upgradable' to see it.
One package can be upgraded. Please consider running sudo apt full-upgrade.

Creating dummy deb...
Waiting until APT locks are released... Done

Installing dummy deb...


The following packages were automatically installed and are no longer required:
  cmake cmake-data g++ g++-8 gcc gcc-8 gir1.2-glib-2.0 gir1.2-ibus-1.0 libalut-dev libalut0 libarchive13 libasan5 libasound2-dev libatomic1 libblkid-dev libc-dev-bin libc6-dev libcc1-0 libdbus-1-dev libdpkg-perl libdrm-dev libdrm-etnaviv1
  libdrm-freedreno1 libdrm-tegra0 libegl1-mesa-dev libffi-dev libfreetype6-dev libgcc-8-dev libgirepository-1.0-1 libgl1-mesa-dev libgles1 libgles2 libgles2-mesa-dev libglib2.0-dev libglib2.0-dev-bin libglu1-mesa libglu1-mesa-dev
  libglvnd-core-dev libglvnd-dev libibus-1.0-5 libibus-1.0-dev libice-dev libitm1 libjsoncpp1 liblsan0 libmount-dev libogg-dev libopenal-data libopenal-dev libopenal1 libopengl0 libpcre16-3 libpcre3-dev libpcre32-3 libpcrecpp0v5 libpng-dev
  libpthread-stubs0-dev libpulse-dev libpulse-mainloop-glib0 librhash0 libsdl2-2.0-0 libselinux1-dev libsepol1-dev libsndio-dev libsndio7.0 libstdc++-8-dev libtsan0 libubsan1 libudev-dev libuv1 libwayland-bin libwayland-dev libx11-dev
  libx11-xcb-dev libxau-dev libxcb-dri2-0-dev libxcb-dri3-dev libxcb-glx0-dev libxcb-present-dev libxcb-randr0-dev libxcb-render0-dev libxcb-shape0-dev libxcb-sync-dev libxcb-xfixes0-dev libxcb1-dev libxcursor-dev libxdamage-dev libxdmcp-dev
  libxext-dev libxfixes-dev libxrender-dev libxshmfence-dev libxxf86vm-dev linux-libc-dev mesa-common-dev pkg-config python3-distutils python3-lib2to3 uuid-dev x11proto-core-dev x11proto-damage-dev x11proto-dev x11proto-dri2-dev
  x11proto-fixes-dev x11proto-gl-dev x11proto-input-dev x11proto-xext-dev x11proto-xf86vidmode-dev xorg-sgml-doctools xtrans-dev zlib1g-dev
Use 'sudo apt autoremove' to remove them.
The following additional packages will be installed:
  blt libimagequant0 libtcl8.6 libtk8.6 libwebpdemux2 libxcursor-dev python3-pil python3-pil.imagetk python3-tk tk8.6-blt2.5
Suggested packages:
  blt-demo tcl8.6 tk8.6 python-pil-doc python3-pil-dbg python3-pil.imagetk-dbg tix python3-tk-dbg
Recommended packages:
  python3-olefile
The following NEW packages will be installed:
  blt libimagequant0 libtcl8.6 libtk8.6 libwebpdemux2 pi-apps-08f5abf3 python3-pil python3-pil.imagetk python3-tk tk8.6-blt2.5
The following packages will be upgraded:
  libxcursor-dev
1 upgraded, 10 newly installed, 0 to remove and 0 not upgraded.
1 not fully installed or removed.
debconf: delaying package configuration, since apt-utils is not installed
(Reading database ... 41924 files and directories currently installed.)

Apt finished.
Cloning into 'CommanderPi'...
/home/jerr8538/CommanderPi
Checking for tkinter: Status: install ok installed
sudo: pip3: command not found
Reading package lists...
Building dependency tree...
Reading state information...
git is already the newest version (1:2.20.1-2+deb10u3).
git set to manually installed.
python3-pil is already the newest version (5.4.1-2+deb10u2).
python3-pil set to manually installed.
python3-pil.imagetk is already the newest version (5.4.1-2+deb10u2).
python3-pil.imagetk set to manually installed.
python3-tk is already the newest version (3.7.3-1).
python3-tk set to manually installed.
The following packages were automatically installed and are no longer required:
  cmake cmake-data g++ g++-8 gcc gcc-8 gir1.2-glib-2.0 gir1.2-ibus-1.0
  libalut-dev libalut0 libarchive13 libasan5 libasound2-dev libatomic1
  libblkid-dev libc-dev-bin libc6-dev libcc1-0 libdbus-1-dev libdpkg-perl
  libdrm-dev libdrm-etnaviv1 libdrm-freedreno1 libdrm-tegra0 libegl1-mesa-dev
  libffi-dev libfreetype6-dev libgcc-8-dev libgirepository-1.0-1
  libgl1-mesa-dev libgles1 libgles2 libgles2-mesa-dev libglib2.0-dev
  libglib2.0-dev-bin libglu1-mesa libglu1-mesa-dev libglvnd-core-dev
  libglvnd-dev libibus-1.0-5 libibus-1.0-dev libice-dev libitm1 libjsoncpp1
  liblsan0 libmount-dev libogg-dev libopenal-data libopenal-dev libopenal1
  libopengl0 libpcre16-3 libpcre3-dev libpcre32-3 libpcrecpp0v5 libpng-dev
  libpthread-stubs0-dev libpulse-dev libpulse-mainloop-glib0 librhash0
  libsdl2-2.0-0 libselinux1-dev libsepol1-dev libsndio-dev libsndio7.0
  libstdc++-8-dev libtsan0 libubsan1 libudev-dev libuv1 libwayland-bin
  libwayland-dev libx11-dev libx11-xcb-dev libxau-dev libxcb-dri2-0-dev
  libxcb-dri3-dev libxcb-glx0-dev libxcb-present-dev libxcb-randr0-dev
  libxcb-render0-dev libxcb-shape0-dev libxcb-sync-dev libxcb-xfixes0-dev
  libxcb1-dev libxcursor-dev libxdamage-dev libxdmcp-dev libxext-dev
  libxfixes-dev libxrender-dev libxshmfence-dev libxxf86vm-dev linux-libc-dev
  mesa-common-dev pkg-config python3-distutils python3-lib2to3 uuid-dev
  x11proto-core-dev x11proto-damage-dev x11proto-dev x11proto-dri2-dev
  x11proto-fixes-dev x11proto-gl-dev x11proto-input-dev x11proto-xext-dev
  x11proto-xf86vidmode-dev xorg-sgml-doctools xtrans-dev zlib1g-dev
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
/home/jerr8538/CommanderPi
[Desktop Entry]
Name=CommanderPi
Comment=System info and overclocking
Exec=/home/jerr8538/CommanderPi/src/start.sh
Icon=/home/jerr8538/CommanderPi/src/icons/Icon.png
Categories=Utility;
Version=1.0
Type=Application
Terminal=false
StartupNotify=true
Save desktop shortcut to /home/jerr8538/Desktop/commanderpi.desktop
Couldn't create desktop shortcut!
Save menu shortcut to /usr/share/applications/commanderpi.desktop
chown: cannot access '/home/jerr8538/Desktop/commanderpi.desktop': No such file or directory
chmod: cannot access '/home/jerr8538/Desktop/commanderpi.desktop': No such file or directory
failed to run install.sh!

Failed to install CommanderPi with install script!
▲ Need help? Copy the ENTIRE terminal output or take a screenshot.
Please ask on Github: https://github.com/Botspot/pi-apps/issues/new/choose
Or on Discord: https://discord.gg/RXSTvaUvuu
```
So it wasn't able to create a desktop shortcut due to there being no such directory, it seems to have installed fine, I just can't run it, maybe due to the low RAM on my Pi.

**Comment by pranavr2003** [comment] 2021-09-02 04:47
@Jerry8538 Do other apps install and work? Like maybe Zoom or Firefox or Micecraft Java or maybe PiKISS?

**Comment by pranavr2003** [comment] 2021-09-02 05:09
@Jerry8538 @Botspot  I'm not sure this is due to any low RAM. From my understanding and the terminal info (I haven't tried it), CommanderPi seems to be the RPi-OS equivalent of WOR_cp.exe that lets you overclock and gives you a GUI version as a way to modify the `config.txt`, `cmdline.txt` etc.. If you install it on the Linux subsystem of Chromium/Fyde, the app may not even launch, since it looks for a `config.txt` file on a pre-assigned destination, which is usually `/boot/config.txt`. However on the Fyde Team's build of Chromium/Fyde OS, `config.txt` is located on the 12th partition (`/dev/sda12/` on which EFI-SYSTEM is located), so if you have to modify that, you'll have to mount that partition first, and then `cd` over to `mnt/`, where you'll then find `config.txt`. CommanderPi assumes you're running this on the Pi (which has just one partition to begin with), and directly looks in `/boot/config.txt/`, which (obviously) doesn't exist and hence it can't give you any info about the system whatsoever.

(Super) long story short, you'll have to try with apps other than those that mess around in `FILESYSTEM ROOT`

**Comment by pranavr2003** [comment] 2021-09-02 06:25
Also I'm able to install `gparted` and `docker`, so the issue is clearly not with the Linux container

**Comment by Botspot** [comment] 2021-09-26 17:11
> Also I'm able to install `gparted` and `docker`, so the issue is clearly not with the Linux container

Well the issue is clearly not with Pi-Apps either. Pi-Apps uses the `yad` dialog to do everything. If yad is malfunctioning, it's not pi-apps's fault, it's yad's fault.
As a result, I'm closing this issue as it's not the kind of problem Pi-Apps developers could fix.

I highly suggest opening an issue on the [yad github repository](https://github.com/v1cont/yad). Someone over there is bound to know what the issue is.

**Closed by Botspot** 2021-09-26 17:11 UTC
