### ISSUE TITLE
ThemeConverter not Working

### ISSUE THREAD

**Issue by SudoAptonator** [Botspot/pi-apps#2173] opened 2022-11-06 02:25 UTC
### Cool ideas?

Techcoder20's MacOS Themeconverter doesn't work. I went on his github (https;//github.com/Techcoder20) page and I copied and pasted the git clone command in my terminal and it didn't run or work (It actually destroyed my pi). Could you please fix this? _-SudoAptonator_

**Comment by theofficialgman** [comment] 2022-11-06 14:46
Duplicate of https://github.com/Botspot/pi-apps/issues/2110

Closing. We are aware, all theme scripts are broken on bullseye as it uses gtk3. Theme scripts were written for gtk2 on buster

**Closed** 2022-11-06 14:47 UTC
Labels: suggestion
