### ISSUE TITLE
Not installing Macos theme

### ISSUE THREAD

**Issue by Dwaitp** [Botspot/pi-apps#2302] opened 2023-04-12 23:35 UTC
### Confirmations

- [X] I searched for similar bug reports in https://github.com/Botspot/pi-apps/issues and found none were relevant.
- [X] I tried updating Pi Apps and the issue is still not fixed. [How to update Pi Apps?](https://github.com/Botspot/pi-apps#to-update-pi-apps)
- [X] IMPORTANT: I promise to respond to comments on this issue and write a good bug report https://www.softwaretestinghelp.com/how-to-write-good-bug-report/

### What happened?

App wont install

### Description

Failled

### What are your system specs (run the following command in your terminal)?

```bash
OS: Raspbian GNU/Linux 11 (bullseye)
OS architecture: 32-bit
Last updated Pi-Apps on: 04/10/2023
Latest Pi-Apps version: 04/10/2023
Kernel: aarch64 6.1.21-v8+
Device model: Raspberry Pi 4 Model B Rev 1.5 
Cpu name: Cortex-A72
Ram size: 3.79 GB
Raspberry Pi OS image version: 2023-02-21
Language: en_US.UTF-8
```

### (Recommended) Error log? Terminal output? Debug messages?

```bash
🭊🬹🬹🬹🬿                                                          
 🭇🬭🬭🬎🬭🬭🬭🬎🬭🬭🬼                                                       
 🮉  ▄ ▄ ▄  ▋   █▀▀🭍 ▄                                              
 🮉  ▄ ▄ ▄  ▋   █▄▄🭞 ▄ ▄▄ 🭂▀▀█ █▀▀🭍 █▀▀🭍 🭂🬰🬰🬰                       
 🮉  ▄ ▄ ▄  ▋   █    █    🭓▄▄█ █▄▄🭞 █▄▄🭞 ▄▄▄🭞                       
 🭦🭏🬭🬭🬭🬭🬭🬭🬭🭄🭛                  █    █                               
                                                                   
                                                                   
tail: warning: --retry only effective for the initial open
Gtk-Message: 19:30:57.022: Failed to load module "appmenu-gtk-module"
Installing Mac OS Theme...

Will install these packages: compton plank xfwm4 xfce4-settings nautilus yad xfce4-panel xfce4-appmenu-plugin xfce4-statusnotifier-plugin xfce4-pulseaudio-plugin blueman figlet lolcat python3-pil python3-pil.imagetk network-manager network-manager-gnome 
Creating an empty apt-package to install the necessary apt packages...
It will be named: pi-apps-0e9de418
Depends: blueman, compton, figlet, lolcat, nautilus, network-manager, network-manager-gnome, plank, python3-pil, python3-pil.imagetk, xfce4-appmenu-plugin, xfce4-panel, xfce4-pulseaudio-plugin, xfce4-settings, xfce4-statusnotifier-plugin, xfwm4, yad
Running sudo apt update...
Ign:2 https://repo.vivaldi.com/stable/deb stable InRelease
Get:3 https://repo.vivaldi.com/stable/deb stable Release [3,840 B]
Hit:4 http://archive.raspberrypi.org/debian bullseye InRelease
Get:5 http://raspbian.raspberrypi.org/raspbian bullseye InRelease [15.0 kB]
Get:6 https://repo.vivaldi.com/stable/deb stable Release.gpg [833 B]
Hit:1 https://box86.debian.ryanfortner.dev/debian ./ InRelease
Get:7 https://repo.vivaldi.com/stable/deb stable/main armhf Packages [1,139 B]
Err:7 https://repo.vivaldi.com/stable/deb stable/main armhf Packages
  File has unexpected size (1347 != 1139). Mirror sync in progress? [IP: 151.101.125.91 443]
  Hashes of expected file:
   - Filesize:1139 [weak]
   - SHA512:584c8863f097af9cfec23c0c345899223e6bfe5196d84f54af155764b431df93d3ea6e9038478fb4eb1f5eaf3cfe4d3deaff043aca1eed8a45e4907be40e6819
   - SHA256:08d8a4458d056e42a62d67b648162bbbf50ce642f8c591ea35331ee2d03c6d30
  Release file created at: Mon, 03 Apr 2023 11:28:52 +0000
Fetched 15.8 kB in 1s (11.5 kB/s)
E: Failed to fetch https://repo.vivaldi.com/stable/deb/dists/stable/main/binary-armhf/Packages.gz  File has unexpected size (1347 != 1139). Mirror sync in progress? [IP: 151.101.125.91 443]
   Hashes of expected file:
    - Filesize:1139 [weak]
    - SHA512:584c8863f097af9cfec23c0c345899223e6bfe5196d84f54af155764b431df93d3ea6e9038478fb4eb1f5eaf3cfe4d3deaff043aca1eed8a45e4907be40e6819
    - SHA256:08d8a4458d056e42a62d67b648162bbbf50ce642f8c591ea35331ee2d03c6d30
   Release file created at: Mon, 03 Apr 2023 11:28:52 +0000
E: Some index files failed to download. They have been ignored, or old ones used instead.
apt update complete.
Failed to run sudo apt update!
APT reported these errors:
E: Failed to fetch https://repo.vivaldi.com/stable/deb/dists/stable/main/binary-armhf/Packages.gz  File has unexpected size (1347 != 1139). Mirror sync in progress? [IP: 151.101.125.91 443]
E: Some index files failed to download. They have been ignored, or old ones used instead.
Ign:2 https://repo.vivaldi.com/stable/deb stable InRelease
Get:3 https://repo.vivaldi.com/stable/deb stable Release [3,840 B]
Hit:4 http://archive.raspberrypi.org/debian bullseye InRelease
Get:5 http://raspbian.raspberrypi.org/raspbian bullseye InRelease [15.0 kB]
Get:6 https://repo.vivaldi.com/stable/deb stable Release.gpg [833 B]
Hit:1 https://box86.debian.ryanfortner.dev/debian ./ InRelease
Get:7 https://repo.vivaldi.com/stable/deb stable/main armhf Packages [1,139 B]
Err:7 https://repo.vivaldi.com/stable/deb stable/main armhf Packages
  File has unexpected size (1347 != 1139). Mirror sync in progress? [IP: 151.101.125.91 443]
  Hashes of expected file:
   - Filesize:1139 [weak]
   - SHA512:584c8863f097af9cfec23c0c345899223e6bfe5196d84f54af155764b431df93d3ea6e9038478fb4eb1f5eaf3cfe4d3deaff043aca1eed8a45e4907be40e6819
   - SHA256:08d8a4458d056e42a62d67b648162bbbf50ce642f8c591ea35331ee2d03c6d30
  Release file created at: Mon, 03 Apr 2023 11:28:52 +0000
Fetched 15.8 kB in 1s (11.5 kB/s)
E: Failed to fetch https://repo.vivaldi.com/stable/deb/dists/stable/main/binary-armhf/Packages.gz  File has unexpected size (1347 != 1139). Mirror sync in progress? [IP: 151.101.125.91 443]
   Hashes of expected file:
    - Filesize:1139 [weak]
    - SHA512:584c8863f097af9cfec23c0c345899223e6bfe5196d84f54af155764b431df93d3ea6e9038478fb4eb1f5eaf3cfe4d3deaff043aca1eed8a45e4907be40e6819
    - SHA256:08d8a4458d056e42a62d67b648162bbbf50ce642f8c591ea35331ee2d03c6d30
   Release file created at: Mon, 03 Apr 2023 11:28:52 +0000
E: Some index files failed to download. They have been ignored, or old ones used instead.

Failed to install Mac OS Theme!
◢◣Need help? Copy the ENTIRE terminal output or take a screenshot.
Please ask on Github: https://github.com/Botspot/pi-apps/issues/new/choose
Or on Discord: https://discord.gg/RXSTvaUvuu
```

**Comment by Botspot** [comment] 2023-04-12 23:49
This is unrelated to Mac OS Theme, and is instead caused by the Vivaldi APT repo being badly configured at the moment.
I just installed the Vivaldi Web Browser on my Pi and then ran `sudo apt update`, and I got the same error. :(

To fix this @Dwaitp, you can remove the ability for Vivaldi Browser to update. Just run this command to do that:
```
sudo rm /etc/apt/sources.list.d/vivaldi.list
```

**Comment by Dwaitp** [comment] 2023-04-13 01:00
Thank you for the update.

**Comment by theofficialgman** [comment] 2023-04-13 01:52
closing since vivaldi install/uninstall passed in the CI for 32bit and 64bit (no apt repo issues currently)

https://github.com/Botspot/pi-apps/actions/runs/4684597026

**Closed by theofficialgman** 2023-04-13 01:52 UTC
Labels: bug

**Comment by Botspot** [comment] 2023-04-13 02:58
> closing since vivaldi install/uninstall passed in the CI for 32bit and 64bit (no apt repo issues currently)
> 
> https://github.com/Botspot/pi-apps/actions/runs/4684597026

I am still getting that error with the vivaldi repo enabled. Using PiOS 64-bit. Any ideas why this was not picked up on the CI, or if this could be due to some apt caching on my end?

**Comment by theofficialgman** [comment] 2023-04-13 03:02
> I am still getting that error with the vivaldi repo enabled. Using PiOS 64-bit. Any ideas why this was not picked up on the CI, or if this could be due to some apt caching on my end?

must be some sort of apt caching somewhere in the world... 
the CI completed without error. there were no apt update or install errors
https://github.com/Botspot/pi-apps/actions/runs/4684597026/jobs/8300908590#step:3:1034
