### ISSUE TITLE
(not pi-apps) Need help with installing dkms package

### ISSUE THREAD

**Issue by Dizzy-Pi** [Botspot/pi-apps#2626] opened 2024-07-26 09:32 UTC
### Confirmations

- [X] I searched for similar bug reports in https://github.com/Botspot/pi-apps/issues and found none were relevant.
- [X] I tried updating Pi-Apps and the issue is still not fixed. [How to update Pi-Apps?](https://pi-apps.io/wiki/getting-started/updating-pi-apps/)
- [X] IMPORTANT: I promise to respond to comments on this issue and write a good bug report https://www.softwaretestinghelp.com/how-to-write-good-bug-report/

### What happened?

trying to install wine which is failing due to a package on my system is causing an error

### Description

im trying to get more info about how to find the conflicting package that is preventing the installation

### What are your system specs (run the following command in your terminal)?

```bash
OS: Debian GNU/Linux 12 (bookworm)
OS architecture: 64-bit
Last updated Pi-Apps on: 07/26/2024
Latest Pi-Apps version: 07/26/2024
Kernel: aarch64 6.6.31+rpt-rpi-v8
Device model: Raspberry Pi 4 Model B Rev 1.5
SOC identifier: bcm2711
Cpu name: Cortex-A72
Ram size: 7.81 GB
Raspberry Pi OS image version: 2024-07-04
Language: en_US.UTF-8
```

### (Recommended) Error log? Terminal output? Debug messages?

```bash
Installing Wine (x64)...

Will install these packages: cabextract p7zip-full 
Creating an empty apt-package to install the necessary apt packages...
It will be named: pi-apps-112b87c1
Depends: cabextract, p7zip-full
Running sudo apt update...
Hit:1 http://deb.debian.org/debian bookworm InRelease
Hit:2 http://deb.debian.org/debian-security bookworm-security InRelease
Hit:3 http://deb.debian.org/debian bookworm-updates InRelease
Hit:4 https://Pi-Apps-Coders.github.io/box64-debs/debian ./ InRelease
Hit:5 http://archive.raspberrypi.com/debian bookworm InRelease
All packages are up to date.
apt update complete.
Installing the pi-apps-112b87c1 package...
The following additional packages will be installed:
  cabextract libmspack0
The following NEW packages will be installed:
  cabextract libmspack0 pi-apps-112b87c1
0 upgraded, 3 newly installed, 0 to remove and 0 not upgraded.
1 not fully installed or removed.
After this operation, 240 kB of additional disk space will be used.
Get:1 /tmp/pi-apps-112b87c1.deb pi-apps-112b87c1 all 1.0 [756 B]
(Reading database ... 192593 files and directories currently installed.)
Unpacking libmspack0:arm64 (0.11-1) ...
Unpacking cabextract (1.9-3) ...
Unpacking pi-apps-112b87c1 (1.0) ...
Removing old xtrx-0.0.1+git20190320.5ae3a3e-3.2 DKMS files...
/usr/sbin/dkms: line 2497: echo: write error: Broken pipe
Deleting module xtrx-0.0.1+git20190320.5ae3a3e-3.2 completely from the DKMS tree.
Loading new xtrx-0.0.1+git20190320.5ae3a3e-3.2 DKMS files...
/usr/sbin/dkms: line 2497: echo: write error: Broken pipe
Building for 6.6.31+rpt-rpi-v8
/usr/sbin/dkms: line 2497: echo: write error: Broken pipe
Building initial module for 6.6.31+rpt-rpi-v8
/usr/sbin/dkms: line 2497: echo: write error: Broken pipe
Error! Bad return status for module build on kernel: 6.6.31+rpt-rpi-v8 (aarch64)
Consult /var/lib/dkms/xtrx/0.0.1+git20190320.5ae3a3e-3.2/build/make.log for more information.
dpkg: error processing package xtrx-dkms (--configure):
 installed xtrx-dkms package post-installation script subprocess returned error exit status 10
Errors were encountered while processing:
 xtrx-dkms
E: Sub-process /usr/bin/dpkg returned an error code (1)
                                                       Apt finished.
Failed to install the packages!
APT reported these errors:
E: Sub-process /usr/bin/dpkg returned an error code (1)
The following additional packages will be installed:
  cabextract libmspack0
The following NEW packages will be installed:
  cabextract libmspack0 pi-apps-112b87c1
0 upgraded, 3 newly installed, 0 to remove and 0 not upgraded.
1 not fully installed or removed.
After this operation, 240 kB of additional disk space will be used.
Get:1 /tmp/pi-apps-112b87c1.deb pi-apps-112b87c1 all 1.0 [756 B]
(Reading database ... 192593 files and directories currently installed.)
Unpacking libmspack0:arm64 (0.11-1) ...
Unpacking cabextract (1.9-3) ...
Unpacking pi-apps-112b87c1 (1.0) ...
Removing old xtrx-0.0.1+git20190320.5ae3a3e-3.2 DKMS files...
/usr/sbin/dkms: line 2497: echo: write error: Broken pipe
Deleting module xtrx-0.0.1+git20190320.5ae3a3e-3.2 completely from the DKMS tree.
Loading new xtrx-0.0.1+git20190320.5ae3a3e-3.2 DKMS files...
/usr/sbin/dkms: line 2497: echo: write error: Broken pipe
Building for 6.6.31+rpt-rpi-v8
/usr/sbin/dkms: line 2497: echo: write error: Broken pipe
Building initial module for 6.6.31+rpt-rpi-v8
/usr/sbin/dkms: line 2497: echo: write error: Broken pipe
Error! Bad return status for module build on kernel: 6.6.31+rpt-rpi-v8 (aarch64)
Consult /var/lib/dkms/xtrx/0.0.1+git20190320.5ae3a3e-3.2/build/make.log for more information.
dpkg: error processing package xtrx-dkms (--configure):
 installed xtrx-dkms package post-installation script subprocess returned error exit status 10
Errors were encountered while processing:
 xtrx-dkms
E: Sub-process /usr/bin/dpkg returned an error code (1)

Failed to install Wine (x64)!
◢◣Need help? Copy the ENTIRE terminal output or take a screenshot.
Please ask on Github: https://github.com/Botspot/pi-apps/issues/new/choose
Or on Discord: https://discord.gg/RXSTvaUvuu
Opening in existing browser session.
```

**Comment by Botspot** [comment] 2024-07-26 14:52
Thanks for reaching out. While The conflicting package is unrelated to pi-apps, we here can try to help you, or at least point you in the right direction. :)

After a quick google search somebody else had this issue. See: https://askubuntu.com/questions/1469881/getting-an-error-every-time-i-install-something-with-apt
Can you see what happens when you run `sudo apt remove xtrx-dkms`?
Before you confirm yes, does that command ask if you really want to uninstall a bunch of stuff, or only that package?

**Comment by theofficialgman** [comment] 2024-07-26 20:14
```
/usr/sbin/dkms: line 2497: echo: write error: Broken pipe
Deleting module xtrx-0.0.1+git20190320.5ae3a3e-3.2 completely from the DKMS tree.
```
this output indicates to me that the script `/usr/sbin/dkms` itself is bugged
this line corresponds to
```
# The <(cmd) idiom does not work if /proc is not mounted
if [ ! -e <(echo) ]; then
    warn $"dkms will not function properly if /proc is not mounted."
fi
```
in the dkms script

this issue is reported by others on debian forums, stackexchange, launchpad bugs, and many other places
https://forums.debian.net/viewtopic.php?t=157714
https://serverfault.com/questions/1130906/debian-update-fails-on-buildine-new-kernel
https://www.antixforum.com/forums/topic/problem-upgrading-after-installing-antix-23/
https://bugs.launchpad.net/ubuntu/+source/dkms/+bug/1125595
https://forum.proxmox.com/threads/upgrade-from-7-to-8-failed-due-to-custom-kernel.142277/
https://groups.google.com/g/linux.debian.kernel/c/I1WFZQo6XtU
https://bugs.archlinux.org/task/49816


I am going to close this issue as not our issue. Please uninstall the problematic package (as @Botspot instructed above) and raise an issue or comment on an existing one with Debian

**Closed by theofficialgman** 2024-07-26 20:14 UTC
Labels: User Error

**Comment by Dizzy-Pi** [comment] 2024-07-27 00:04
sudo apt remove xtrx-dkms worked! Thank you for your assistance on a non Pi-Apps issue to get me up and running.

**Comment by Botspot** [comment] 2024-07-27 13:52
> sudo apt remove xtrx-dkms worked! Thank you for your assistance on a non Pi-Apps issue to get me up and running.

Awesome! Good to see it was that easy. Do you happen to remember why you had that installed to begin with?

**Comment by theofficialgman** [comment] 2024-07-31 19:34
More information on why this error is showing up now (caused by piOS kernel upgrade beyond 6.1)
https://forums.raspberrypi.com/viewtopic.php?p=2241235#p2241234
