### ISSUE TITLE
Help needed : Plank (Dock) on Pi Apps

### ISSUE THREAD

**Issue by open-sorcerer64** [Botspot/pi-apps#688] opened 2021-05-25 14:27 UTC
### Hi Botspot,
I want to add Plank which is a dock(like on Mac OS) but I am just a kid so I can't figure out how to make the install script
**Any Help will be greatly appreciated**
I am also a Youtuber [https://www.youtube.com/channel/UCCsEfbaCHPjM0Dhx69TrJPw](url) I was making a tutorial on it, but i thought if my viewers did it through **Pi Apps** it will be easy for them.
 
It is a dock like in MacOS, useful for people who are both mac and raspberry pi users. Or people who want to make there OS look like mac or just have a dock(like me)

It can be easily installed with `sudo apt install plank compton`. But the script to autostart it is complicated

Tejas Singh YT
[https://www.youtube.com/channel/UCCsEfbaCHPjM0Dhx69TrJPw](url)

**Comment by TerraGitHuB** [comment] 2021-05-25 14:42
If you can make the script on Github that will auotstart plank, I can try and create a Pi-apps .zip for you...

**Comment by chunky-milk** [comment] 2021-05-25 16:16
Maybe we can create scripts to automatically compile the latest version of plank, instead of using the outdated version from APT. Here are compile instructions if you can get them to work... https://github.com/ricotz/plank/blob/master/HACKING

**Comment by Itai-Nelken** [comment] 2021-05-25 16:23
I tried to build it once but I never got it to build, dependency issues...

**Comment by mobilegmYT** [comment] 2021-05-25 16:28
What if we just yoink it from TwisterOS?

**Comment by chunky-milk** [comment] 2021-05-25 16:29
> What if we just yoink it from TwisterOS?
> 
> 

Is the version on twister os the latest version?

**Comment by mobilegmYT** [comment] 2021-05-25 16:32
> > What if we just yoink it from TwisterOS?
> 
> Is the version on twister os the latest version?

Nevermind, twister uses apt version too.

**Comment by Botspot** [comment] 2021-05-25 16:37
@Tejas-Singh-py, have you tried the Pi-Apps MacOS theme? That includes a plank-style panel, a compositor, and many other graphical changes. Maybe you could instruct your viewers to start with that and then customize it?.

**Comment by leha-code** [comment] 2021-05-25 17:11
Plank is installable with apt

**Comment by leha-code** [comment] 2021-05-25 17:16
There isn't much added in the latest version. My Ubuntu laptop is running the latest and I see no difference

**Comment by TerraGitHuB** [comment] 2021-05-25 17:37
I think most of the issue is just getting it to start by default.

**Comment by mobilegmYT** [comment] 2021-05-25 17:38
> I think most of the issue is just getting it to start by default.

Use a startup script to run it? rc.local?

**Comment by TerraGitHuB** [comment] 2021-05-25 17:46
You know, despite all I've tried, I've never got anything to do it.

Anyway, this is off topic. 

Seemingly, all one needs to do is to install with apt, then get it to run on start-up (rc.local or crontab or whatever is best).

**Comment by mobilegmYT** [comment] 2021-05-25 17:47
> You know, despite all I've tried, I've never got anything to do it.
> 
> Anyway, this is off topic.
> 
> Seemingly, all one needs to do is to install with apt, then get it to run on start-up (rc.local or crontab or whatever is best).

Humm... are you using any different window/desktop manager like xfce instead of pixel?

**Comment by Itai-Nelken** [comment] 2021-05-25 18:36
> There isn't much added in the latest version. My Ubuntu laptop is running the latest and I see no difference

There is a fix to a bug that causes the animations to slow down until they don't run at all (I don't know when it was fixed, but I know it was fixed in a version newer than the apt one).

**Comment by TerraGitHuB** [comment] 2021-05-25 18:42
@mobilegmYT no, not at the time of trying.

I just gave up. I didn't really have a use for it anyway. I use GNOME For Pi ATM (my own project, waiting to be approved by @Botspot for Pi-apps)

**Comment by chunky-milk** [comment] 2021-05-25 18:44
> You know, despite all I've tried, I've never got anything to do it.
> 
> 
> 
> Anyway, this is off topic. 
> 
> 
> 
> Seemingly, all one needs to do is to install with apt, then get it to run on start-up (rc.local or crontab or whatever is best).

Just for future reference, what you can do to have plank on autostart is 

mkdir -p ~/.config/auto start
cp /usr/share/applications/plank.desktop ~/.config/autostart/

Then reboot.

**Comment by Tejas-Singh-py** [comment] 2021-05-26 05:57
> > You know, despite all I've tried, I've never got anything to do it.
> > Anyway, this is off topic.
> > Seemingly, all one needs to do is to install with apt, then get it to run on start-up (rc.local or crontab or whatever is best).
> 
> Just for future reference, what you can do to have plank on autostart is
> 
> mkdir -p ~/.config/autostart
> cp /usr/share/applications/plank.desktop ~/.config/autostart/
> 
> Then reboot.

Hi Everyone,
Thanks for he response. I have made the script for plank. It downloads Plank and Compton(Required) and auto-start both of them. Anyone of you can make the install and uninstall script. 
### Install Script
```bash
sudo apt install plank
sudo apt install compton
cd .config
mkdir autostart
cd autostart
sudo cp /usr/share/applications/plank.desktop ~/.config/autostart
sudo chmod +x plank.desktop

sudo chown pi:pi plank.desktop
sudo cp /usr/share/applications/compton.desktop ~/.config/autostart
sudo chmod +x compton.desktop
sudo chown pi:pi compton.desktop
```

### Uninstall Script
```bash
sudo apt remove plank
sudo apt remove compton
```

**Request: Please mention me and my channel in the credits section**


> Maybe we can create scripts to automatically compile the latest version of plank, instead of using the outdated version from APT. Here are compile instructions if you can get them to work... https://github.com/ricotz/plank/blob/master/HACKING

Linux has dependency issues lol

**Comment by TerraGitHuB** [comment] 2021-05-26 07:44
Great, thanks @Tejas-Singh-py

**Comment by TerraGitHuB** [comment] 2021-05-26 07:51
Here @Botspot, yet another app waiting for approval:
[plank.zip](https://github.com/Botspot/pi-apps/files/6544789/plank.zip)

**Comment by Tejas-Singh-py** [comment] 2021-05-26 08:43
> Here @Botspot, yet another app waiting for approval:
> [plank.zip](https://github.com/Botspot/pi-apps/files/6544789/plank.zip)

@TerraGitHuB  You mentioned me

**Comment by TerraGitHuB** [comment] 2021-05-26 08:46
Yup, your github name plus youtube channel are referenced in the credits.

**Comment by Tejas-Singh-YT** [comment] 2021-05-26 08:55
> Yup, your github name plus youtube channel are referenced in the credits.

Thanks @TerraGitHuB Can't wait to get it approved.

**Comment by Tejas-Singh-py** [comment] 2021-05-26 11:38
> Here @Botspot, yet another app waiting for approval:
> [plank.zip](https://github.com/Botspot/pi-apps/files/6544789/plank.zip)

Hey, Terra
is this file encrypted

**Comment by TerraGitHuB** [comment] 2021-05-26 12:14
No, shouldn't be.

**Comment by TerraGitHuB** [comment] 2021-05-26 12:16
Although, there's nothing in the ZIP!

**Comment by TerraGitHuB** [comment] 2021-05-26 12:17
[plank.zip](https://github.com/Botspot/pi-apps/files/6546590/plank.zip)


Try that one.

**Comment by Itai-Nelken** [comment] 2021-05-26 14:49
@TerraGitHuB the zip permissions are broken.
comments on the script:
use the 'create app' button in pi-apps settings to create the app, it gives you the template scripts to get started that include all the pi-apps stuff. see my comment in the gnomeforpi issue, they mostly apply for this scripts as well.

**Comment by Tejas-Singh-py** [comment] 2021-05-27 06:53
> @TerraGitHuB the zip permissions are broken.
> comments on the script:
> use the 'create app' button in pi-apps settings to create the app, it gives you the template scripts to get started that include all the pi-apps stuff. see my comment in the gnomeforpi issue, they mostly apply for this scripts as well.

I used the create app thing but as I told, I don't know how to make a shell script and I can't understand the template script. Therefore, I came for help. You Can help me with the script the commands are given above

**Comment by Tejas-Singh-py** [comment] 2021-05-27 06:54
### Install Script
```shell
sudo apt install plank
sudo apt install compton
cd .config
mkdir autostart
cd autostart
sudo cp /usr/share/applications/plank.desktop ~/.config/autostart
sudo chmod +x plank.desktop
sudo chown pi:pi plank.desktop
sudo cp /usr/share/applications/compton.desktop ~/.config/autostart
sudo chmod +x compton.desktop
sudo chown pi:pi compton.desktop
```

### Uninstall Script
```shell
sudo apt remove plank
sudo apt remove compton
```

**Request: Please mention me and my channel in the credits section**

**Closed** 2021-08-02 05:29 UTC
Labels: App Request
