### ISSUE TITLE
failed to install box86

### ISSUE THREAD

**Issue by stormagedon92** [Botspot/pi-apps#2259] opened 2023-02-04 02:34 UTC
### Confirmations

- [X] I searched for similar bug reports in https://github.com/Botspot/pi-apps/issues and found none were relevant.
- [X] I tried updating Pi Apps and the issue is still not fixed. [How to update Pi Apps?](https://github.com/Botspot/pi-apps#to-update-pi-apps)
- [X] IMPORTANT: I promise to respond to comments on this issue and write a good bug report https://www.softwaretestinghelp.com/how-to-write-good-bug-report/

### What happened?

box86 failed to install

### Description

installed several other applications (multimc, sublime, cura, libracad) but box86 failed

### What are your system specs (run the following command in your terminal)?

```bash
OS: Pop!_OS 22.04 LTS
OS architecture: 64-bit
Last updated Pi-Apps on: 02/03/2023
Latest Pi-Apps version: 02/03/2023
Kernel: aarch64 5.15.0-1023-raspi
Device model: Raspberry Pi 4 Model B Rev 1.4 
Cpu name: Cortex-A72
Ram size: 7.75 GB
Language: en_US.UTF-8
```

### (Recommended) Error log? Terminal output? Debug messages?

```bash
BEGINNING OF LOG FILE:
-----------------------

Will install these packages: libraspberrypi0:armhf libssh-gcrypt-4:armhf libgssapi-krb5-2:armhf libkrb5-3:armhf libssl1.1:armhf | libssl3:armhf libcups2:armhf libsdl1.2debian:armhf libopusfile0:armhf libc6:armhf libx11-6:armhf libgdk-pixbuf2.0-0:armhf libgtk2.0-0:armhf libstdc++6:armhf libsdl2-2.0-0:armhf mesa-va-drivers:armhf libsdl1.2-dev:armhf libsdl-mixer1.2:armhf libpng16-16:armhf libcal3d12v5:armhf libsdl2-net-2.0-0:armhf libopenal1:armhf libsdl2-image-2.0-0:armhf libvorbis-dev:armhf libcurl4:armhf osspd:armhf pulseaudio libjpeg62:armhf libudev1:armhf libgl1-mesa-dev:armhf libsnappy1v5:armhf libx11-dev:armhf libsmpeg0:armhf libboost-filesystem1.74.0:armhf libboost-program-options1.74.0:armhf libavcodec58:armhf libavformat58:armhf libswscale5:armhf libmyguiengine3debian1v5:armhf libboost-iostreams1.74.0:armhf libsdl2-mixer-2.0-0:armhf 
Waiting until APT locks are released... Done
Creating an empty apt-package to install the necessary apt packages...
It will be named: pi-apps-5f3374a7
Depends: libavcodec58:armhf, libavformat58:armhf, libboost-filesystem1.74.0:armhf, libboost-iostreams1.74.0:armhf, libboost-program-options1.74.0:armhf, libc6:armhf, libcal3d12v5:armhf, libcups2:armhf, libcurl4:armhf, libgdk-pixbuf2.0-0:armhf, libgl1-mesa-dev:armhf, libgssapi-krb5-2:armhf, libgtk2.0-0:armhf, libjpeg62:armhf, libkrb5-3:armhf, libmyguiengine3debian1v5:armhf, libopenal1:armhf, libopusfile0:armhf, libpng16-16:armhf, libraspberrypi0:armhf, libsdl1.2debian:armhf, libsdl1.2-dev:armhf, libsdl2-2.0-0:armhf, libsdl2-image-2.0-0:armhf, libsdl2-mixer-2.0-0:armhf, libsdl2-net-2.0-0:armhf, libsdl-mixer1.2:armhf, libsmpeg0:armhf, libsnappy1v5:armhf, libssh-gcrypt-4:armhf, libssl1.1:armhf | libssl3:armhf, libstdc++6:armhf, libswscale5:armhf, libudev1:armhf, libvorbis-dev:armhf, libx11-6:armhf, libx11-dev:armhf, mesa-va-drivers:armhf, osspd:armhf, pulseaudio
Running sudo apt update...
Hit:1 http://apt.pop-os.org/proprietary jammy InRelease
Hit:2 https://download.sublimetext.com apt/stable/ InRelease
Hit:3 http://ports.ubuntu.com/ubuntu-ports jammy InRelease
Hit:4 http://apt.pop-os.org/release jammy InRelease
Hit:5 http://ports.ubuntu.com/ubuntu-ports jammy-security InRelease
Hit:6 http://ports.ubuntu.com/ubuntu-ports jammy-updates InRelease
Hit:7 http://ports.ubuntu.com/ubuntu-ports jammy-backports InRelease
Get:8 http://ports.ubuntu.com/ubuntu-ports jammy/main armhf Packages [1,323 kB]
Get:9 http://ports.ubuntu.com/ubuntu-ports jammy/restricted armhf Packages [10.9 kB]
Get:10 http://ports.ubuntu.com/ubuntu-ports jammy/universe armhf Packages [13.5 MB]
Get:11 http://ports.ubuntu.com/ubuntu-ports jammy/multiverse armhf Packages [164 kB]
Get:12 http://ports.ubuntu.com/ubuntu-ports jammy-security/main armhf Packages [353 kB]
Get:13 http://ports.ubuntu.com/ubuntu-ports jammy-security/restricted armhf Packages [7,908 B]
Get:14 http://ports.ubuntu.com/ubuntu-ports jammy-security/universe armhf Packages [403 kB]
Get:15 http://ports.ubuntu.com/ubuntu-ports jammy-security/multiverse armhf Packages [688 B]
Get:16 http://ports.ubuntu.com/ubuntu-ports jammy-updates/main armhf Packages [577 kB]
Get:17 http://ports.ubuntu.com/ubuntu-ports jammy-updates/restricted armhf Packages [8,256 B]
Get:18 http://ports.ubuntu.com/ubuntu-ports jammy-updates/universe armhf Packages [558 kB]
Get:19 http://ports.ubuntu.com/ubuntu-ports jammy-updates/multiverse armhf Packages [1,376 B]
Get:20 http://ports.ubuntu.com/ubuntu-ports jammy-backports/main armhf Packages [40.5 kB]
Get:21 http://ports.ubuntu.com/ubuntu-ports jammy-backports/universe armhf Packages [19.5 kB]
Fetched 17.0 MB in 13s (1,332 kB/s)
All packages are up to date.
apt update complete.
Installing the pi-apps-5f3374a7 package...
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:
The following packages have unmet dependencies:
 libdbus-1-3:armhf : Depends: libsystemd0:armhf but it is not going to be installed
 libegl1:armhf : Depends: libegl-mesa0:armhf but it is not going to be installed
 libfluidsynth3:armhf : Depends: libasound2:armhf (>= 1.0.16)
                        Depends: libsdl2-2.0-0:armhf (>= 2.0.12) but it is not installable
 libglx0:armhf : Depends: libglx-mesa0:armhf but it is not going to be installed
 libmikmod3:armhf : Depends: libsdl2-2.0-0:armhf (>= 2.0.12+dfsg1) but it is not installable
 libpulse0:armhf : Depends: libsystemd0:armhf but it is not going to be installed
 libsdl-mixer1.2:armhf : Depends: libsdl1.2debian:armhf (>= 1.2.11)
 libsdl2-image-2.0-0:armhf : Depends: libsdl2-2.0-0:armhf (>= 2.0.12) but it is not installable
 libsdl2-mixer-2.0-0:armhf : Depends: libsdl2-2.0-0:armhf (>= 2.0.12) but it is not installable
 libsdl2-net-2.0-0:armhf : Depends: libsdl2-2.0-0:armhf (>= 2.0.12) but it is not installable
 libsmpeg0:armhf : Depends: libsdl1.2debian:armhf (>= 1.2.11)
 libsndio7.0:armhf : Depends: libasound2:armhf (>= 1.0.17)
 libswscale5:armhf : Depends: libavutil56:armhf (= 7:4.4.2-0ubuntu0.22.04.1) but it is not installable
 osspd:armhf : Depends: osspd-pulseaudio:armhf but it is not going to be installed or
                        osspd-backend:armhf
 pi-apps-5f3374a7 : Depends: libavcodec58:armhf
                    Depends: libavformat58:armhf
                    Depends: libsdl1.2debian:armhf
                    Depends: libsdl1.2-dev:armhf
                    Depends: libsdl2-2.0-0:armhf
                    Depends: libudev1:armhf
                    Depends: mesa-va-drivers:armhf
                    Depends: pulseaudio
E: Unable to correct problems, you have held broken packages.
Apt finished.
Failed to install the packages!
APT reported these errors:
E: Unable to correct problems, you have held broken packages.
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:
The following packages have unmet dependencies:
 libdbus-1-3:armhf : Depends: libsystemd0:armhf but it is not going to be installed
 libegl1:armhf : Depends: libegl-mesa0:armhf but it is not going to be installed
 libfluidsynth3:armhf : Depends: libasound2:armhf (>= 1.0.16)
                        Depends: libsdl2-2.0-0:armhf (>= 2.0.12) but it is not installable
 libglx0:armhf : Depends: libglx-mesa0:armhf but it is not going to be installed
 libmikmod3:armhf : Depends: libsdl2-2.0-0:armhf (>= 2.0.12+dfsg1) but it is not installable
 libpulse0:armhf : Depends: libsystemd0:armhf but it is not going to be installed
 libsdl-mixer1.2:armhf : Depends: libsdl1.2debian:armhf (>= 1.2.11)
 libsdl2-image-2.0-0:armhf : Depends: libsdl2-2.0-0:armhf (>= 2.0.12) but it is not installable
 libsdl2-mixer-2.0-0:armhf : Depends: libsdl2-2.0-0:armhf (>= 2.0.12) but it is not installable
 libsdl2-net-2.0-0:armhf : Depends: libsdl2-2.0-0:armhf (>= 2.0.12) but it is not installable
 libsmpeg0:armhf : Depends: libsdl1.2debian:armhf (>= 1.2.11)
 libsndio7.0:armhf : Depends: libasound2:armhf (>= 1.0.17)
 libswscale5:armhf : Depends: libavutil56:armhf (= 7:4.4.2-0ubuntu0.22.04.1) but it is not installable
 osspd:armhf : Depends: osspd-pulseaudio:armhf but it is not going to be installed or
                        osspd-backend:armhf
 pi-apps-5f3374a7 : Depends: libavcodec58:armhf
                    Depends: libavformat58:armhf
                    Depends: libsdl1.2debian:armhf
                    Depends: libsdl1.2-dev:armhf
                    Depends: libsdl2-2.0-0:armhf
                    Depends: libudev1:armhf
                    Depends: mesa-va-drivers:armhf
                    Depends: pulseaudio
E: Unable to correct problems, you have held broken packages.

Failed to install Box86!
◢◣Need help? Copy the ENTIRE terminal output or take a screenshot.
Please ask on Github: https://github.com/Botspot/pi-apps/issues/new/choose
Or on Discord: https://discord.gg/RXSTvaUvuu
Additional log diagnosis for developers below:

Package: libdbus-1-3
Architecture: armhf
Version: 1.12.20-2ubuntu4.1
Multi-Arch: same
Priority: important
Section: libs
Source: dbus
Origin: Ubuntu
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: Utopia Maintenance Team <pkg-utopia-maintainers@lists.alioth.debian.org>
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Installed-Size: 340
Depends: libc6 (>= 2.34), libsystemd0
Recommends: dbus
Breaks: dbus (<< 1.9.16-1~)
Filename: pool/main/d/dbus/libdbus-1-3_1.12.20-2ubuntu4.1_armhf.deb
Size: 169540
MD5sum: 8bcbbe8f53ff2e247d174bb250dbaf89
SHA1: baf867fff0b8f336ede5ecdba7e63f5230771435
SHA256: d4c7f04bc8089c0e4d8ff813646a42a93fee44fe66e1ce93fa563ccaa6ae11b9
SHA512: e67d86baf178219126f403351822c08e27b7de8613e37b95287ed124f2cc60b7a65b38d9a012a5eb4f0154571dd38867800a20026c846c304412506050cf7a63
Homepage: https://dbus.freedesktop.org/
Description-en: simple interprocess messaging system (library)
 D-Bus is a message bus, used for sending messages between applications.
 Conceptually, it fits somewhere in between raw sockets and CORBA in
 terms of complexity.
 .
 D-Bus supports broadcast messages, asynchronous messages (thus
 decreasing latency), authentication, and more. It is designed to be
 low-overhead; messages are sent using a binary protocol, not using
 XML. D-Bus also supports a method call mapping for its messages, but
 it is not required; this makes using the system quite simple.
 .
 It comes with several bindings, including GLib, Python, Qt and Java.
 .
 The daemon can be found in the dbus package.
Description-md5: 394b84dd0007d22bc4bb591ca6b5fa31
Task: minimal, server-minimal
```

**Comment by theofficialgman** [comment] 2023-02-09 01:41
@Botspot @stormagedon92 I can confirm the issue with PopOS 22.04 https://github.com/Botspot/pi-apps/actions/runs/4129921980/jobs/7136069036#step:3:861

this issue is different in Ubuntu 22.04 https://github.com/Botspot/pi-apps/actions/runs/4129921980/jobs/7136068730 . it succeeds but only does so because it basically removes the entire 64bit OS.

@stormagedon92 please file this as a bug at PopOS and/or Ubuntu as this is not an issue with pi-apps (this works fine on focal, buster, and bullseye). they have done something to break multiarch (probably some custom ffmpeg package on arm64 only that conflicts with the armhf one from ubuntu)

I will be disabling box86 on 22.04 as a result of this

**Comment by theofficialgman** [comment] 2023-03-11 00:45
closing as can't fix. refer to the above comment

**Closed by theofficialgman** 2023-03-11 00:45 UTC
Labels: Upstream Bug
