### ISSUE TITLE
Zoom doesn't open

### ISSUE THREAD

**Issue by Rak1ta** [Botspot/pi-apps#2292] opened 2023-04-02 06:45 UTC
### Confirmations

- [X] I searched for similar bug reports in https://github.com/Botspot/pi-apps/issues and found none were relevant.
- [X] I tried updating Pi Apps and the issue is still not fixed. [How to update Pi Apps?](https://github.com/Botspot/pi-apps#to-update-pi-apps)
- [X] IMPORTANT: I promise to respond to comments on this issue and write a good bug report https://www.softwaretestinghelp.com/how-to-write-good-bug-report/

### What happened?

Error in Box64

### Description

When launched, it produces such a log and Zoom does not start.
[log.txt](https://github.com/Botspot/pi-apps/files/11131305/log.txt)

### What are your system specs (run the following command in your terminal)?

```bash
OS: Debian GNU/Linux 11 (bullseye)
OS architecture: 64-bit
Last updated Pi-Apps on: 04/01/2023
Latest Pi-Apps version: 04/02/2023
Kernel: aarch64 6.1.19-v8+
Device model: Raspberry Pi 4 Model B Rev 1.2 
Cpu name: Cortex-A72
Ram size: 3.61 GB
Raspberry Pi OS image version: 2023-02-21
Language: en_US.UTF-8
```

### (Recommended) Error log? Terminal output? Debug messages?

```
Error loading one of needed lib
Error: loading needed libs in elf /home/pi/zoom/zoom
Zoom exited. Close this terminal to exit
```

**Comment by Botspot** [comment] 2023-04-02 11:06
Can reproduce on PiOS 64-bit.
Not sure what the problem is, as I made sure these apt packages were installed: (they already were)
```
libqt5quickwidgets5 libqt5quick5 libqt5widgets5 libqt5x11extras5 libqt5gui5 libqt5qml5 libqt5network5 libqt5dbus5 libqt5core5a
```
I tried downgrading Zoom to 5.14.0.1720: no change.
I also tried downgrading box64 to `0.2.3+20230323.9`: no change.

**Comment by Botspot** [comment] 2023-04-02 11:07
Can reproduce on PiOS 64-bit.
Not sure what the problem is, as I made sure these apt packages were installed: (they already were)
```
libqt5quickwidgets5 libqt5quick5 libqt5widgets5 libqt5x11extras5 libqt5gui5 libqt5qml5 libqt5network5 libqt5dbus5 libqt5core5a
```
I tried downgrading Zoom to 5.14.0.1720: no change.
I also tried downgrading box64 to `0.2.3+20230323.9`: no change.

**Comment by Rak1ta** [comment] 2023-04-02 11:17
@Botspot This I have now installed on a clean Bullseye (aarch64)
[install-success-Zoom.log](https://github.com/Botspot/pi-apps/files/11132012/install-success-Zoom.log)
[install-success-Box64.log](https://github.com/Botspot/pi-apps/files/11132010/install-success-Box64.log)
[log-terminal.txt](https://github.com/Botspot/pi-apps/files/11132011/log-terminal.txt)

**Comment by Jai-JAP** [comment] 2023-04-02 16:23
> Can reproduce on PiOS 64-bit.
> Not sure what the problem is, as I made sure these apt packages were installed: (they already were)
> ```
> libqt5quickwidgets5 libqt5quick5 libqt5widgets5 libqt5x11extras5 libqt5gui5 libqt5qml5 libqt5network5 libqt5dbus5 libqt5core5a
> ```
> I tried downgrading Zoom to 5.14.0.1720: no change.
> I also tried downgrading box64 to `0.2.3+20230323.9`: no change.

All these are c++ libraries and are not wrapped in box86/64 so you need native x64 versions of them.

**Comment by theofficialgman** [comment] 2023-04-02 22:58
zoom archive has QT binaries/libraries in a subfolder called `Qt`. on a normal x86_64 system, the qt.conf file places next to the zoom binary would be read which contains the path to tell the zoom binary to look in this folder to look for qt5 binaries. this is not happening with box64

qt.conf
```
[Paths]
Prefix=./Qt
Binaries=bin
Libraries=lib
Plugins=plugins
Qml2Imports=qml
```

**Comment by Botspot** [comment] 2023-04-03 02:48
> zoom archive has QT binaries/libraries in a subfolder called `Qt`. on a normal x86_64 system, the `qt.conf` file placed next to the zoom binary would be read which contains the path to tell the zoom binary to look in this folder to look for qt5 binaries. this is not happening with box64
> 
> qt.conf
> 
> ```
> [Paths]
> Prefix=./Qt
> Binaries=bin
> Libraries=lib
> Plugins=plugins
> Qml2Imports=qml
> ```

Well, surely Zoom must have worked under box64 at some point, and when we added arm64 support for Zoom. I'm not sure what would have *changed* to break functionality.

**Comment by Jai-JAP** [comment] 2023-04-03 08:52
Can you try moving qt libs from Qt folder to zoom folder

Run
`mv ~/zoom/Qt/* ~/zoom`
and try again

**Comment by Rak1ta** [comment] 2023-04-03 13:48
> BOX64_LD_LIBRARY_PATH=${BOX64_LD_LIBRARY_PATH}:${HOME}/zoom/Qt box64 zoom

[log.txt](https://github.com/Botspot/pi-apps/files/11138922/log.txt)

**Comment by Jai-JAP** [comment] 2023-04-03 17:14
Try editing `~/zoom/runzoom.sh` and replace last line
`BOX64_LD_LIBRARY_PATH=. . . . . . .zoom`
with
`BOX64_LD_LIBRARY_PATH=${BOX64_LD_LIBRARY_PATH}:${HOME}/zoom/Qt/lib:${HOME}/zoom/cef box64 zoom`

Also try this with a fresh install and it should work.

**Comment by Botspot** [comment] 2023-04-03 17:20
> Try editing `~/zoom/runzoom.sh` and replace last line `BOX64_LD_LIBRARY_PATH=. . . . . . .zoom` with `BOX64_LD_LIBRARY_PATH=${BOX64_LD_LIBRARY_PATH}:${HOME}/zoom/Qt/lib:${HOME}/zoom/cef box64 zoom`
> 
> Also try this with a fresh install and it should work.

That worked for me. I am still at a loss as to what would have caused zoom to break and to suddenly need this fix. It used to work without this change.

**Comment by Botspot** [comment] 2023-04-03 17:23
As a sidenote, has anyone else noticed that the Zoom icon seems to be rendered on the taskbar with visual artifacts and missing pixels?
![Screenshot from 2023-04-03 12-22-47](https://user-images.githubusercontent.com/54716352/229582436-adf123e7-4ed1-43ce-afdb-c853e75aeb5c.png)

**Comment by Rak1ta** [comment] 2023-04-03 17:33
@Botspot armhf 
![Безымянный](https://user-images.githubusercontent.com/88277343/229584427-36f29747-efda-4f2a-b9bd-bdb227570195.png)

**Comment by Botspot** [comment] 2023-04-03 17:37
> @Botspot armhf ![Безымянный](https://user-images.githubusercontent.com/88277343/229584427-36f29747-efda-4f2a-b9bd-bdb227570195.png)

Good data point. The Zoom version for armhf is much older as Zoom seems to have abandoned 32-bit x86 linux builds.

**Comment by Jai-JAP** [comment] 2023-04-03 17:43
> > Try editing `~/zoom/runzoom.sh` and replace last line `BOX64_LD_LIBRARY_PATH=. . . . . . .zoom` with `BOX64_LD_LIBRARY_PATH=${BOX64_LD_LIBRARY_PATH}:${HOME}/zoom/Qt/lib:${HOME}/zoom/cef box64 zoom`
> > 
> > Also try this with a fresh install and it should work.
> 
> That worked for me. I am still at a loss as to what would have caused zoom to break and to suddenly need this fix. It used to work without this change.

Zoom had moved some libraries in its tar.gz so this fix is now needed. Also it may break again in future as zoom constantly changes its linux tgz packaging as far as I have noticed.
But for most of the time it works well with box64 without additional fixes.

**Comment by theofficialgman** [comment] 2023-04-04 02:27
> That worked for me. I am still at a loss as to what would have caused zoom to break and to suddenly need this fix. It used to work without this change.

@Botspot that is simple. older zoom tarfile used to have the qt5 libraries directly in the main folder right next to the zoom binary. download an older tar.xz and you will see this is the case (I checked a really old one from january)

looking at the latest tarfile there appears to be a new binary `ZoomLauncher` that you can launch. Can anyone test running this with box64 and see if it avoids needing the add cef and/or Qt paths to BOX64_LD_LIBRARY_PATH?

**Comment by Botspot** [comment] 2023-04-04 03:29
> > That worked for me. I am still at a loss as to what would have caused zoom to break and to suddenly need this fix. It used to work without this change.
> 
> @Botspot that is simple. older zoom tarfile used to have the qt5 libraries directly in the main folder right next to the zoom binary. download an older tar.xz and you will see this is the case (I checked a really old one from january)
> 
> looking at the latest tarfile there appears to be a new binary `ZoomLauncher` that you can launch. Can anyone test running this with box64 and see if it avoids needing the add cef and/or Qt paths to BOX64_LD_LIBRARY_PATH?

I guess my confusion stemmed from trying the immediately previous tarfile and watching that one not work either. This means Zoom has been broken for a while.

**Comment by Botspot** [comment] 2023-04-05 03:59
Fixed with commit https://github.com/Botspot/pi-apps/commit/3a41b272167576b75bf9735fa283135438bbe28c

**Closed by Botspot** 2023-04-05 03:59 UTC
Labels: bug
