### ISSUE TITLE
OBS Studio

### ISSUE THREAD

**Issue by techcoder20** [Botspot/pi-apps#267] opened 2021-01-22 07:15 UTC
@Botspot Can we add obs studio to pi apps :)

Installation Command:
`wget -qO- https://raw.githubusercontent.com/techcoder20/RPIObsInstaller/main/install.sh | bash`

Uninstallation Command:
`wget -qO- https://raw.githubusercontent.com/techcoder20/RPIObsInstaller/main/uninstall.sh | bash`

**Comment by Botspot** [comment] 2021-01-22 15:39
How useful is OBS Studio on the Pi, considering that it is not hardware accelerated?

**Comment by techcoder20** [comment] 2021-01-22 16:13
@Botspot Lets see even if it's not hardware accelerated the screen recording is pretty good and I have not tried this but people could use it like a HDMI capture card input which streams it to twitch or something

**Comment by chunky-milk** [comment] 2021-01-22 18:30
@techcoder20 using an HDMI capture works, I can confirm that. you can also use a camera, though you will have to enable it with ```raspi-config```.

**Comment by slashtechno** [comment] 2021-01-26 01:57
I think OBS would be an amazing addition to Pi-Apps.

**Comment by Botspot** [comment] 2021-01-26 02:17
> I think OBS would be an amazing addition to Pi-Apps.

But if it's too laggy to be usable due to no hardware acceleration... Who would want that?

**Comment by techcoder20** [comment] 2021-01-26 02:34
Is not that laggy it works pretty good for me

**Comment by Botspot** [comment] 2021-01-26 20:19
@techcoder20 Let's improve your script.

First, let's add some failure notices (like pi-apps' `error` function) if things go wrong.  
Let's add the `-f` flag to your `rm` command so it will suppress errors.  
Let's change your `'''` to `"`, in the desktop entry creation, then change `/home/pi` to `$HOME`.  
Also, can the `~/RPIObsInstaller` folder be removed after installation?

**Comment by techcoder20** [comment] 2021-01-27 00:03
K I will make the required changes.

**Comment by techcoder20** [comment] 2021-01-27 07:41
@Botspot  I have made the required changes in the install script and have made a zip file for pi apps :) I will try to compile a deb file for 64 bit later but this should work for 32-bit

[OBS Studio.zip](https://github.com/Botspot/pi-apps/files/5878451/OBS.Studio.zip)

**Comment by techcoder20** [comment] 2021-01-27 10:22
@Botspot I have made the changes in the script and also added compatibility  for 64 bit. Here is the zip file for pi apps
[OBS Studio.zip](https://github.com/Botspot/pi-apps/files/5879415/OBS.Studio.zip)

**Comment by Botspot** [comment] 2021-01-27 15:39
Dependency installation needs to use pi-apps' pkg-install utility.

**Comment by Botspot** [comment] 2021-01-27 15:49
Also I'd like to ask you to not run a script entirely from your repository like that.  
It'll mess up updates, and be much harder to track down bugs. Let's make the installation scripts as standalone as possible.

BTW: When using your latest zip, it installs instantly without actually doing anything. I have not been able to figure out why.

**Comment by techcoder20** [comment] 2021-01-27 15:54
Sorry About That @Botspot Here is the updated zip file :)
[OBS Studio.zip](https://github.com/Botspot/pi-apps/files/5881373/OBS.Studio.zip)

**Comment by Botspot** [comment] 2021-01-27 21:22
Okay, I've made many improvements to the app. Here it is:  
[OBS Studio.zip](https://github.com/Botspot/pi-apps/files/5883159/OBS.Studio.zip)

One problem: When I try to run obs, it gives this error:
```
pi@raspberrypi:~ $ obs
/usr/bin/obs-exec: error while loading shared libraries: libxcb-composite.so.0: cannot open shared object file: No such file or directory
```

**Comment by Botspot** [comment] 2021-01-27 21:28
Fixed by running:
```
sudo apt install  libxcb-damage0 libxcb-composite0 libxcb-ewmh2
```
After this, OBS launched. Is there anything else that should be installed?  
Here was the full output from OBS:
```
pi@raspberrypi:~ $ MESA_GL_VERSION_OVERRIDE=3.3 /usr/bin/obs-exec
Attempted path: share/obs/obs-studio/locale/en-US.ini
Attempted path: /usr/share/obs/obs-studio/locale/en-US.ini
Attempted path: share/obs/obs-studio/locale.ini
Attempted path: /usr/share/obs/obs-studio/locale.ini
Attempted path: share/obs/obs-studio/themes/Dark.qss
Attempted path: /usr/share/obs/obs-studio/themes/Dark.qss
info: Physical Cores: 4, Logical Cores: 4
info: Physical Memory: 3680MB Total, 457MB Free
info: Kernel Version: Linux 5.4.83-v8+
info: Distribution: "Raspbian GNU/Linux" "10"
info: Session Type: x11
info: Window System: X11.0, Vendor: The X.Org Foundation, Version: 1.20.4
info: Portable mode: false
Attempted path: share/obs/obs-studio/themes/Dark/no_sources.svg
Attempted path: /usr/share/obs/obs-studio/themes/Dark/no_sources.svg
QMetaObject::connectSlotsByName: No matching signal for on_advAudioProps_clicked()
QMetaObject::connectSlotsByName: No matching signal for on_advAudioProps_destroyed()
QMetaObject::connectSlotsByName: No matching signal for on_actionGridMode_triggered()
QMetaObject::connectSlotsByName: No matching signal for on_program_customContextMenuRequested(QPoint)
QMetaObject::connectSlotsByName: No matching signal for on_transitionRemove_clicked()
info: OBS 26.1.2-52-gd7ec87ff0 (linux)
info: ---------------------------------
info: ---------------------------------
info: audio settings reset:
	samples per sec: 48000
	speakers:        2
info: ---------------------------------
info: Initializing OpenGL...
info: Loading up OpenGL on adapter Broadcom V3D 4.2
error: glEnable failed, glGetError returned GL_INVALID_ENUM(0x500)
info: OpenGL loaded successfully, version 3.3 (Core Profile) Mesa 20.2.6 (git-8346d1d7b8), shading language 3.30
info: ---------------------------------
info: video settings reset:
	base resolution:   1280x1024
	output resolution: 852x682
	downscale filter:  Bicubic
	fps:               30/1
	format:            NV12
	YUV mode:          709/Partial
info: NV12 texture support not available
info: Audio monitoring device:
	name: Default
	id: default
info: ---------------------------------
warning: Failed to load 'en-US' text for module: 'decklink-captions.so'
warning: Failed to load 'en-US' text for module: 'decklink-ouput-ui.so'
libDeckLinkAPI.so: cannot open shared object file: No such file or directory
warning: A DeckLink iterator could not be created.  The DeckLink drivers may not be installed
info: No blackmagic support
warning: v4l2loopback not installed, virtual camera disabled
info: FFMPEG VAAPI supported
info: VLC found, VLC video source enabled
info: ---------------------------------
info:   Loaded Modules:
info:     vlc-video.so
info:     text-freetype2.so
info:     sndio.so
info:     rtmp-services.so
info:     obs-x264.so
info:     obs-transitions.so
info:     obs-outputs.so
info:     obs-filters.so
info:     obs-ffmpeg.so
info:     linux-v4l2.so
info:     linux-pulseaudio.so
info:     linux-jack.so
info:     linux-decklink.so
info:     linux-capture.so
info:     linux-alsa.so
info:     image-source.so
info:     frontend-tools.so
info:     decklink-ouput-ui.so
info:     decklink-captions.so
info: ---------------------------------
info: ==== Startup complete ===============================================
info: All scene data cleared
info: ------------------------------------------------
info: Switched to scene 'Scene'
info: ------------------------------------------------
info: Loaded scenes:
info: - scene 'Scene':
info: ------------------------------------------------
Attempted path: share/obs/obs-studio/images/overflow.png
Attempted path: /usr/share/obs/obs-studio/images/overflow.png
```

**Comment by Itai-Nelken** [comment] 2021-01-27 21:37
just a note I think will be useful: there are monitors (like mine) that for some reason will cause some apps like RPi imager and VLC to open in windows so large a toolbar button takes half the screen, then the system freezes. if you are lucky you can somehow open a task manager and kill the app, otherwise the only way is to take out the power.

I had the same issue when using the version of OBS that pikiss compiles, I don't want to try this version because I'm pretty sure I know what will happen.

I think the issue happens only with apps using qt and only in RPiOS (because I think that both RPi imager and VLC use qt).

### so what I want to say:<br>
add a warning to the description about this issue, something like this:<br>
**WARNING!**<br>
 if apps like VLC don't work for for you, be ready to expect OBS to not work as well.

**Comment by Botspot** [comment] 2021-01-27 21:44
> just a note I think will be useful: there are monitors (like mine) that for some reason will cause some apps like RPi imager and VLC to open in windows so large a toolbar button takes half the screen, then the system freezes. if you are lucky you can somehow open a task manager and kill the app, otherwise the only way is to take out the power.

Do you overclock? That sounds like a malfunctioning GPU.  
In any case, I think the RPi forums would be very interested in what's happening for you. I'm sure they will figure out what's going on and help you fix it.

**Comment by Itai-Nelken** [comment] 2021-01-27 22:42
>Do you overclock? That sounds like a malfunctioning GPU.

no, I'm on stock clock and have the same bug since I used the pi for the first time. come to think of it I have never tested my other pi4s, but I did test my pi3 and VLC does work.

>In any case, I think the RPi forums would be very interested in what's happening for you. I'm sure they will figure out what's going on and help you fix it.

Thanks for the suggestion!

**Comment by techcoder20** [comment] 2021-01-27 23:41
> Fixed by running:
> 
> ```
> sudo apt install libxcb-damage0 libxcb-composite0 libxcb-ewmh2
> ```
> 
> After this, OBS launched. Is there anything else that should be installed?
> Here was the full output from OBS:
> 
> ```
> pi@raspberrypi:~ $ MESA_GL_VERSION_OVERRIDE=3.3 /usr/bin/obs-exec
> Attempted path: share/obs/obs-studio/locale/en-US.ini
> Attempted path: /usr/share/obs/obs-studio/locale/en-US.ini
> Attempted path: share/obs/obs-studio/locale.ini
> Attempted path: /usr/share/obs/obs-studio/locale.ini
> Attempted path: share/obs/obs-studio/themes/Dark.qss
> Attempted path: /usr/share/obs/obs-studio/themes/Dark.qss
> info: Physical Cores: 4, Logical Cores: 4
> info: Physical Memory: 3680MB Total, 457MB Free
> info: Kernel Version: Linux 5.4.83-v8+
> info: Distribution: "Raspbian GNU/Linux" "10"
> info: Session Type: x11
> info: Window System: X11.0, Vendor: The X.Org Foundation, Version: 1.20.4
> info: Portable mode: false
> Attempted path: share/obs/obs-studio/themes/Dark/no_sources.svg
> Attempted path: /usr/share/obs/obs-studio/themes/Dark/no_sources.svg
> QMetaObject::connectSlotsByName: No matching signal for on_advAudioProps_clicked()
> QMetaObject::connectSlotsByName: No matching signal for on_advAudioProps_destroyed()
> QMetaObject::connectSlotsByName: No matching signal for on_actionGridMode_triggered()
> QMetaObject::connectSlotsByName: No matching signal for on_program_customContextMenuRequested(QPoint)
> QMetaObject::connectSlotsByName: No matching signal for on_transitionRemove_clicked()
> info: OBS 26.1.2-52-gd7ec87ff0 (linux)
> info: ---------------------------------
> info: ---------------------------------
> info: audio settings reset:
> 	samples per sec: 48000
> 	speakers:        2
> info: ---------------------------------
> info: Initializing OpenGL...
> info: Loading up OpenGL on adapter Broadcom V3D 4.2
> error: glEnable failed, glGetError returned GL_INVALID_ENUM(0x500)
> info: OpenGL loaded successfully, version 3.3 (Core Profile) Mesa 20.2.6 (git-8346d1d7b8), shading language 3.30
> info: ---------------------------------
> info: video settings reset:
> 	base resolution:   1280x1024
> 	output resolution: 852x682
> 	downscale filter:  Bicubic
> 	fps:               30/1
> 	format:            NV12
> 	YUV mode:          709/Partial
> info: NV12 texture support not available
> info: Audio monitoring device:
> 	name: Default
> 	id: default
> info: ---------------------------------
> warning: Failed to load 'en-US' text for module: 'decklink-captions.so'
> warning: Failed to load 'en-US' text for module: 'decklink-ouput-ui.so'
> libDeckLinkAPI.so: cannot open shared object file: No such file or directory
> warning: A DeckLink iterator could not be created.  The DeckLink drivers may not be installed
> info: No blackmagic support
> warning: v4l2loopback not installed, virtual camera disabled
> info: FFMPEG VAAPI supported
> info: VLC found, VLC video source enabled
> info: ---------------------------------
> info:   Loaded Modules:
> info:     vlc-video.so
> info:     text-freetype2.so
> info:     sndio.so
> info:     rtmp-services.so
> info:     obs-x264.so
> info:     obs-transitions.so
> info:     obs-outputs.so
> info:     obs-filters.so
> info:     obs-ffmpeg.so
> info:     linux-v4l2.so
> info:     linux-pulseaudio.so
> info:     linux-jack.so
> info:     linux-decklink.so
> info:     linux-capture.so
> info:     linux-alsa.so
> info:     image-source.so
> info:     frontend-tools.so
> info:     decklink-ouput-ui.so
> info:     decklink-captions.so
> info: ---------------------------------
> info: ==== Startup complete ===============================================
> info: All scene data cleared
> info: ------------------------------------------------
> info: Switched to scene 'Scene'
> info: ------------------------------------------------
> info: Loaded scenes:
> info: - scene 'Scene':
> info: ------------------------------------------------
> Attempted path: share/obs/obs-studio/images/overflow.png
> Attempted path: /usr/share/obs/obs-studio/images/overflow.png
> ```
I think that's it

**Comment by techcoder20** [comment] 2021-01-27 23:53
> Also I'd like to ask you to not run a script entirely from your repository like that.
> It'll mess up updates, and be much harder to track down bugs. Let's make the installation scripts as standalone as possible.

Oh okay I thought it would easy to update if it was in other GitHub repo

**Comment by techcoder20** [comment] 2021-01-28 01:08
@Botspot I have used all your updates to the script which are really great and here is the final zip file
[OBS Studio.zip](https://github.com/Botspot/pi-apps/files/5884103/OBS.Studio.zip)

**Comment by Botspot** [comment] 2021-01-28 03:58
What category should OBS Studio go into?

- Tools
- Editors
- Internet
- Games

I guess it depends on what you use it for.

**Comment by techcoder20** [comment] 2021-01-28 04:01
> What category should OBS Studio go into?
> 
> * Tools
> * Editors
> * Internet
> * Games
> 
> I guess it depends on what you use it for.

I am gonna say tools

**Comment by Botspot** [comment] 2021-01-28 04:08
Added with commit 86c762c20a92ec27e80689a70ae504cfacb9a09d.

**Closed by Botspot** 2021-01-28 04:08 UTC
Labels: App Request
