### ISSUE TITLE
Geekbench browns out my Pi4

### ISSUE THREAD

**Issue by Pythonic456** [Botspot/pi-apps#1688] opened 2022-04-14 17:38 UTC
Here's my setup:

- Pi 4 4GB
- 32GB SDcard
- Bullseye 32 bit

With a clean install, and no modifications to `/boot/config.txt`, when running `geekbench` from Pi-Apps, the single core tests run completely fine. When it reaches the multi core stage, it can do them for a bit but then browns out, maybe crashes or something. I can't think of any way to try seeing a log of something happening. I have the official Pi4 kit from ThePiHut, no modifications to board or power supply, only things plugged into USB are the official keyboard and mouse, with a separately powered USB hub with a HDD.

I tried `overvoltage=6` and up to `overvoltage=8`, but that didn't change anything. This is on default clock by the way.
I'm sure that it doesn't do this on other people's Pis, otherwise you wouldn't have added `geekbench` to Pi-Apps.

Thanks!

**Comment by Crilum** [comment] 2022-04-14 17:48
@Pythonic456 Geekbench did that on my Pi, but only when I had my Pi overclocked to 2GHz, after I set it back to a normal clock, it worked fine..

**Comment by Pythonic456** [comment] 2022-04-15 09:19
Hmm. I have no overclock, yet it still does it... I have tried underclock to 1.2GHz but it still dies.

**Comment by Botspot** [comment] 2022-04-15 14:40
> Hmm. I have no overclock, yet it still does it... I have tried underclock to 1.2GHz but it still dies.

What power supply are you using?

**Comment by Pythonic456** [comment] 2022-04-15 16:59
The official one from [this](https://thepihut.com/collections/raspberry-pi-kits-and-bundles/products/raspberry-pi-4-desktop-kit) Pi 4 kit.

**Comment by Crilum** [comment] 2022-04-15 19:32
Well that Power Supply should be plenty..

**Comment by Pythonic456** [comment] 2022-04-15 20:50
I did read somewhere that 100% on all CPU cores at 1950MHz can easily crash the Pi. Not sure if its correct or not though.

**Comment by Crilum** [comment] 2022-04-15 21:20
>I did read somewhere that 100% on all CPU cores at 1950MHz can easily crash the Pi. Not sure if its correct or not though.

Well, my Pi 4 @ 2GHz will die under hard load so that's probably true..

**Comment by theofficialgman** [comment] 2022-04-16 03:37
fyi, 15 watts is probably VERY close to the limit when geekbenching.
also I've heard that the canakit and pihut power supplies are garbage and have vdroop issues. I suggest testing with a quality usb-c powersupply from the normal brands, such as anker, samsung, etc.

the pi4 is binned at its default clockspeed for a reason, its more efficient there and only guaranteed to have stability up to those clocks. anything past that is silicon lottery and it may seem stable until you hit it with an intense load.

**Comment by Crilum** [comment] 2022-04-16 04:11
I have an official RPi Power Supply, and it works fine with Geekbench at normal clock.

**Comment by Pythonic456** [comment] 2022-04-16 08:13
I will try one of my Samsung power supplies, although to be honest I don't think it's going to make a whole lot of difference. One way that might be possible would involve using the GPIO 5V and Ground pins to feed power into the Pi, possibly having a chance of giving it more than 15W.

**Comment by Botspot** [comment] 2022-04-18 15:21
I'm closing this issue because it's not a problem caused by Pi-Apps.

**Closed by Botspot** 2022-04-18 15:21 UTC
Labels: wontfix
