### ISSUE TITLE
Add Lunar Client

### ISSUE THREAD

**Issue by Pythonic456** [Botspot/pi-apps#762] opened 2021-06-24 18:29 UTC
https://github.com/gl91306/lunar/

This is Lunar Client ported to run on Raspberry Pi.
It is already on [PiWare](https://gitlab.com/joaopizani/piware).
Upsides:

- Higher FPS than standard Minecraft
- Nicer UI
- More features

Downsides:

- Doesn't support Microsoft accounts (and won't until Moonsworth makes Lunar support them again)
- Takes up to 10 minutes to install

@gl91306 said they don't want it on Pi-Apps because it has a lot more users, who would constantly
ask about Microsoft accounts on it. I volunteer to take all these issues myself.

Thanks!

**Comment by mobilegmYT** [comment] 2021-06-24 19:00
> https://github.com/gl91306/lunar/
> 
> This is Lunar Client ported to run on Raspberry Pi.
> It is already on [PiWare](https://gitlab.com/joaopizani/piware).
> Upsides:
> 
> * Higher FPS than standard Minecraft
> * Nicer UI
> * More features
> 
> Downsides:
> 
> * Doesn't support Microsoft accounts (and won't until Moonsworth makes Lunar support them again)
> * Takes up to 10 minutes to install
> 
> @gl91306 said they don't want it on Pi-Apps because it has a lot more users, who would constantly
> ask about Microsoft accounts on it. I volunteer to take all these issues myself.
> 
> Thanks!

I've tested GL's fork before. I haven't gotten it to work for myself but someone with a clean install can try it. I will note it has lwjgl linking ATM which makes this high priority, even if MS acc support isn't on it yet.

**Comment by Pythonic456** [comment] 2021-06-24 19:13
@mobilegmYT With the help of @gl91306 I set it up and got it running, and it works fine for me.
Maybe I could help you get it to run?

**Comment by mobilegmYT** [comment] 2021-06-24 19:14
> @mobilegmYT With the help of @gl91306 I set it up and got it running, and it works fine for me.
> Maybe I could help you get it to run?

Sure, my Discord is RPiNews#0816

**Comment by mobilegmYT** [comment] 2021-06-24 20:03
> @mobilegmYT With the help of @gl91306 I set it up and got it running, and it works fine for me.
> Maybe I could help you get it to run?

Wait woah, the newest version worked for me... whoop whoop!

**Comment by marv-nerd** [comment] 2021-06-25 00:58
I thought Microsoft already works on lunar

**Comment by mobilegmYT** [comment] 2021-06-25 01:03
> I thought Microsoft already works on lunar

Yea the option is there but according to reddit it's broken? I can't test it tho since I haven't migrated so if anyone here wants to give it a shot, just use the install instructions on https://github.com/gl91306/lunar/

**Comment by marv-nerd** [comment] 2021-06-25 01:09
I played lunar on another computer with Microsoft account, and it works perfectly fine

**Comment by Pythonic456** [comment] 2021-06-25 07:59
> > @mobilegmYT With the help of @gl91306 I set it up and got it running, and it works fine for me.
> > Maybe I could help you get it to run?
> 
> Wait woah, the newest version worked for me... whoop whoop!

Cool!

**Comment by gl91306** [comment] 2021-06-28 22:35
The reason that MS accounts don't work on RPIS for lunar has nothing to do with the official launcher. It has to do with the fact that a native library isn't compiled for armhf. The Microsoft account popup in lunarcleitn depends on javafx, which is already available for arm, if you know where to look. The problem is, the MS account popup uses jfx's Webkit plugin, which essentially embeds the MS login screen. This plugin is dependent on a native library called libjfxwebkit.so, which IS available for armhf, but only for java 8. For some reason, the people who compile javafx for armhf stopped compiling libjfxwebkit.so past java 8. And yes, I have tried using java 8's .so file with java 16, and that doesn't work. So yeah, the only reason MS accounts don't work on Lunar client for arm, is because a native library we need is on found precompiled anywhere on the internet. I have to compile it my self, but there are a lot of challenges regarding that, including the fact that you cant compile directly on the pi, which i'm trying to fix. Its taking a while though. I will however, post when I am completed(It will be in #announcements in the pi-ware discord). And that's about it.

**Comment by gl91306** [comment] 2021-06-28 22:38
that was a long paragraph :P

**Closed** 2021-07-06 08:42 UTC
Labels: App Request
