### ISSUE TITLE
make vivaldi run faster and better

### ISSUE THREAD

**Issue by Itai-Nelken** [Botspot/pi-apps#674] opened 2021-05-21 07:39 UTC
Idea by [craigevil from the botspot discord server #general channel](https://discord.com/channels/770629697909424159/770629697909424162/845129611574640641)

change the 'Exec' part of the desktop shortcut to: `Exec=/usr/bin/vivaldi-stable --use-gl=desktop %U`

**Comment by Pythonic456** [comment] 2021-05-25 18:11
Seems to change nothing except to output this error:
`[13092:13092:0525/190818.091097:ERROR:gl_surface_presentation_helper.cc(259)] GetVSyncParametersIfAvailable() failed for 1 times!`
And repeats this every minute or so.
Is there anything else I need to change?

**Comment by Itai-Nelken** [comment] 2021-05-25 18:33
I don't know..

**Comment by theofficialgman** [comment] 2022-05-07 23:45
closing, performance in browsers isn't a real concern of pi-apps.
the browser gets to decide which backend is most performant and stable for a platform (whether that be a desktop GL backend, gles backend, or vulkan)

**Closed by theofficialgman** 2022-05-07 23:45 UTC
Labels: suggestion

**Comment by Botspot** [comment] 2022-05-08 03:54
In addition, `--use-gl=desktop` started causing problems for me on RPi's modified Chromium. It took a long time to identify the cause of my problems.

A similar thing could happen in the future with Vivaldi.

However I wouldn't go as far to say that Pi-Apps is not interested in performance web-browsing. In the future I may release an app to boost Chromium performance on the older RPi3 model. (HW video deciding, smooth 720p youtube, partial RAMfs chromium cache & config, and more)
