### ISSUE TITLE
add optifine to mc java?

### ISSUE THREAD

**Issue by imyetihearmeroar** [Botspot/pi-apps#75] opened 2020-11-09 14:59 UTC
would it be possible for you to add a way to install optifine to improve performance?

**Comment by mobilegmYT** [comment] 2020-11-09 15:04
You could totally add optfine to your Minecraft install! It isn't added by default though because we don't know what mc version your are using. But yes, you could download optfine for your version, then run `java -jar path/to/optfine/jar`.en click install, and go to your current profile to edit the mc version, and switch it to optfine.

**Comment by Botspot** [comment] 2020-11-09 16:56
I think @mobilegmYT 's answer covers it all.

Closing this issue now, but @imyetihearmeroar if you have more to ask, simply reply below and I'll re-open it for you.

**Comment by imyetihearmeroar** [comment] 2020-11-09 19:13
> You could totally add optfine to your Minecraft install! It isn't added by default though because we don't know what mc version your are using. But yes, you could download optfine for your version, then run `java -jar path/to/optfine/jar`.en click install, and go to your current profile to edit the mc version, and switch it to optfine.

What you said works and installs, but when i try to launch the optifine profile it crashes with this log:
---- Minecraft Crash Report ----
// I feel sad now :(

Time: 11/9/20 2:11 PM
Description: Initializing game

java.lang.ExceptionInInitializerError
	at dkd.<init>(GameSettings.java:177)
	at djz.<init>(SourceFile:440)
	at net.minecraft.client.main.Main.main(SourceFile:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:159)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:30)
Caused by: java.lang.RuntimeException: java.lang.UnsatisfiedLinkError: Failed to locate library: liblwjgl32.so
	at deo.<clinit>(SourceFile:46)
	... 9 more
Caused by: java.lang.UnsatisfiedLinkError: Failed to locate library: liblwjgl32.so
	at org.lwjgl.system.Library.loadSystem(Library.java:147)
	at org.lwjgl.system.Library.loadSystem(Library.java:67)
	at org.lwjgl.system.Library.<clinit>(Library.java:50)
	at org.lwjgl.system.MemoryAccessJNI.<clinit>(MemoryAccessJNI.java:13)
	at org.lwjgl.system.Pointer.<clinit>(Pointer.java:28)
	at org.lwjgl.system.Platform.mapLibraryNameBundled(Platform.java:80)
	at org.lwjgl.glfw.GLFW.<clinit>(GLFW.java:674)
	at sun.misc.Unsafe.ensureClassInitialized(Native Method)
	at java.lang.invoke.DirectMethodHandle$EnsureInitialized.computeValue(DirectMethodHandle.java:330)
	at java.lang.invoke.DirectMethodHandle$EnsureInitialized.computeValue(DirectMethodHandle.java:327)
	at java.lang.ClassValue.getFromHashMap(ClassValue.java:227)
	at java.lang.ClassValue.getFromBackup(ClassValue.java:209)
	at java.lang.ClassValue.get(ClassValue.java:115)
	at java.lang.invoke.DirectMethodHandle.checkInitialized(DirectMethodHandle.java:351)
	at java.lang.invoke.DirectMethodHandle.ensureInitialized(DirectMethodHandle.java:341)
	at java.lang.invoke.DirectMethodHandle.ensureInitialized(DirectMethodHandle.java:373)
	at deo.<clinit>(SourceFile:43)
	... 9 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at dkd.<init>(GameSettings.java:177)
	at djz.<init>(SourceFile:440)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(SourceFile:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:159)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:30)

-- System Details --
Details:
	Minecraft Version: 1.16.4
	Minecraft Version ID: 1.16.4
	Operating System: Linux (arm) version 5.4.72-v7l+
	Java Version: 1.8.0_251, Oracle Corporation
	Java VM Version: Java HotSpot(TM) Server VM (mixed mode), Oracle Corporation
	Memory: 103931040 bytes (99 MB) / 344801280 bytes (328 MB) up to 523501568 bytes (499 MB)
	CPUs: 4
	JVM Flags: 5 total; -Xmx512M -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	Launched Version: 1.16.4-OptiFine_HD_U_G5
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: ~~ERROR~~ NoClassDefFoundError: Could not initialize class org.lwjgl.glfw.GLFW
	GL Caps: 
	Using VBOs: Yes
	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	CPU: <unknown>
	OptiFine Version: OptiFine_1.16.4_HD_U_G5
	OptiFine Build: 20201106-171901
	Shaders: null
	OpenGlVersion: null
	OpenGlRenderer: null
	OpenGlVendor: null
	CpuCount: 0

Sorry to bother you, but I cant find this anywhere else on the internet.

**Comment by Botspot** [comment] 2020-11-09 19:18
Basically, the launcher_profiles.json needs to be edited in order to run Minecraft successfully.

Pi-Apps automatically generates launcher_profiles.json with the correct flags in place. That way, Minecraft launches successfully, without having to make any changes to the Profile.

Here's the problem: When you install Optifine, it creates a new profile that does not include those necessary java flags.

We are discussing the possibilities on the [Pi-Apps Discord server](https://discord.gg/RXSTvaUvuu) right now.

**Comment by Pythonic456** [comment] 2020-11-12 17:17
So, can I do this manually? I'm having the same issue and not sure how to fix it...

**Comment by mobilegmYT** [comment] 2020-11-12 17:19
@Pythonic456 @imyetihearmeroar  Just edit the Optfine profile and follow https://www.noxxtech.tk/minecraft-install#h.fpnon3xvmuoz

**Comment by MTCK123** [comment] 2020-11-27 20:40
@mobilegmYT  Ok so I treid what the artical said to do but it came up with this?
What I did was edit the JVM argument and added `-Dorg.lwjgl.librarypath=/home/pi/lwjgl3arm32` that but had this error report: 
`---- Minecraft Crash Report ----
// Sorry :(

Time: 11/28/20 7:36 AM
Description: Initializing game

java.lang.ExceptionInInitializerError
	at dkd.<init>(GameSettings.java:177)
	at djz.<init>(SourceFile:440)
	at net.minecraft.client.main.Main.main(SourceFile:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:159)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:30)
Caused by: java.lang.RuntimeException: java.lang.UnsatisfiedLinkError: Failed to locate library: liblwjgl32.so
	at deo.<clinit>(SourceFile:46)
	... 9 more
Caused by: java.lang.UnsatisfiedLinkError: Failed to locate library: liblwjgl32.so
	at org.lwjgl.system.Library.loadSystem(Library.java:147)
	at org.lwjgl.system.Library.loadSystem(Library.java:67)
	at org.lwjgl.system.Library.<clinit>(Library.java:50)
	at org.lwjgl.system.MemoryAccessJNI.<clinit>(MemoryAccessJNI.java:13)
	at org.lwjgl.system.Pointer.<clinit>(Pointer.java:28)
	at org.lwjgl.system.Platform.mapLibraryNameBundled(Platform.java:80)
	at org.lwjgl.glfw.GLFW.<clinit>(GLFW.java:674)
	at sun.misc.Unsafe.ensureClassInitialized(Native Method)
	at java.lang.invoke.DirectMethodHandle$EnsureInitialized.computeValue(DirectMethodHandle.java:330)
	at java.lang.invoke.DirectMethodHandle$EnsureInitialized.computeValue(DirectMethodHandle.java:327)
	at java.lang.ClassValue.getFromHashMap(ClassValue.java:227)
	at java.lang.ClassValue.getFromBackup(ClassValue.java:209)
	at java.lang.ClassValue.get(ClassValue.java:115)
	at java.lang.invoke.DirectMethodHandle.checkInitialized(DirectMethodHandle.java:351)
	at java.lang.invoke.DirectMethodHandle.ensureInitialized(DirectMethodHandle.java:341)
	at java.lang.invoke.DirectMethodHandle.ensureInitialized(DirectMethodHandle.java:373)
	at deo.<clinit>(SourceFile:43)
	... 9 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at dkd.<init>(GameSettings.java:177)
	at djz.<init>(SourceFile:440)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(SourceFile:177)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:159)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:30)

-- System Details --
Details:
	Minecraft Version: 1.16.4
	Minecraft Version ID: 1.16.4
	Operating System: Linux (arm) version 5.4.72-v7l+
	Java Version: 1.8.0_251, Oracle Corporation
	Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
	Memory: 54538352 bytes (52 MB) / 255066112 bytes (243 MB) up to 255066112 bytes (243 MB)
	CPUs: 4
	JVM Flags: 4 total; -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	Launched Version: 1.16.4-OptiFine_HD_U_G5
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: ~~ERROR~~ NoClassDefFoundError: Could not initialize class org.lwjgl.glfw.GLFW
	GL Caps: 
	Using VBOs: Yes
	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	CPU: <unknown>
	OptiFine Version: OptiFine_1.16.4_HD_U_G5
	OptiFine Build: 20201106-171901
	Shaders: null
	OpenGlVersion: null
	OpenGlRenderer: null
	OpenGlVendor: null
	CpuCount: 0`
Personally I have no Idea what this means but hopefully you do.

**Comment by gl91306** [comment] 2020-12-05 22:14
There are my java arguments -Dorg.lwjgl.librarypath=/home/pi/lwjgl3arm32 -Xmx2G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn1G
(I have a RPI4 4G)

**Comment by gl91306** [comment] 2020-12-05 22:20
Also are you on a 64 bit os? then you have to add /opt/jdk/jdk1.8.0_251/bin/java to executable

**Comment by zachdwilliams** [comment] 2020-12-16 11:29
> You could totally add optfine to your Minecraft install! It isn't added by default though because we don't know what mc version your are using. But yes, you could download optfine for your version, then run `java -jar path/to/optfine/jar`.en click install, and go to your current profile to edit the mc version, and switch it to optfine.

How exactly do you download optifine?

**Comment by mobilegmYT** [comment] 2020-12-16 16:22
@zachdwilliams You have to download it from the website.

**Comment by zachdwilliams** [comment] 2020-12-18 07:39
Alright

**Comment by Botspot** [comment] 2021-01-05 17:21
I'm afraid this is not possible to include by default upon installation. :(

**Closed by Botspot** 2021-01-05 17:21 UTC
