### ISSUE TITLE
wine (x86 with box86)

### ISSUE THREAD

**Issue by Itai-Nelken** [Botspot/pi-apps#151] opened 2020-12-22 18:56 UTC
[Wine (x86).zip](https://github.com/Botspot/pi-apps/files/5731964/Wine.x86.zip)
<b>uninstaller not finished yet!</b> 
can someone on RPiOS test it?
also I don't know how to remove the wine .debs, can someone that knows add the needed commands to the `uninstall`
 script?

**Comment by ilobilo** [comment] 2020-12-23 17:06
There are several ways to uninstall .deb packages
https://linuxhint.com/uninstall-debian-packages/

**Comment by Itai-Nelken** [comment] 2020-12-23 18:57
> There are several ways to uninstall .deb packages
> https://linuxhint.com/uninstall-debian-packages/

@ilobilo thanks! could you test it? I don't have a sd card with RPiOS right now.
My problem is, I can't test it because I'm on TwisterOS that has wine pre installed and I don't wan't to mess with it. so I can't see how the packages are called so I don't know the command to remove them.

**Comment by Itai-Nelken** [comment] 2020-12-24 12:07
[Wine (x86).zip](https://github.com/Botspot/pi-apps/files/5739496/Wine.x86.zip)
@Botspot pi-apps runs pkg-install **before** running the rest of the commands, right?
because winetricks (that this script also installs) needs `cabextract` to run.

**Comment by Itai-Nelken** [comment] 2020-12-25 14:38
ok, I'm testing it.

**Comment by Itai-Nelken** [comment] 2020-12-25 17:40
[Wine (x86).zip](https://github.com/Botspot/pi-apps/files/5742241/Wine.x86.zip)
fixed a few bugs, installer (should be) finished.
it doesn't work at all for me. it downloads and extracts the debs, than copies everything. but when running `wine wineboot` it errors out.
no need to uninstall the debs as they are extracted and not installed (I didn't understand that until now).

can someone test it please?

**Comment by Botspot** [comment] 2020-12-26 03:39
I haven't had time to look at this yet, but perhaps this would help: https://www.raspberrypi.org/forums/viewtopic.php?f=63&t=292105&p=1766662&hilit=wine+twister#p1766662

**Comment by Itai-Nelken** [comment] 2020-12-26 08:35
[Wine (x86).zip](https://github.com/Botspot/pi-apps/files/5742853/Wine.x86.zip)
> I haven't had time to look at this yet, but perhaps this would help: https://www.raspberrypi.org/forums/viewtopic.php?f=63&t=292105&p=1766662&hilit=wine+twister#p1766662

Thanks @Botspot, I used the TwisterOS wine, and now everything is simpler. I just needs testing.

**Comment by Itai-Nelken** [comment] 2020-12-26 14:30
[Wine (x86).zip](https://github.com/Botspot/pi-apps/files/5743213/Wine.x86.zip)
I removed winetricks because it's malfunctioning. but wine works, I installed 7zip with it.
**left to do:**
- add it to the hidelist in TwisterOS.

can someone test it just to be sure it really works?

**Comment by Botspot** [comment] 2020-12-26 14:30
You're welcome to put `pkg-install` wherever you want.  
Does the script rely on the `cabextract` package?

Concerning your YAD dialogs, do you think that is such a good idea? It would be pretty cool if somebody could click `Install`, and then leave for work. Currently those YAD dialogs will hold up the script until a button is clicked.  
Speaking of buttons, do you think many people would actually want to click "Cancel"?

Let's suppress these errors:
```
Installing Wine (x86) with install-32 script
gio: file:///home/pi/wine-old: Error trashing file /home/pi/wine-old: No such file or directory
gio: file:///home/pi/.wine-old: Error trashing file /home/pi/.wine-old: No such file or directory
mv: cannot stat '/usr/local/bin/wine': No such file or directory
mv: cannot stat '/usr/local/bin/winecfg': No such file or directory
mv: cannot stat '/usr/local/bin/wineserver': No such file or directory
```
Suppressing those errors is easy enough: just add ` &>/dev/null` to the end of each `mv`, `rm`, and `gio trash` command.

**Comment by Botspot** [comment] 2020-12-26 14:31
And I just got this error:
```
2020-12-26 08:27:31 (18.0 MB/s) - ‘/home/pi/wine.tgz’ saved [67938781/67938781]

tar: /home/pi/wine: Not found in archive
tar: Exiting with failure status due to previous errors
```

**Comment by Itai-Nelken** [comment] 2020-12-26 14:36
> And I just got this error:
> 
> ```
> 2020-12-26 08:27:31 (18.0 MB/s) - ‘/home/pi/wine.tgz’ saved [67938781/67938781]
> 
> tar: /home/pi/wine: Not found in archive
> tar: Exiting with failure status due to previous errors
> ```

I thought i fixed it...
@Botspot can you test this version:
[Wine (x86).zip](https://github.com/Botspot/pi-apps/files/5743218/Wine.x86.zip)
its the version that worked for me, I might have messed up to different versions of the script accidentally.

**Comment by Itai-Nelken** [comment] 2020-12-26 14:44
> And I just got this error:
> 
> ```
> 2020-12-26 08:27:31 (18.0 MB/s) - ‘/home/pi/wine.tgz’ saved [67938781/67938781]
> 
> tar: /home/pi/wine: Not found in archive
> tar: Exiting with failure status due to previous errors
> ```

I thought i fixed it...
@Botspot can you test this version:
[Wine (x86).zip](https://github.com/Botspot/pi-apps/files/5743226/Wine.x86.zip)
its the version that worked for me (but I commented out winetricks), I might have messed up to different versions of the script accidentally.

**Comment by Botspot** [comment] 2020-12-26 15:00
I'm working on my own version of the script at the moment.

**Comment by Botspot** [comment] 2020-12-26 15:04
Any idea why my box86 says "Error: file is not found (check BOX86_PATH)"?

**Comment by Itai-Nelken** [comment] 2020-12-26 15:06
> Any idea why my box86 says "Error: file is not found (check BOX86_PATH)"?
No, when those that happen?

**Comment by Botspot** [comment] 2020-12-26 15:10
> > Any idea why my box86 says "Error: file is not found (check BOX86_PATH)"?
> 
> No, when those that happen?

I think that was an issue caused by box86 somehow. I've updated it and it seems to be working now.

**Comment by Botspot** [comment] 2020-12-26 15:11
Okay, using your latest zip:
```
mv: 'wine' and '/home/pi/wine' are the same file
```

**Comment by Itai-Nelken** [comment] 2020-12-26 15:14
> Okay, using your latest zip:
> 
> ```
> mv: 'wine' and '/home/pi/wine' are the same file
> ```

If I remember correctly it happened to me as well, but wine still worked. try to finish the installation and see if wine works.
I'm not sure what causes it. maybe change to the home directory, and than download and extract wine.

**Comment by Botspot** [comment] 2020-12-26 15:15
Okay I removed the `mv` line and now it seems to be working.

What were your thoughts on removing the pop-up dialogs? https://github.com/Botspot/pi-apps/issues/151#issuecomment-751361706

**Comment by Botspot** [comment] 2020-12-26 15:17
> Okay I removed the `mv` line and now it seems to be working.

Or not. Any ideas?
```
Saving to: ‘/home/pi/wine.tgz’

/home/pi/wine.tgz   100%[===================>]  64.79M  20.9MB/s    in 3.1s    

2020-12-26 09:14:36 (20.9 MB/s) - ‘/home/pi/wine.tgz’ saved [67938781/67938781]

Box86 with Dynarec v0.1.9 96f944c8 built on Dec 21 2020 00:03:56
Box86 with Dynarec v0.1.9 96f944c8 built on Dec 21 2020 00:03:56
wine: created the configuration directory '/home/pi/.wine'
Box86 with Dynarec v0.1.9 96f944c8 built on Dec 21 2020 00:03:56
0048:err:ole:StdMarshalImpl_MarshalInterface Failed to create ifstub, hres=0x80004002
0048:err:ole:CoMarshalInterface Failed to marshal the interface {6d5140c1-7436-11ce-8034-00aa006009fa}, 80004002
0048:err:ole:get_local_server_stream Failed: 80004002
0050:err:ole:StdMarshalImpl_MarshalInterface Failed to create ifstub, hres=0x80004002
0050:err:ole:CoMarshalInterface Failed to marshal the interface {6d5140c1-7436-11ce-8034-00aa006009fa}, 80004002
0050:err:ole:get_local_server_stream Failed: 80004002
005c:fixme:file:NtLockFile I/O completion on lock not implemented yet
005c:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION
005c:err:mscoree:LoadLibraryShim error reading registry key for installroot
005c:err:mscoree:LoadLibraryShim error reading registry key for installroot
005c:err:mscoree:LoadLibraryShim error reading registry key for installroot
005c:err:mscoree:LoadLibraryShim error reading registry key for installroot
0064:fixme:file:NtLockFile I/O completion on lock not implemented yet
0064:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION
0064:err:mscoree:LoadLibraryShim error reading registry key for installroot
0064:err:mscoree:LoadLibraryShim error reading registry key for installroot
0064:err:mscoree:LoadLibraryShim error reading registry key for installroot
0064:err:mscoree:LoadLibraryShim error reading registry key for installroot
0064:fixme:msi:internal_ui_handler internal UI not implemented for message 0x0b000000 (UI level = 5)
0064:fixme:msi:internal_ui_handler internal UI not implemented for message 0x0b000000 (UI level = 5)
005c:fixme:msi:internal_ui_handler internal UI not implemented for message 0x0b000000 (UI level = 1)
005c:fixme:msi:internal_ui_handler internal UI not implemented for message 0x0b000000 (UI level = 1)
0074:fixme:file:NtLockFile I/O completion on lock not implemented yet
0074:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION
0074:fixme:msi:internal_ui_handler internal UI not implemented for message 0x0b000000 (UI level = 1)
0074:fixme:msi:internal_ui_handler internal UI not implemented for message 0x0b000000 (UI level = 1)
0040:err:winediag:SECUR32_initNTLMSP ntlm_auth was not found or is outdated. Make sure that ntlm_auth >= 3.0.25 is in your path. Usually, you can find it in the winbind package of your distribution.
0040:fixme:dwmapi:DwmIsCompositionEnabled 6D95DD14
007c:fixme:iphlpapi:NotifyIpInterfaceChange (family 0, callback 0x6a0df537, context 0x7af49060, init_notify 0, handle 0x79b5fce8): stub
0040:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION
wine: configuration in L"/home/pi/.wine" has been updated.
0024:err:module:__wine_process_init failed to load L"Z:\\home\\pi\\wine\\bin\\wineboot", error c000012f
```

**Comment by Itai-Nelken** [comment] 2020-12-26 15:27
thats the errors I got with my original script, but they disappeared after using the TwisterOS wine.

**Comment by Itai-Nelken** [comment] 2020-12-26 15:27
did the wine `mono` and `gecko` installers appear?

**Comment by Botspot** [comment] 2020-12-26 15:33
Now no window is appearing at all. :(  
It's consistently saying:
```
Box86 with Dynarec v0.1.9 96f944c8 built on Dec 21 2020 00:03:56
Box86 with Dynarec v0.1.9 96f944c8 built on Dec 21 2020 00:03:56
Box86 with Dynarec v0.1.9 96f944c8 built on Dec 21 2020 00:03:56
0024:err:module:__wine_process_init failed to load L"J:\\home\\pi\\wine\\bin\\wineboot", error c000012f
```

Here's my minimal zip:
[Wine (x86).zip](https://github.com/Botspot/pi-apps/files/5743267/Wine.x86.zip)

**Comment by Itai-Nelken** [comment] 2020-12-26 15:49
I'm testing your script right now.
something to add to the `description` file is that the menu shortcuts stay even after uninstalling. and maybe add how to remove them before removing wine.

**Comment by Itai-Nelken** [comment] 2020-12-26 16:08
@Botspot your script works! I installed 7zip and notepad ++ and they work (I tested 7zip by extracting its installer). 
also I forgot to add a menu shortcut to wine configuration (command: `wine winecfg` or `wine ~/wine/bin/winecfg` if the first one doesn't work (its supposed to).

**Comment by fabianmendes** [comment] 2020-12-26 17:04
Amazing issue.

**Comment by ilobilo** [comment] 2020-12-26 17:27
> > There are several ways to uninstall .deb packages
> > https://linuxhint.com/uninstall-debian-packages/
> 
> @ilobilo thanks! could you test it? I don't have a sd card with RPiOS right now.
> My problem is I can't test it because I'm on TwisterOS that has wine pre installed and I don't wan't to mess with it, so I can't see how the packages are called so I don't know the command to remove them.

Sorry i dont have rpi yet.

**Comment by Itai-Nelken** [comment] 2020-12-26 17:56
@ilobilo doesn't matter anymore, but thanks!

**Comment by Botspot** [comment] 2020-12-26 21:20
Okay, despite those errors and Wine's failure to display a pop-up during install, it seems to be working!

**Comment by Botspot** [comment] 2020-12-27 03:49
@Itai-Nelken You mentioned that you removed winetricks. Do you hope to add it back, or should we remove your little "note: " text from the description?

**Comment by Itai-Nelken** [comment] 2020-12-27 04:41
> @Itai-Nelken You mentioned that you removed winetricks. Do you hope to add it back, or should we remove your little "note: " text from the description?

remove it, its only causing problems. also we need to make the script add a menu button for wine configuration (`wine winecfg`).

**Comment by Botspot** [comment] 2020-12-27 04:49
Do you think you could make the `wine winecfg` menu button?

**Comment by Itai-Nelken** [comment] 2020-12-27 05:02
> Do you think you could make the `wine winecfg` menu button?

yes, of course, I'll also add the usage instructions to the description file.

**Comment by Itai-Nelken** [comment] 2020-12-27 15:55
[Wine (x86).zip](https://github.com/Botspot/pi-apps/files/5744736/Wine.x86.zip)
@Botspot can you test it, just to be sure it works and remove the `_MACOSX` folder (if it's there).

**Comment by Itai-Nelken** [comment] 2020-12-27 19:21
[Wine (x86).zip](https://github.com/Botspot/pi-apps/files/5745055/Wine.x86.zip)
@Botspot, updated the description with a note about menu shortcuts created by wine.
otherwise the same as last zip.
(remove `_MACOSX` folder as well, and test it to see if it works).
also maybe ask in your discord server if someone can test it, just to be sure that it really works before adding it to pi-apps.

**Comment by PUP-Loki** [comment] 2020-12-27 20:23
just given it a test and I get this error

--2020-12-27 20:19:11--  https://twisteros.com/wine.tgz
Resolving twisteros.com (twisteros.com)... 185.199.108.153, 185.199.109.153, 185.199.110.153, ...
Connecting to twisteros.com (twisteros.com)|185.199.108.153|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 67938781 (65M) [application/octet-stream]
Saving to: ‘/home/pi/wine.tgz’

/home/pi/wine.tgz   100%[===================>]  64.79M  11.0MB/s    in 5.9s    

2020-12-27 20:19:20 (11.0 MB/s) - ‘/home/pi/wine.tgz’ saved [67938781/67938781]

/home/pi/pi-apps/apps/Wine (x86)/install-32: line 41: syntax error near unexpected token `('
/home/pi/pi-apps/apps/Wine (x86)/install-32: line 41: `Icon="$HOME/pi-apps/Wine (x86)/icon-64.png"'

Failed to install Wine (x86) with install-32 script!

Close this window to exit

**Comment by Itai-Nelken** [comment] 2020-12-27 20:28
> just given it a test and I get this error
> 
> --2020-12-27 20:19:11-- https://twisteros.com/wine.tgz
> Resolving twisteros.com (twisteros.com)... 185.199.108.153, 185.199.109.153, 185.199.110.153, ...
> Connecting to twisteros.com (twisteros.com)|185.199.108.153|:443... connected.
> HTTP request sent, awaiting response... 200 OK
> Length: 67938781 (65M) [application/octet-stream]
> Saving to: ‘/home/pi/wine.tgz’
> 
> /home/pi/wine.tgz 100%[===================>] 64.79M 11.0MB/s in 5.9s
> 
> 2020-12-27 20:19:20 (11.0 MB/s) - ‘/home/pi/wine.tgz’ saved [67938781/67938781]
> 
> /home/pi/pi-apps/apps/Wine (x86)/install-32: line 41: syntax error near unexpected token `(' /home/pi/pi-apps/apps/Wine (x86)/install-32: line 41: `Icon="$HOME/pi-apps/Wine (x86)/icon-64.png"'
> 
> Failed to install Wine (x86) with install-32 script!
> 
> Close this window to exit
> 
> it looks like you are missing and apps folder
> Icon="$HOME/pi-apps/Wine (x86)/icon-64.png"
> Icon="$HOME/pi-apps/apps/Wine (x86)/icon-64.png"

aargh, I messed up bash syntax again, @Botspot can you fix it please?

**Comment by PUP-Loki** [comment] 2020-12-27 20:29
just got it working with this code 
Icon="$HOME/pi-apps/apps/Wine \(x86\)/icon-64.png"

**Comment by Itai-Nelken** [comment] 2020-12-27 20:34
> just got it working with this code
> Icon="$HOME/pi-apps/apps/Wine (x86)/icon-64.png"

@PUP-Loki thanks, it appears I didn't mess up bash syntax, but miswrote the path.
thanks for finding this out!

**Comment by Itai-Nelken** [comment] 2020-12-27 20:37
[Wine (x86).zip](https://github.com/Botspot/pi-apps/files/5745146/Wine.x86.zip)
fixed icon path in wine cfg menu button thanks to @PUP-Loki.
otherwise the same as last zip.
(remove _MACOSX folder as well, and test it to see if it works).

**Comment by PUP-Loki** [comment] 2020-12-27 20:57
fix error in install and uninstall scripts
[Wine.x86.zip](https://github.com/Botspot/pi-apps/files/5745193/Wine.x86.zip)

**Comment by Botspot** [comment] 2020-12-27 22:07
@itai_nelken Is there really a good reason to remove `~/.wine` upon installation?

Seems like this makes updating a pain.

**Comment by Botspot** [comment] 2020-12-28 03:54
@Itai-Nelken I'm improving the menu button.  
What category should winecfg go in? Let's not leave it in `Other`.

**Comment by Itai-Nelken** [comment] 2020-12-28 05:14
> @Itai-Nelken I'm improving the menu button.
> What category should winecfg go in? Let's not leave it in `Other`.

maybe Games? I don't know.

**Comment by Itai-Nelken** [comment] 2020-12-28 05:15
> @itai_nelken Is there really a good reason to remove `~/.wine` upon installation?
> 
> Seems like this makes updating a pain.

it gets removed in case there is a broken wine prefix there, so you get a new one. I think it's necessary, even though it will be a pain when updating.

**Comment by Itai-Nelken** [comment] 2020-12-28 07:22
> @itai_nelken Is there really a good reason to remove `~/.wine` upon installation?
> 
> Seems like this makes updating a pain.

also, maybe instead of deleting, just make a backup of it so `~/.wine.old`. than if that file exists, ask user if they want to keep it or create a new one.

**Comment by Itai-Nelken** [comment] 2020-12-28 13:06
@Botspot I just cleared wine's cache (delete `~/.cache/wine`) and tried this zip  [Wine.x86.zip](https://github.com/Botspot/pi-apps/files/5745193/Wine.x86.zip), and the wine mono and gecko installers appeared. reason: wine coaches the installers, so they don't appear after installing first time.

**Comment by Botspot** [comment] 2020-12-28 18:14
> > What category should winecfg go in? Let's not leave it in `Other`.
> 
> maybe Games? I don't know.

I'm thinking of putting it in System Tools.

> @Botspot I just cleared wine's cache (delete `~/.cache/wine`) and tried this zip [Wine.x86.zip](https://github.com/Botspot/pi-apps/files/5745193/Wine.x86.zip), and the wine mono and gecko installers appeared. reason: wine coaches the installers, so they don't appear after installing first time.

Interesting. That looks like something we'll want to clear upon installation then. Right?

> it gets removed in case there is a broken wine prefix there, so you get a new one. I think it's necessary, even though it will be a pain when updating.

Would it be possible to detect a "broken wine prefix"? If so, that would seem like the best of both worlds.

**Comment by Itai-Nelken** [comment] 2020-12-28 18:25
> > > What category should winecfg go in? Let's not leave it in `Other`.
> > 
> > 
> > maybe Games? I don't know.
> 
> I'm thinking of putting it in System Tools.

sounds good. 
> > @Botspot I just cleared wine's cache (delete `~/.cache/wine`) and tried this zip [Wine.x86.zip](https://github.com/Botspot/pi-apps/files/5745193/Wine.x86.zip), and the wine mono and gecko installers appeared. reason: wine coaches the installers, so they don't appear after installing first time.
> 
> Interesting. That looks like something we'll want to clear upon installation then. Right?
yes, also uninstallation.

also I have a problem with wine (TwisterOS, and using this script) that it just stops working. you can install apps and run some of them from the installer, but everything else doesn't work.

also we need to add wine to the hidelist in TwsiterOS.

**Comment by Itai-Nelken** [comment] 2020-12-28 18:27
> > it gets removed in case there is a broken wine prefix there, so you get a new one. I think it's necessary, even though it will be a pain when updating.
> 
> Would it be possible to detect a "broken wine prefix"? If so, that would seem like the best of both worlds.

If its possible than yes, it would be the best.
after a quick google, I didn't find any way to detect a broken wine prefix.

**Comment by Itai-Nelken** [comment] 2020-12-29 10:01
in TwisterOS, `/usr/local/bin/wine` is this script:
```sh
#!/bin/bash
setarch linux32 -L /home/pi/wine/bin/wine "$@"
```
maybe we should use it?

**Comment by Itai-Nelken** [comment] 2020-12-29 11:34
there is also this:
add this line
`application/x-ms-dos-executable=userapp-"wine"-9GU8V0.desktop;`

To this file right at the end of the list for added associations right above default applications 
`/home/pi/.config/mimeapps.list`

This will let you just double click .exe files to open them

**Comment by Botspot** [comment] 2020-12-29 15:46
Nice finds, @Itai-Nelken!

**Comment by Botspot** [comment] 2020-12-29 15:56
@Itai-Nelken Could you find where the wine desktop file is?
```
find / -name 'userapp-"wine"-9GU8V0.desktop'
```
I want to see what that file contains.

**Comment by Itai-Nelken** [comment] 2020-12-29 16:17
@Botspot that command comes up with a long list:
[output.txt](https://github.com/Botspot/pi-apps/files/5751335/output.txt)

**Comment by Botspot** [comment] 2020-12-29 16:28
Looks like it couldn't find it. Strange.

**Comment by ilobilo** [comment] 2020-12-29 17:18
You can use **find / -path /sys -prune -o -path /proc -prune -o -name 'userapp-"wine"-9GU8V0.desktop'**
To exclude /sys and /proc directories. (But I haven't tried it)

**Comment by Botspot** [comment] 2020-12-29 17:19
> You can use **find / -path /sys -prune -o -path /proc -prune -o -name 'userapp-"wine"-9GU8V0.desktop'**
> To exclude /sys and /proc directories. (But I haven't tried it)

Or to simply hide errors, you can do `find / -name 'userapp-"wine"-9GU8V0.desktop' 2>/dev/null`. But I checked and the file isn't there. So there's no point.

**Comment by Botspot** [comment] 2020-12-30 19:55
Wow this looks really promising! https://discord.com/channels/670543161525010442/700827603623346278/758440669600940072

**Comment by Itai-Nelken** [comment] 2020-12-30 19:58
@Botspot that is what I based my original script on. but winetricks never ran inside the script.

**Comment by Botspot** [comment] 2021-01-01 04:48
[Wine (x86).zip](https://github.com/Botspot/pi-apps/files/5758642/Wine.x86.zip)
I've made a large number of changes to this, and have gotten winetricks working.

> in TwisterOS, `/usr/local/bin/wine` is this script:
> ```shell
> #!/bin/bash
> setarch linux32 -L /home/pi/wine/bin/wine "$@"
> ```

Interesting. I've tried doing that on RPiOS, but it didn't seem to work.

**Comment by Itai-Nelken** [comment] 2021-01-01 07:22
I tried your zip in vdesktop and it failed just after finishing to install wine gecko. I'll try again not with vdesktop later.

**Comment by Itai-Nelken** [comment] 2021-01-02 21:30
@Botspot I don't think it can be in the installer, but maybe add it to the description that if you get errors similar to `file not found` when running apps (installed with wine) ru `wine boot -u`, that should fix it.

**Comment by Itai-Nelken** [comment] 2021-01-06 17:02
I think we should add this, makes the experience way better (just added to TwisterOS, and it works really well. It also helps with shortcut icons I think).

```
add this line
`application/x-ms-dos-executable=userapp-"wine"-9GU8V0.desktop;`

To this file right at the end of the list for added associations right above default applications 
`/home/pi/.config/mimeapps.list`

This will let you just double click .exe files to open them

and this:
You can also do this to see .exe icons. Looks nice especially if you're on an older windows theme like Raspbian 95 or Raspbian XP.
```sh
sudo pip3 install icoextract
wget https://raw.githubusercontent.com/jlu5/icoextract/master/exe-thumbnailer.thumbnailer && sudo mv exe-thumbnailer.thumbnailer /usr/share/thumbnailers/
```
reboot for thumbnailer to work
```

**Comment by Botspot** [comment] 2021-01-06 20:23
The thumbnailer appears to only work with Thunar file manager. It's useless on pcmanfm.

**Comment by Itai-Nelken** [comment] 2021-01-06 21:00
we can still do the double click exe to open with wine thing though (I hope so at least):
add this line
application/x-ms-dos-executable=userapp-"wine"-9GU8V0.desktop;

To this file right at the end of the list for added associations right above default applications
/home/pi/.config/mimeapps.list

**Comment by Itai-Nelken** [comment] 2021-01-06 21:02
also what about detecting if user has thunar installed, and if yes install thumbnailer.

**Comment by Botspot** [comment] 2021-01-07 02:08
> we can still do the double click exe to open with wine thing though (I hope so at least):
> add this line
> application/x-ms-dos-executable=userapp-"wine"-9GU8V0.desktop;
> 
> To this file right at the end of the list for added associations right above default applications
> /home/pi/.config/mimeapps.list

That requires there being a file somewhere called `userapp-"wine"-9GU8V0.desktop`. If no such file exists, then adding this line to mimeapps.list won't do anything.

> also what about detecting if user has thunar installed, and if yes install thumbnailer.

Good idea. Let's have it detect if the thunar executable exists. Where is it on your system, @Itai-Nelken? (run `whereis thunar`)

**Comment by Itai-Nelken** [comment] 2021-01-07 15:16
@Botspot 
```
pi@Twisterpi4-ultra-4gb:~ $ grep -r '9GU8V0' / 2>/dev/null
/var/log/auth.log.1:Dec 29 18:11:53 Twisterpi4-ultra-4gb sudo:       pi : TTY=pts/1 ; PWD=/home/pi ; USER=root ; COMMAND=/usr/bin/find / -name userapp-"wine"-9GU8V0.desktop
/var/log/auth.log.1:Dec 29 18:13:39 Twisterpi4-ultra-4gb sudo:       pi : TTY=pts/1 ; PWD=/home/pi ; USER=root ; COMMAND=/usr/bin/find / -name userapp-"wine"-9GU8V0.desktop
Binary file /proc/24114/task/24114/cmdline matches
Binary file /proc/24114/cmdline matches
/home/pi/.bash_history:find / -name 'userapp-"wine"-9GU8V0.desktop'
/home/pi/.bash_history:sudo find / -name 'userapp-"wine"-9GU8V0.desktop'
/home/pi/.bash_history:find / -name 'userapp-"wine"-9GU8V0.desktop'
/home/pi/.bash_history:sudo find / -name 'userapp-"wine"-9GU8V0.desktop'
/home/pi/.bash_history:find / -path /sys -prune -o -path /proc -prune -o -name 'userapp-"wine"-9GU8V0.desktop
/home/pi/.bash_history:find / -path /sys -prune -o -path /proc -prune -o -name 'userapp-"wine"-9GU8V0.desktop'
/home/pi/.bash_history:find / -name 'userapp-"wine"-9GU8V0.desktop' 2>/dev/null
Binary file /home/pi/.config/discord-nativefier-18566a/Local Storage/leveldb/000012.log matches
pi@Twisterpi4-ultra-4gb:~ $ 
```

**Comment by Botspot** [comment] 2021-01-10 01:07
@Itai-Nelken Unfortunately, none of those search results are valid.

One more thing before it's added: we need this app to deal with Pi3 users. To run on a Pi3, WINE needs  a 3G/1G kernel.
Or WINE needs to be compiled for a 2G/2G kernel.

One of the two. Pick your poison. ;)

**Comment by Itai-Nelken** [comment] 2021-01-15 15:46
> One more thing before it's added: we need this app to deal with Pi3 users. To run on a Pi3, WINE needs a 3G/1G kernel.
> Or WINE needs to be compiled for a 2G/2G kernel.
> 
> One of the two. Pick your poison. ;)

I have no idea, do whatever you think is better, or just add pi3 detection.

**Comment by Itai-Nelken** [comment] 2021-01-15 15:46
> One more thing before it's added: we need this app to deal with Pi3 users. To run on a Pi3, WINE needs a 3G/1G kernel.
> Or WINE needs to be compiled for a 2G/2G kernel.
> 
> One of the two. Pick your poison. ;)

@Botspot I have no idea, do whatever you think is better, or just add pi3 detection and hide it on pi3's.

**Comment by techcoder20** [comment] 2021-01-21 03:22
@Botspot @Itai-Nelken This issue has been open for a long time. Can I help in any way ?

**Comment by Botspot** [comment] 2021-01-21 15:41
> @Botspot @Itai-Nelken This issue has been open for a long time. Can I help in any way ?

Yes. It's ready, but needs a solution for Pi 3 devices. I've installed WINE on a Pi3 before - it involved **compiling the kernel** with a 3G/1G memory split.  

We just need to find someone who's willing to regularly compile the kernel for the Pi3. See: https://www.raspberrypi.org/forums/viewtopic.php?f=29&t=298165&p=1795179&hilit=wine#p1795179

**Comment by Itai-Nelken** [comment] 2021-01-22 18:52
@Botspot I'll compile the rpi kernel for Pi 2, Pi 3, Pi 3+, CM 3 for now, and I'll huess I'll need to compile it again every time a new release is released.

**Comment by Itai-Nelken** [comment] 2021-01-22 21:40
@Botspot 
rpi 2,3,3+,cm3 kernel 3G/2G: https://drive.google.com/file/d/1I5rzyLUylCKkpnVAEVbXT9003um4Eu2s/view?usp=sharing
**installation instructions:**
```
export KERNEL=kernel7
sudo make modules_install
sudo cp arch/arm/boot/dts/*.dtb /boot/
sudo cp arch/arm/boot/dts/overlays/*.dtb* /boot/overlays/
sudo cp arch/arm/boot/dts/overlays/README /boot/overlays/
sudo cp arch/arm/boot/zImage /boot/$KERNEL.img
```

rpi kernel building documentation: https://www.raspberrypi.org/documentation/linux/kernel/building.md

**Comment by Itai-Nelken** [comment] 2021-01-24 14:16
anyone has a pi3 and wants to help test?
@Botspot is the kernel I compiled above ok?

**Comment by slashtechno** [comment] 2021-01-28 16:08
Is it possible for Pi-Apps to detect what device you are using and if you are using a compatible device you can install Wine? That way the majority of users can use Wine.

Also in the description of Wine in Pi-Apps can there be a quick tutorial?

**Comment by Botspot** [comment] 2021-01-30 01:10
Detection is underway on my end.

Kernel building instructions can be found here: https://gist.github.com/MIvanchev/14de59fa2552d315ac74c30cf1c0b01e#configuring-a-3g1g-vm-split-32-bit-distros-only

**Comment by Itai-Nelken** [comment] 2021-01-31 15:08
@Botspot Great job on the wine script!
I have a suggestion: in the part where the script asks you if you want to change to 64bit kernel or compile the linux kernel, why not add another option that asks you if you want to install a precompiled version but it might be outdated?
I can compile the RPi kernel every month if needed.

**Comment by Botspot** [comment] 2021-02-01 04:41
> @Botspot Great job on the wine script!
> I have a suggestion: in the part where the script asks you if you want to change to 64bit kernel or compile the linux kernel, why not add another option that asks you if you want to install a precompiled version but it might be outdated?
> I can compile the RPi kernel every month if needed.

Good idea. Could you create a github repository to host the kernel files?

**Comment by Itai-Nelken** [comment] 2021-02-01 06:05
> Good idea. Could you create a github repository to host the kernel files?

yes. here: https://github.com/Itai-Nelken/RPi-3g-1g-kernel-wine
the files still are not there though.

**Comment by Itai-Nelken** [comment] 2021-02-01 07:06
@Botspot do you know how can I upload big files to github?
the website has a 25mb limit and `git push` fails and says the file is to large.
should I just use the releases?

**Comment by Itai-Nelken** [comment] 2021-02-01 08:25
I will use the releases, here is the frst one: https://github.com/Itai-Nelken/RPi-3g-1g-kernel-wine/releases/tag/1

**Comment by Botspot** [comment] 2021-02-01 13:42
> should I just use the releases?

Yes, if any single file is larger than 100mb.

**Comment by Itai-Nelken** [comment] 2021-02-01 13:46
> > should I just use the releases?
> 
> Yes, if any single file is larger than 100mb.

ok, then that is what I'll keep using.
BTW is what I uploaded to the [repo](https://github.com/Itai-Nelken/RPi-3g-1g-kernel-wine) ok?

**Comment by Botspot** [comment] 2021-02-01 17:49
Added to Pi-Apps with commit ba768d5d8a0f931dc0490fc4b96ff9352f774e1b.

**Closed by Botspot** 2021-02-01 17:49 UTC
Labels: App Request, Testers wanted

**Comment by Itai-Nelken** [comment] 2021-02-01 18:33
> > > should I just use the releases?
> > 
> > 
> > Yes, if any single file is larger than 100mb.
> 
> ok, then that is what I'll keep using.
> BTW is what I uploaded to the [repo](https://github.com/Itai-Nelken/RPi-3g-1g-kernel-wine) ok?

will you use that? if yes I think the issue should stay open untill a prebuilt kernel option for pi3 is added.

**Comment by Itai-Nelken** [comment] 2021-02-02 20:57
@Botspot are you working on adding the prebuilt kernel option or can I (try to) add it?

**Comment by Botspot** [comment] 2021-02-02 21:23
> @Botspot are you working on adding the prebuilt kernel option or can I (try to) add it?

I've not yet had a large enough chunk of time to get it done.  
You're more than welcome to help! :)

**Comment by Itai-Nelken** [comment] 2021-02-03 09:41
should the we backup the kernel before compiling/installing pre-compiled and make the uninstall script restore the old kernel?
