### ISSUE TITLE
Minecraft java install error on 64-bit PiOS

### ISSUE THREAD

**Issue by premkubade** [Botspot/pi-apps#235] opened 2021-01-13 04:40 UTC
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|151.101.12.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 3693924 (3.5M) [application/octet-stream]
lwjgl3arm64.tar.gz: No such file or directory

Cannot write to ‘lwjgl3arm64.tar.gz’ (No such file or directory).
Failed to install the launcher!

Failed to install Minecraft Java with install-64 script!

Close this window to exit.

**Comment by Botspot** [comment] 2021-01-16 16:07
Unfortunately I've not been able to reproduce this.

@premkubade Could you try it again and see if maybe you had a faulty Internet connection?

**Comment by CoderLogy** [comment] 2021-01-16 16:45
Which version of Pi do u have 
Pls tell #224

**Comment by CoderLogy** [comment] 2021-01-16 16:46
Which version of Pi do u have

**Comment by Botspot** [comment] 2021-01-21 20:57
Closing this issue because OP failed to respond.

**Closed by Botspot** 2021-01-21 20:57 UTC
