### ISSUE TITLE
need help with internet error

### ISSUE THREAD

**Issue by udhgu** [Botspot/pi-apps#2616] opened 2024-07-07 14:04 UTC
### Confirmations

- [X] I searched for similar bug reports in https://github.com/Botspot/pi-apps/issues and found none were relevant.
- [X] I tried updating Pi-Apps and the issue is still not fixed. [How to update Pi-Apps?](https://pi-apps.io/wiki/getting-started/updating-pi-apps/)
- [X] IMPORTANT: I promise to respond to comments on this issue and write a good bug report https://www.softwaretestinghelp.com/how-to-write-good-bug-report/

### What happened?

box86 won't install

### Description

when i click install box86 button,this failing message was appeared.i tried many times

### What are your system specs (run the following command in your terminal)?

```bash
OS: Raspbian GNU/Linux 12 (bookworm)
OS architecture: 32-bit
Last updated Pi-Apps on: 07/07/2024
Latest Pi-Apps version: 07/07/2024
Kernel: aarch64 6.6.31+rpt-rpi-v8
Device model: Raspberry Pi 5 Model B Rev 1.0
SOC identifier: bcm2712
Cpu name: Cortex-A76
Ram size: 3.98 GB
Raspberry Pi OS image version: 2024-03-15
Language: en_US.UTF-8
```

### (Recommended) Error log? Terminal output? Debug messages?

```bash
BEGINNING OF LOG FILE:
-----------------------
gpg: no valid OpenPGP data found.
add_external_repo: pubkeyurl isn't a valid link

Failed to install Box86!
◢◣Need help? Copy the ENTIRE terminal output or take a screenshot.
Please ask on Github: https://github.com/Botspot/pi-apps/issues/new/choose
Or on Discord: https://discord.gg/RXSTvaUvuu
```

**Comment by theofficialgman** [comment] 2024-07-08 18:26
this is not a bug but an internet error on your end (or your ISP)

the following URL must be accessible by wget in order to add and use the box86 debian repo
```
https://pi-apps-coders.github.io/box86-debs/KEY.gpg
```

**Comment by theofficialgman** [comment] 2024-07-26 20:16
Closing as there is nothing more we can do for you here.

**Closed by theofficialgman** 2024-07-26 20:16 UTC
Labels: User Error
