### ISSUE TITLE
osu!

### ISSUE THREAD

**Issue by everypizza1** [Botspot/pi-apps#2402] opened 2023-07-26 21:22 UTC
### What is the name of the app?

osu!

### (Optional) Where is the app hosted?

https://github.com/ppy/osu/#running-osu

### About the app

osu! is one of my favorite rhythm games. I would like a way to run it on the pi.

### Confirmations

- [X] I have confirmed that this app is legal and not piracy.
- [X] I have read the app eligibilty rubric https://github.com/Botspot/pi-apps/issues/185 and confirmed this app is suitable for addition in Pi-Apps.
- [X] I have confirmed that this app has never been discussed in https://github.com/Botspot/pi-apps/issues and https://github.com/Botspot/pi-apps/pulls, and it is not in the Pi-Apps app list.
- [X] I have confirmed that this app can run on Raspberry Pi.

**Comment by theofficialgman** [comment] 2023-07-26 21:56
you read this yet are still still opening an app request?
```
All of the following MUST be met. If you can NOT check one of these boxes. Then do NOT create a GitHub Issue. We will close it. The checkboxes are made a requirement on purpose.
```
closing as stated

**Closed by theofficialgman** 2023-07-26 21:56 UTC
Labels: App Request

**Comment by everypizza1** [comment] 2023-07-27 12:19
> you read this yet are still still opening an app request?
> 
> > All of the following MUST be met. If you can NOT check one of these boxes. Then do NOT create a GitHub Issue. We will close it. The checkboxes are made a requirement on purpose.
> 
> 
> closing as stated

Couldn't we run the Linux build with box64?

**Comment by GYKgamer** [comment] 2024-01-22 22:31
So i've been building Osu! and i'm just stuck on an error about "/lib/aarch64-linux-gnu/libc.so: invalid ELF header" and i've been stuck on this error for quite some time, I don't know what to do now so i'm just going to post what i've done so far. My recording is not perfect because it was made so that is was the most simplest to understand. It should be enough to reproduce what i've done.
[what i did.txt](https://github.com/Botspot/pi-apps/files/14016139/what.i.did.txt)

**Comment by GYKgamer** [comment] 2024-01-22 22:37
You could, I used windows to build it into arm64

**Comment by GYKgamer** [comment] 2024-01-31 18:03
![image](https://github.com/Botspot/pi-apps/assets/41442793/7b04a24a-af2e-418f-afbc-94dd7d1898ed)
I don't think this is how my libc.so file should look like

**Comment by GYKgamer** [comment] 2024-02-01 23:25
I have successfully built osu! for the raspberry pi and have gotten it running (between 15 - 40fps)
In maps it is playable, though unknown about the mouse as I was using vnc and the mouse was going places
[what i did.txt](https://github.com/Botspot/pi-apps/files/14132121/what.i.did.txt)
![image](https://github.com/Botspot/pi-apps/assets/41442793/ef07f068-a44b-4dc7-a835-8a5bba1e0378)

**Comment by everypizza1** [comment] 2024-02-01 23:42
I haven't been using the Pi much as I now am using a primary desktop. I don't think it would be a good experience, considering it's lagging on a i5-4590.


________________________________

**Comment by GYKgamer** [comment] 2024-02-01 23:50
Are you using full screen? Cause thats most likely the issue, that's why I have the game automatically set to 640x480 windowed and that's how I get the better fps.

**Comment by everypizza1** [comment] 2024-02-01 23:59
I've heard that windowed increases input lag.


________________________________

**Comment by GYKgamer** [comment] 2024-02-02 11:12
@theofficialgman this look good?
