### ISSUE TITLE
Failed to install Firefox Rapid Release with install script!

### ISSUE THREAD

**Issue by directorcrow** [Botspot/pi-apps#846] opened 2021-07-25 23:20 UTC
I do not know much but this happened.
![2021-07-25-181402_1280x720_scrot](https://user-images.githubusercontent.com/86080574/126916569-ab27c59d-973c-4d19-81f6-be10e2b75455.png)

**Comment by Botspot** [comment] 2021-07-25 23:26
This issue was caused by a typo in the installation script. The typo has now been fixed with commit https://github.com/Botspot/pi-apps/commit/625e12ade6ad1f4d311b053f66a4ea3f0bcdc83a.

**Closed** 2021-07-25 23:25 UTC

**Comment by directorcrow** [comment] 2021-07-25 23:28
Thanks, good work :)
