### ISSUE TITLE
Genymotion

### ISSUE THREAD

**Issue by rbcoder117** [Botspot/pi-apps#1836] opened 2022-05-18 01:27 UTC
### What is the name of the app?

Gennymotion

### About the app

An Android emulator

### Confirmations

- [X] I have confirmed that this app is legal and not piracy.
- [X] I have confirmed that this app has never been discussed in https://github.com/Botspot/pi-apps/issues and https://github.com/Botspot/pi-apps/pulls, and it is not in the Pi Apps app list.
- [x] I have confirmed that this app can run on Raspberry Pi.

**Comment by ryanfortner** [comment] 2022-05-18 01:36
This request is lacking a few important details. 

1. You didn’t provide a link to the software, so we can’t be sure what you’re talking about. 
2. The android emulator Genymotion, which I’m assuming you are referring to, is paid software, which Pi-Apps does not include. Is there a trial version?
3. You clicked the “I have confirmed this app can run on a Raspberry Pi” check box, though you didn’t provide any instructions as to run the software. 

Please provide some more information so that we can assist you.

**Comment by rbcoder117** [comment] 2022-05-18 02:59
Ok tomarow i have to go to bed rn

**Comment by Crilum** [comment] 2022-05-18 06:16
@ryanfortner You don't have to pay to use GenyMotion, if it's for personal use, as far as I'm aware..

I've used it on an `amd64` linux box for free.

**Comment by Crilum** [comment] 2022-05-18 06:18
In order to use GenyMotion, you have to install VirtualBox, which will be a rabbit-hole.. It's not installable on a Raspberry Pi, as far as I can tell.

**Comment by rbcoder117** [comment] 2022-05-18 21:52
Yes @Crilum is correct the download links here https://www.genymotion.com/download/
ill unpack later today. @ryanfortner

**Comment by Crilum** [comment] 2022-05-19 16:47
From the downloads page:
```
System Requirements

Ubuntu 20.04LTS (Focal Fossa) - 64bit only
Debian 9 (Stretch) or above - 64bit only
Fedora 30 or above - 64bit only
x86_64 CPU, with Intel VT-x/AMD-V/SVM
Hardware accelerated GPU
400 MB disk space
4GB RAM
VirtualBox from your distribution
```

So to install this, you'd need to have installed VirtualBox running inside of Box64, and then try to install GenyMotion, which requires `Intel VT-x/AMD-V/SVM`, which I don't think ARM processors have (or Box64 can emulate).

**Comment by theofficialgman** [comment] 2022-05-21 03:09
closing due to needless complexity needed to install. if you need an android dev system, just actually run android on the pi. This software is very designed for running on x86_64 hardware, and even if you could get it to run, you would be running through THREE emulation layers. arm64 linux -> x86_64 linux -> android x86_64 -> android arm64 (if it does that)

**Closed by theofficialgman** 2022-05-21 03:09 UTC
Labels: App Request
