### ISSUE TITLE
Pi Apps moved to preferences?

### ISSUE THREAD

**Issue by steveiliop56** [Botspot/pi-apps#2387] opened 2023-07-11 15:26 UTC
Hello,

Today I formated my raspberry pi and then installed pi-apps with these commands:

```Shellscript
git clone https://github.com/Botspot/pi-apps
mv pi-apps/ .pi-apps/
~/.pi-apps/install
```

While the install worked the pi-apps app appeared in the Preferences section rather than the Accessories one. I tried uninstalling and reinstalling 2 times and I had the same result. So did pi-apps change location?

**Comment by Botspot** [comment] 2023-07-11 16:50
Hello @steveiliop56, yes this is a known issue.
It was a mistake caused by @theofficialgman's recent commit https://github.com/Botspot/pi-apps/commit/7e381a2ef769e56873197b7683972e7c6ea312da
I've asked him to fix it in a way that it solves the problem he was having, while avoiding moving the pi-apps launcher to Preferences on PiOS.

**Comment by steveiliop56** [comment] 2023-07-11 16:51
So it's a bug and it will be fixed in the next update?

**Comment by Botspot** [comment] 2023-07-11 16:54
> So it's a bug and it will be fixed in the next update?

It's a bug and will be fixed soon. If @theofficialgman does not get to it today, then I will fix it myself.

**Comment by theofficialgman** [comment] 2023-07-11 16:57
Will look into it this afternoon local time.

**Comment by theofficialgman** [comment] 2023-07-11 20:49
piOS uses the LXDE desktop environment by default. the default categories are controlled by the XML found in `/etc/xdg/menus/lxde-pi-applications.menu`

read the below contents you will find that the accessories submenu is generated based on applications that have a category that contains `Utility and NOT (Accessibility OR System)`

after the help menu there is a `DesktopSettings` menu which I believe is the `Preferences` menu (it is strange because in the XML it is named differently. This menu is generated last and contains only categories `(Settings OR PackageManager OR System)` that were not already allocated above.

Since pi-apps currently uses `Categories=Utility;System;PackageManager;` it failed the Accessories submenu checks so DesktopSettings` picked it up due to System and PackageManager existing.

kde discover: `Categories=Qt;KDE;System;`
gnome software: `Categories=GNOME;GTK;System;PackageManager;`
synaptic package manager: `Categories=PackageManager;GTK;System;Settings;`
snap store: `Categories=GNOME;GTK;System;PackageManager;`

Given this information, it is impossible to have pi-apps reside in the Accessories category as it used to do. It also should not reside in the Accessories category as that would make it different from ALL other software stores (kde discover, gnome software, snap store, synaptic package manager, Add / Remove Software) which will reside in the `DesktopSettings` (preferences) category. I am content on leaving it how it is now @Botspot since it is show it always should have been in the first place. Old users will find it and new users will likely look there first anyway.

I am perfectly find with the risks as outlined here

> Maybe it would have been fine if pi-apps was always in Preferences from day 1, but it is be unfair to our users to change it now without warning. This breaks all the tutorials, videos, muscle memory, etc. TBH, when I noticed this, I first thought I broke something and then wondered if something ran the pi-apps uninstall script.

I can add a popup dialog that automatically closs to warn the users, that is easy and a good idea.

the file that a referenced earlier:
```
<!DOCTYPE Menu PUBLIC "-//freedesktop//DTD Menu 1.0//EN"
 "http://www.freedesktop.org/standards/menu-spec/1.0/menu.dtd">

<Menu>

	<Name>Applications</Name>
	<Directory>lxde-menu-applications.directory</Directory>

	<!-- Read standard .directory and .desktop file locations -->
	<DefaultAppDirs/>
	<DefaultDirectoryDirs/>

	<!-- Read in overrides and child menus from applications-merged/ -->
	<DefaultMergeDirs/>

	<!-- Debian menu -->
	<Menu>
		<Name>Debian</Name>
		<Directory>lxde-debian.directory</Directory>
		<MergeFile>debian-menu.menu</MergeFile>
	</Menu>

	<!-- Accessories submenu -->
	<Menu>
		<Name>Accessories</Name>
		<Directory>lxde-utility.directory</Directory>
		<Include>
			<And>
				<Category>Utility</Category>
	<!-- Accessibility spec must have either the Utility or Settings
			 category, and we display an accessibility submenu already for
			 the ones that do not have Settings, so don't display accessibility
			 applications here -->
				<Not><Category>Accessibility</Category></Not>
				<Not><Category>System</Category></Not>
			</And>
		</Include>
	</Menu> <!-- End Accessories -->

	<!-- Accessibility submenu -->
	<Menu>
		<Name>Universal Access</Name>
		<Directory>lxde-utility-accessibility.directory</Directory>
		<Include>
			<And>
				<Category>Accessibility</Category>
				<Not><Category>Settings</Category></Not>
			</And>
		</Include>
	</Menu> <!-- End Accessibility -->

	<!-- Development Tools -->
	<Menu>
		<Name>Development</Name>
		<Directory>lxde-development.directory</Directory>
		<Include>
			<And>
				<Category>Development</Category>
			</And>
			<Filename>emacs.desktop</Filename>
		</Include>
	</Menu> <!-- End Development Tools -->

	<!-- Education -->
	<Menu>
		<Name>Education</Name>
		<Directory>lxde-education.directory</Directory>
		<Include>
			<And>
				<Category>Education</Category>
			</And>
		</Include>
	</Menu> <!-- End Education -->

	<!-- Games -->
	<Menu>
		<Name>Games</Name>
		<Directory>lxde-game.directory</Directory>
		<Include>
			<And>
				<Category>Game</Category>
			</And>
		</Include>
	</Menu> <!-- End Games -->

	<!-- Graphics -->
	<Menu>
		<Name>Graphics</Name>
		<Directory>lxde-graphics.directory</Directory>
		<Include>
			<And>
				<Category>Graphics</Category>
				<Not><Category>Utility</Category></Not>
			</And>
		</Include>
	</Menu> <!-- End Graphics -->

	<!-- Internet -->
	<Menu>
		<Name>Internet</Name>
		<Directory>lxde-network.directory</Directory>
		<Include>
			<And>
				<Category>Network</Category>
			</And>
		</Include>
	</Menu>	 <!-- End Internet -->

	<!-- Multimedia -->
	<Menu>
		<Name>Multimedia</Name>
		<Directory>lxde-audio-video.directory</Directory>
		<Include>
			<And>
				<Category>AudioVideo</Category>
			</And>
		</Include>
	</Menu>	 <!-- End Multimedia -->

	<!-- Office -->
	<Menu>
		<Name>Office</Name>
		<Directory>lxde-office.directory</Directory>
		<Include>
			<And>
				<Category>Office</Category>
			</And>
		</Include>
	</Menu> <!-- End Office -->

	<!-- System Tools-->
	<Menu>
		<Name>System</Name>
		<Directory>lxde-system-tools.directory</Directory>
		<Include>
			<And>
				<Category>System</Category>
				<Not><Category>Settings</Category></Not>
				<Not><Category>PackageManager</Category></Not>
			</And>
		</Include>
	</Menu>	 <!-- End System Tools -->

	<!-- Other -->
	<Menu>
		<Name>Other</Name>
		<Directory>lxde-other.directory</Directory>
		<OnlyUnallocated/>
		<Include>
			<And>
				<Not><Category>Core</Category></Not>
				<Not><Category>Settings</Category></Not>
				<Not><Category>Screensaver</Category></Not>
			</And>
		</Include>
		</Menu> <!-- End Other -->

	<Menu>
		<Name>DesktopSettings</Name>
		<Directory>lxde-settings.directory</Directory>
		<OnlyUnallocated/>
		<Include>
			<Or>
				<Category>Settings</Category>
				<Category>PackageManager</Category>
				<Category>System</Category>
			</Or>
		</Include>
		<Layout>
			<Merge type="menus"/>
			<Merge type="files"/>
		</Layout>

	</Menu> <!-- End Settings -->

	<Layout>
		<Merge type="files"/>
		<Merge type="menus"/>
		<Separator/>
		<Menuname>DesktopSettings</Menuname>
	</Layout>

</Menu> <!-- End Applications -->
```

**Comment by steveiliop56** [comment] 2023-07-11 21:04
Could you maybe make a dialog to ask if the users want pi-apps in the Accessories menu or the Preferences one? Because for me I am used to it being in the Accessories menu and I believe that pi-apps is mostly a raspberry pi software accessory rather than just an other package manager... So what do you think?

**Comment by theofficialgman** [comment] 2023-07-11 21:19
> Could you maybe add a dialog to ask if the user wants pi-apps in the Accessories menu or the Preferences one? 

no I don't think thats going to be an option
> Because for me, I am used to it being in the Accessories menu and I believe that pi-apps is mostly a raspberry pi software accessory rather than just an other package manager...

I quote our about pages: `The most popular app store for Raspberry Pi computers. 100% open-source bash scripts (including the GUI).` and `Raspberry Pi App Store for Open Source Projects`. Its an app store, no doubt about that.

**Comment by theofficialgman** [comment] 2023-07-11 21:56
@Botspot I highly consider you re-read the comment here https://github.com/Botspot/pi-apps/issues/2387#issuecomment-1631490092 and please give feedback.

**Comment by Botspot** [comment] 2023-07-11 22:23
@steveiliop56, I have fixed this now. Next time you run pi-apps, it will then return to Accessories as it always has been.

> I have stated multiple times this was not intentional

I understand that and I believe you.

> @Botspot I highly consider you re-read the comment here [#2387 (comment)](https://github.com/Botspot/pi-apps/issues/2387#issuecomment-1631490092) (or read it if you haven't already) and please give feedback on what problems you have with each solution and reason I have outlined.

The reason comes down to three things:
1. Pi-Apps has always been in Accessories. Any reason for moving it would need to be a very good reason. (And we would need to discuss it internally, request opinions from users, let everybody vote on it, etc.)
2. Pi-Apps has always been solving a different problem than an ordinary app store. It is best known for making hard-to-install apps easy to install (with the caveat for package-apps explained in the app eligibility rubric). Pi-Apps is not intended to be the only way for installing apps on a system, unless the user's needs are minimal. It should be more thought of as a little "upgrade service", a way to get ARM versions of apps that are lacking in some way from the normal sources.
3. Building on the above reason, I consider Pi-Apps to be closer in scope to PiKISS and PiGro, both of which are **not** in Preferences. (PiKISS is in System Tools and PiGro is in Accessories)
4. For most of our users who only use Pi-Apps for installing a couple of things, it makes more sense to say "I found this **little tool** which easily installs Minecraft," than to say "I found an entire app store to install one app that I couldn't find anywhere else."

> Rather than piOS being the odd one out and having it appear under a totally different category than its software store siblings.

Yes, I agree that my compromise to place Pi-Apps in Preferences if the PiOS desktop modifications are missing, is not an ideal compromise for that reason. We can discuss that further, add a notification dialog, make it changeable in pi-apps settings, etc. But for now I just wanted at least Pi-Apps installations on PiOS to be changed back right now, allowing ample time to work out a more permanent solution afterwards.

**Comment by theofficialgman** [comment] 2023-07-11 22:57
> The reason comes down to four things:
> 
> 1. Pi-Apps has always been in Accessories. Any reason for moving it would need to be a very good reason. (And we would need to first discuss it internally, request opinions from users, let everybody vote on it, explain the change to users, etc.)

A vote seems like a good idea but in practice I don't think it will give us much info. Most users use pi-apps once and never join our discord server or communicate on the github (as you mention below).

> 3. Building on the above reason, I consider Pi-Apps to be closer in scope to PiKISS and PiGro, both of which are **not** in Preferences. (PiKISS is in System Tools and PiGro is in Accessories)

I understand they are in different locations. However I think thats probably by accident or, in the case of pi-kiss gui, because they wanted to match pi-apps location (the fork of pi-kiss gui that we use came out after pi-apps and is made by one of our contributors).

> 4. For most of our users who only use Pi-Apps for installing a couple of things (IIRC the average was 3 apps per pi-apps download), it makes more sense to say "I found this **little tool** which easily installs Minecraft," than to say "I found **an entire app store** to install one app that I couldn't find anywhere else."

Along these lines, incase you haven't noticed, I have been making subtle changes to try to increase our "retention" or "useage" rates among our users. I have noticed for a long time that even for very popular applications their "update" clicks are SIGNIFICANTLY lower than their "install" clicks, even for applications that get updated frequently. With an active userbase and an app that gets updated frequently you would expect the "update" clicks to greatly exceed the "install" clicks.

So I have concluded their either:
A: users don't realize they need to update their applications (hence why I made this change https://github.com/Botspot/pi-apps/pull/2386/commits/e2b5c4f7cfae5d117bbe6505640fbc537754576d )
B: users install their applications, use them for a bit, then get board, and don't use their systems anymore for running that software

> Yes, I agree that my compromise (to place Pi-Apps in Preferences if the PiOS desktop modifications are missing), is not an ideal compromise for that reason. We can discuss that further, add a notification dialog, make it changeable in pi-apps settings, etc. But for now I just wanted at least Pi-Apps installations on PiOS to be changed back right now, allowing ample time to work out a more permanent solution afterwards.

I'll be interested in revisiting it in the future.

**Comment by steveiliop56** [comment] 2023-07-12 06:52
Can confirm pi-apps is back, as it concerns about how much people use it whouldn't it be cool to make pi-apps as a .deb package so everytime a user updates his system pi-apps would get a new update script on what to update. Yeah for sure it would be a lot more complicated but I have to admit sometimes when I launch my os I am bored to wait 15 seconds or so for the terminal to pop up, update.... So an other solution could be either to run the update process in the background and only show the status window or you could create something like pi os updater that just has a small window in the center saying it's updating and process....

**Comment by Botspot** [comment] 2023-07-12 16:37
> Can confirm pi-apps is back, as it concerns how much people use it, whouldn't be cool to make pi-apps a .deb package so everytime a user updates the system pi-apps would get a new update script on what to update. Yeah for sure it would be a lot more complicated but I have to admit sometimes when I launch my os I am bored to wait 15 seconds or so for the terminal to pop up, update.... So an other solution could be either to run the update process in the background and only show the status window or you could create something like pi os updater that just has a small window in the center saying it's updating....

Pi-Apps itself could be a deb, but you would have to manually download the deb and install it (in order for `sudo apt install pi-apps` to work, I would have to persuade the RPi developers to add pi-apps to their official repositories)
The programs installed from pi-apps, however, follow a flexible script format which is very fluid compared to a deb file. It would not be possible to package all the apps into debs, so pi-apps would still need to update them in a terminal as always. 
@steveiliop56, would you prefer for pi-apps to start updating in a terminal without permission on startup?

**Comment by steveiliop56** [comment] 2023-07-12 16:42
I would basically prefer not to see the terminal part...

**Comment by theofficialgman** [comment] 2023-07-12 17:04
the terminal is there for your benefit. to see what is happening and respond to any terminal prompts that might be waiting for user input. without it there is no feedback to the user and we really can't provide any. it does not make sense to force all scripts to be rewritten to provide feedback via a GUI only.

also fyi, good apt updater show a terminal as well (the one called software updater does so, as does kde when there is a failure). pretty much this -> https://itsfoss.com/love-thy-terminal/

its much better to have a terminal window where you can see what is happening and actually diagnose issues. Have you ever been using windows and an app fails to launch or install and all you get is a cryptic error message with an error code that googling doesn't help with (if that, sometimes it just fails and you get no information). Did you like that experience? No, me neither. Having the terminal present showing all output during execution prevents all of those issues.

**Comment by steveiliop56** [comment] 2023-07-12 17:12
Yeahh you are right I was just thinking that in terms of not pooping up 2 windows to update which for users like me that use something like this: ![IMG-25205acba3b6a52ba0f28a7744bdd418-V.jpg](https://github.com/Botspot/pi-apps/assets/106091011/429e7df5-0241-4fc1-bee6-18658f1b85d1) with limited "desktop space", it would be fun to be able to hide the terminal and see a logfile if something went wrong.

**Comment by theofficialgman** [comment] 2023-07-12 17:15
> with limited "desktop space", it would be fun to be able to hide the terminal and see a logfile if something went wrong.

That's what the minimize button is for on every window.

**Comment by steveiliop56** [comment] 2023-07-12 17:18
Then no more taskbar space 🤣🤣🤣. So let's skip this part and as it concerns the reason of the entire issue (Pi Apps in Preferences), I think that you should create a poll in the discord server and ask users where they prefer to have pi-apps... Closing this issue...

**Closed** 2023-07-12 17:18 UTC
Labels: suggestion
