### ISSUE TITLE
Zoom not running on the raspberry pi 4

### ISSUE THREAD

**Issue by loudmusicpigeon** [Botspot/pi-apps#1038] opened 2021-10-11 13:40 UTC
Whenever i try to open zoom on the raspberry pi 4 i get the following message in the terminal in the terminal.
```
Box86 with Dynarec v0.2.3 1955c225 built on Oct 10 2021 00:04:24
zoom started.
Client: Breakpad is using Single Client Mode! client fd = -1
free(): invalid pointer
/home/pi/zoom/runzoom.sh: line 13: 14424 Aborted                 box86 zoom "$1"
Zoom exited. Close this terminal to exit
```
Zoom doesn't launch after this.
Anyone knows what mught be causing this?
I'm installing it from Pi Apps

**Comment by Itai-Nelken** [comment] 2021-10-11 14:28
There isn't anything pi-apps can do, it's a problem with either zoom or box86.

**Comment by cycool29** [comment] 2021-10-13 00:13
> Has anyone else been able to reproduce this?

Hmm what do you mean reproduce? 
Just launch from menu bar and it shows up the error message.

**Comment by anantmishra** [comment] 2021-12-15 16:09
Tried to install and run zoom and it failed to start. The box version installed is 0.2.5+20211212.a1aac43a-1

Interestingly, I managed to run the zoom with the version 0.2.3+20211003.b30a0717-1. This means the problem is with box86 and it has returned.

Has created a new ticket to track the same - #1271

**Comment by theofficialgman** [comment] 2022-02-03 04:26
issue was fixed in and other issue has been already closed

**Closed by theofficialgman** 2022-02-03 04:26 UTC
