### ISSUE TITLE
W-O-R not working

### ISSUE THREAD

**Issue by rbcoder117** [Botspot/pi-apps#1489] opened 2022-02-13 00:46 UTC
### Confirmations

- [X] I searched for similar bug reports in https://github.com/Botspot/pi-apps/issues and found none were relevant.
- [X] I tried updating Pi Apps and the issue is still not fixed. [How to update Pi Apps?](https://github.com/Botspot/pi-apps#to-update-pi-apps)

### What happened?

its not running the terminal

### Description

after getting to the last screen it will not launch the terminal.

### What is your operating system?

raspberry pi os

**Comment by Adarkk** [comment] 2022-02-13 04:06
Same thing

**Comment by Botspot** [comment] 2022-02-13 05:05
@rbcoder117 @Adarkk, which terminals do you currently have installed? Does the command `lxterminal` do anything?

Please run `~/wor-flasher/install-wor-gui.sh` inside a terminal to check for errors.

**Comment by Adarkk** [comment] 2022-02-13 05:18
@rbcoder117,  i use an standart raspbbery pi terminal  ,the terminal is work fine, so i can install some snap apps without problem  .
But the (pi apps ) isn't install as a normal , it take like 3  hours to install and in the end isn't open.

**Comment by Adarkk** [comment] 2022-02-15 05:48
Its fixed , now all its work

**Comment by Botspot** [comment] 2022-02-15 15:46
> Its fixed , now all its work

Well that's weird, because I didn't make any changes to WoR-Flasher recently that would have fixed a problem like this.
In any case, thank you for letting me know that the problem is solved. I will close the issue now.

**Closed by Botspot** 2022-02-15 15:46 UTC
Labels: bug
