### ISSUE TITLE
Telegram (app request)

### ISSUE THREAD

**Issue by Aradionov366** [Botspot/pi-apps#156] opened 2020-12-24 12:19 UTC
Yes, I know that you can install it using the command 'sudo install telegram-desktop', but the version you install will be too old, I would like to see a new version of this messenger. Thank you in advance :D

**Comment by Itai-Nelken** [comment] 2020-12-24 12:32
@Aradionov366 you can install it from snap (https://snapcraft.io/telegram-desktop there are armhf and arm64 versions), flatpak (https://flathub.org/apps/details/org.telegram.desktop not sure there are arm versions though) and if you can compile it yourself (https://github.com/telegramdesktop/tdesktop/blob/dev/docs/building-cmake.md) (as you said you can also install it with `sudo apt install telegram-desktop`).

I don't think that a app that's available on so many places can be on pi-apps

**Comment by Botspot** [comment] 2020-12-25 18:15
I still haven't decided on this. Issue will remain open until I make a decision.

**Comment by Botspot** [comment] 2020-12-27 23:29
It appears that you can install telegram via Flatpak:
```
sudo apt install flatpak
flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
flatpak install flathub org.telegram.desktop
```
To run:
```
/var/lib/flatpak/exports/share/applications/org.telegram.desktop.desktop
```
@Aradionov366, could you please compare the Flatpak version to the APT version and convince me that the Flatpak version is indeed better/necessary?

**Comment by Itai-Nelken** [comment] 2020-12-28 05:40
> It appears that you can install telegram via Flatpak:
> 
> ```
> sudo apt install flatpak
> flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
> flatpak install flathub org.telegram.desktop
> ```
> 
> To run:
> 
> ```
> /var/lib/flatpak/exports/share/applications/org.telegram.desktop.desktop
> ```
> 
> @Aradionov366, could you please compare the Flatpak version to the APT version and convince me that the Flatpak version is indeed better/necessary?

@Aradionov366 
reboot after installing flatpak, and the menu button will appear.
also if it doesn't, you can run using the command @Botspot sent, or this command:
```
flatpak run telegram-desktop
```

**Comment by Botspot** [comment] 2021-01-07 01:53
Closing this issue, as @Aradionov366 has not replied explaining **why** the `apt-get` version of Telegram is sub-optimal.

**Comment by fabianmendes** [comment] 2021-01-20 15:52
Please reopen this issue. Snap installation version has conflicts, also, Menu Icon is not set.
![2021-01-20-113335_800x480_scrot](https://user-images.githubusercontent.com/31230743/105199518-39f91c80-5b15-11eb-9ff7-8dd2bc9457cd.png)

Otherwise, I can't set it less than 100% such an annoying thing. Also, **I confirm** that it is _outdated_, there are messages that say you should install Telegram desktop because the message is not compatible with this version. :)
![2021-01-20-114516_800x480_scrot](https://user-images.githubusercontent.com/31230743/105200129-e2a77c00-5b15-11eb-952f-218de296114c.png)

**Comment by Botspot** [comment] 2021-03-08 16:37
@Itai-Nelken

**Comment by Itai-Nelken** [comment] 2021-03-08 16:51
> @Itai-Nelken Would an electron webapp be suitable for this?

why not? I'll make one.

**Comment by Itai-Nelken** [comment] 2021-03-08 17:21
@Botspot I just tested telegram web (that the nativefier app will use) and it lacks some features.

**Comment by Botspot** [comment] 2021-03-08 17:39
> @Botspot I just tested telegram web (that the nativefier app will use) and it lacks some features.

Any course of action, or is this a dead-end?

**Comment by Itai-Nelken** [comment] 2021-03-08 17:41
> > @Botspot I just tested telegram web (that the nativefier app will use) and it lacks some features.
> 
> Any course of action, or is this a dead-end?

its not really bad, just some things it can't display.
Ill try to compile the official desktop app.

**Comment by Itai-Nelken** [comment] 2021-03-08 17:56
@Botspot no luck, it needs some x86_64 software...
so or use a nativefier webapp that ios the same as using the website, or use the flatpak version, or don't add it (best option in my opinion as we don't want to add broken or half functioning apps).

**Comment by Botspot** [comment] 2021-03-08 18:13
> @Botspot no luck, it needs some x86_64 software...
> so or use a nativefier webapp that ios the same as using the website, or use the flatpak version, or don't add it (best option in my opinion as we don't want to add broken or half functioning apps).

Is the flatpak version somehow special? Or is it missing the same features as the electron app?

**Comment by Itai-Nelken** [comment] 2021-03-08 18:19
> > @Botspot no luck, it needs some x86_64 software...
> > so or use a nativefier webapp that ios the same as using the website, or use the flatpak version, or don't add it (best option in my opinion as we don't want to add broken or half functioning apps).
> 
> Is the flatpak version somehow special? Or is it missing the same features as the electron app?

Ill test it and see.

**Comment by Itai-Nelken** [comment] 2021-03-08 18:29
@Botspot the flatpak app looks like the official app, and it feels pretty snappy and fast.
![image](https://i.imgur.com/e96ZL71.png)
it even has a tray icon:
![image1](https://i.imgur.com/Gc7RS3e.png)
![image2](https://i.imgur.com/pJsWvFS.png)

**Comment by Itai-Nelken** [comment] 2021-03-08 18:30
its way better than the website.

**Comment by Itai-Nelken** [comment] 2021-03-08 18:32
just a note: you have to log out and back in or reboot for the desktop shortcuts to appear.
another way to fix that might be running `source ~/.bashrc` but I didn't try it and I doubt it will work.

**Comment by Botspot** [comment] 2021-03-08 18:35
> its way better than the website.

That settles it then. :)

**Comment by Itai-Nelken** [comment] 2021-03-08 18:41
> Then let's use the Flatpak app.

I'll make the scripts then.
something else: to install the flatpak app, flatpak needs to be installed obviously, so when uninstalling I think the script shouldn't remove flatpak in case the user installed any other flatpak apps.
what do you say?

**Comment by Botspot** [comment] 2021-03-08 19:02
> > Then let's use the Flatpak app.
> 
> I'll make the scripts then.
> something else: to install the flatpak app, flatpak needs to be installed obviously, so when uninstalling I think the script shouldn't remove flatpak in case the user installed any other flatpak apps.
> what do you say?

flatpak is an apt package, right? If so, then I'd say `pkg-install` is the best way to go. (So that if flatpak is installed prior, it will remain unchanged upon uninstalling Telegram)

**Comment by Itai-Nelken** [comment] 2021-03-08 19:07
>flatpak is an apt package, right?

what I mean is what will happen if the user installs flatpak apps after installing telegram from pi-apps. do you still think using `pkg-install` is the best way?

**Comment by Botspot** [comment] 2021-03-08 19:11
> > flatpak is an apt package, right?
> 
> what I mean is what will happen if the user installs flatpak apps after installing telegram from pi-apps. do you still think using `pkg-install` is the best way?

Oh I see what you mean. Yes there is a small chance of that exact scenario happening, as flatpak is a commonly used package.

I guess it wouldn't do harm to leave it installed. Use apt I guess.

**Comment by Itai-Nelken** [comment] 2021-03-08 19:11
bad news @Botspot, the app is really unstable, it crashed 3 times in a row when trying to read messages...
here is the output when running from terminal if someone wants it:
```bash
pi@twisterpi-4-4gb:~ $ flatpak run org.telegram.desktop
Gtk-Message: 21:09:26.531: Failed to load module "appmenu-gtk-module"
Qt: Session management error: Authentication Rejected, reason : None of the authentication protocols specified are supported and host-based authentication failed
error: : cannot open
error: : cannot open
error: : cannot open
[swscaler @ 0x9ef71510] No accelerated colorspace conversion found from yuv420p to bgra.
pi@twisterpi-4-4gb:~ $ 
```
the part with `swscaler @ 0x9ef71510]` is when it crashed.

**Comment by Itai-Nelken** [comment] 2021-03-08 19:34
(I won't create the scripts as it makes no sense because the app is so unstable)

**Comment by Botspot** [comment] 2021-03-08 19:38
> (I won't create the scripts as it makes no sense because the app is so unstable)

Understand. Before giving up though, could you try correcting the `Failed to load module "appmenu-gtk-module"` error?

Maybe fixing that will fix everything.

**Comment by Itai-Nelken** [comment] 2021-03-08 19:50
>Understand. Before giving up though, could you try correcting the Failed to load module "appmenu-gtk-module" error?
>
>Maybe fixing that will fix everything.

might try tomorrow.

**Comment by Itai-Nelken** [comment] 2021-04-11 21:37
this looks promising: https://forum.snapcraft.io/t/raspbery-pi-3b-chromium-error/18010/6
if we can get the snap version working we can use this, also maybe it will fix the flatpak version!

**Comment by Painadath** [comment] 2021-04-13 13:57
@Itai-Nelken is it possible to compile every web application like this

**Comment by Itai-Nelken** [comment] 2021-04-13 14:09
> @Itai-Nelken is it possible to compile every web application like this

@Painadath I don't understand, do you mean if we can compile it? If yes than no, the telegram desktop app has some x86_64 only dependencies.

**Comment by Itai-Nelken** [comment] 2021-04-17 09:23
@Botspot the errors the snap version gives can be fixed by commenting out this line in `/etc/ld.so.preload`:
```
/usr/lib/arm-linux-gnueabihf/libarmmem-${PLATFORM}.so
```
but its pretty outdated but I didn't have any problems with it so far. TBH I don't use telegram so much, so I have no idea if some things won't work.

I'll test later if this also fixes the flatpak version that is much newer.

**Comment by Itai-Nelken** [comment] 2021-04-17 11:35
the flatpak version is now working as well even without the fix!
but its older (v2.2) and the snap version is newer (v2.6) the newest is v2.7.
so I say we should go with the snap version. and the fix isn't needed, it works great so far without it.
![](https://i.imgur.com/ZV9TvRN.png)

**Comment by Itai-Nelken** [comment] 2021-04-24 15:41
this should work to install tdesktop (inside a pi-apps install script only):
```bash
if [[ ! -f "${DIRECTORY}/data/status/Snap Store" ]] && [[ $(cat "${DIRECTORY}/data/status/Snap Store") != "installed" ]]; then
	if ! command -v snap >/dev/null ; then
		${DIRECTORY}/manage install "Snap Store" || error "Failed to install snap store!"
	fi
else
	echo -e "\e[1mSnap is already installed...\e[0m"
fi
sudo snap install telegram-desktop || error "snap failed to install telegram-dekstop!"
```

the problem is that if the user uninstall the snap-store, telegram will stop working.
what do you have any ideas @Botspot?

**Comment by Botspot** [comment] 2021-04-25 02:43
Are you sure there's no way to electronify it?

How about reverse-engineering the snap?

**Comment by Itai-Nelken** [comment] 2021-04-25 04:07
there isn't any way I can think of to reverse engineer a snap or electronify a app that its website is worse than the app (missing features) andthe desktop app written in c++ and not javascript (thats actually good, it means its less resource intensive!).

there is already a request for arm: https://github.com/telegramdesktop/tdesktop/issues/1924
there is also this if we don't end up in "dependency hell": https://packages.debian.org/sid/armhf/telegram-desktop/download

**Comment by Botspot** [comment] 2021-04-25 19:20
> there isn't any way I can think of to reverse engineer a snap

What I mean is: would it be possible to _extract_ the snap so that can run dependently of Snap? (Hint: yes it is. I did it with Boxy SVG around a year ago, but have forgotten how to do it now.)

**Comment by Itai-Nelken** [comment] 2021-04-25 19:40
I found a different way in the rpi support issue in the tdesktop repo: using the debian sid packages.
I only have to update the versions as the comment with the instructions is from 2016 and then test it.
Will do it tomorrow.

**Comment by Itai-Nelken** [comment] 2021-04-26 13:22
I'm currently testing this.
from https://github.com/telegramdesktop/tdesktop/issues/1924#issuecomment-520380465
```bash
# Install Dependencies
sudo apt install -y \
    'libasyncns0' \
    'libavcodec-dev' \
    'libavcodec-extra' \
    'libavcodec-extra58' \
    'libavcodec-extra58-dbgsym' \
    'libavformat-dev' \
    'libavformat58' \
    'libavformat58-dbgsym' \
    'libavutil-dev' \
    'libavutil56' \
    'libavutil56-dbgsym' \
    'libdouble-conversion1' \
    'libflac8' \
    'libgle3' \
    'libgle3-dev' \
    'libglee0d1' \
    'libglee0d1-dbg' \
    'libgles1' \
    'libgles2' \
    'libgles2-mesa' \
    'libgles2-mesa-dev' \
    'libglew-dev' \
    'libglew2.1' \
    'libglewmx1.13' \
    'libglu1-mesa' \
    'libjpeg8' \
    'libminizip1' \
    'libmng1' \
    'libopenal-data' \
    'libopenal1' \
    'libpcre16-3' \
    'libpulse0' \
    'libqt5core5a' \
    'libqt5dbus5' \
    'libqt5gui5' \
    'libqt5network5' \
    'libqt5svg5' \
    'libqt5widgets5' \
    'libsndfile1' \
    'libsndio-dev' \
    'libsndio7.0' \
    'libswscale-dev' \
    'libswscale5' \
    'libswscale5-dbgsym' \
    'libwebpdemux2' \
    'libxcb-icccm4' \
    'libxcb-keysyms1' \
    'libxcb-randr0' \
    'libxcb-render-util0' \
    'libxcb-xinerama0' \
    'libxcb-xkb1' \
    'libxkbcommon-x11-0' \
    'libxkbcommon0' \
    'libxxhash-dev' \
    'libxxhash0' \
    'mesa-utils' \
    'qt5-gtk-platformtheme' \
    'qt5-image-formats-plugins' \
    'qttranslations5-l10n'

# Download Telegram Components
wget \
    'http://ftp.us.debian.org/debian/pool/main/libt/libtgvoip/libtgvoip1.0_1.0~git20170704.445433f-4~bpo9+1_armhf.deb' \
    'http://ftp.us.debian.org/debian/pool/main/libt/libtgvoip/libtgvoip-dev_2.4.2-1_armhf.deb' \
    'http://ftp.it.debian.org/debian/pool/main/t/telegram-desktop/telegram-desktop_2.6.1+ds-1_armhf.deb'

# Install Telegram Components
sudo dpkg -i \
    'libtgvoip1.0_1.0~git20170704.445433f-4~bpo9+1_armhf.deb' \
    'libtgvoip-dev_2.4.2-1_armhf.deb' \
    'telegram-desktop_1.5.11-1_armhf.deb'
```

**Comment by Itai-Nelken** [comment] 2021-04-26 13:23
the snap edge version is the latest, so I'm currently downloading it and will extract it.

**Comment by Itai-Nelken** [comment] 2021-04-26 13:33
this https://github.com/Botspot/pi-apps/issues/156#issuecomment-826831476 didn't work :(
and I don't have the time to search for the updated versions of the dependencies...

**Comment by Itai-Nelken** [comment] 2021-04-26 14:08
```
The following packages have unmet dependencies:
 telegram-desktop : Depends: libavcodec58 (>= 7:4.2)
                    Depends: libavformat58 (>= 7:4.2) but 7:4.1.6-1~deb10u1+rpt1 is to be installed
                    Depends: libc6 (>= 2.29) but 2.28-10+rpi1 is to be installed
                    Depends: libgcc-s1 (>= 3.5) but it is not installable
                    Depends: libgdk-pixbuf-2.0-0 (>= 2.22.0) but it is not installable
                    Depends: libqt5core5a (>= 5.15.1) but 5.11.3+dfsg1-1+rpi1+deb10u4 is to be installed
                    Depends: libqt5dbus5 (>= 5.14.1) but 5.11.3+dfsg1-1+rpi1+deb10u4 is to be installed
                    Depends: libqt5gui5 (>= 5.15.1) but 5.11.3+dfsg1-1+rpi1+deb10u4 is to be installed or
                             libqt5gui5-gles (>= 5.15.1) but it is not installable
                    Depends: libqt5network5 (>= 5.15.1) but 5.11.3+dfsg1-1+rpi1+deb10u4 is to be installed
                    Depends: libqt5widgets5 (>= 5.15.1) but 5.11.3+dfsg1-1+rpi1+deb10u4 is to be installed
                    Depends: librlottie0-1 (>= 0~git20200305.a717479+dfsg) but it is not going to be installed
                    Depends: qtbase-abi-5-15-2 but it is not installable
                    Depends: qtwayland-client-abi-5-15-2 but it is not installable
                    Recommends: fonts-open-sans but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

**Comment by mobilegmYT** [comment] 2021-04-26 14:29
> ```
> The following packages have unmet dependencies:
>  telegram-desktop : Depends: libavcodec58 (>= 7:4.2)
>                     Depends: libavformat58 (>= 7:4.2) but 7:4.1.6-1~deb10u1+rpt1 is to be installed
>                     Depends: libc6 (>= 2.29) but 2.28-10+rpi1 is to be installed
>                     Depends: libgcc-s1 (>= 3.5) but it is not installable
>                     Depends: libgdk-pixbuf-2.0-0 (>= 2.22.0) but it is not installable
>                     Depends: libqt5core5a (>= 5.15.1) but 5.11.3+dfsg1-1+rpi1+deb10u4 is to be installed
>                     Depends: libqt5dbus5 (>= 5.14.1) but 5.11.3+dfsg1-1+rpi1+deb10u4 is to be installed
>                     Depends: libqt5gui5 (>= 5.15.1) but 5.11.3+dfsg1-1+rpi1+deb10u4 is to be installed or
>                              libqt5gui5-gles (>= 5.15.1) but it is not installable
>                     Depends: libqt5network5 (>= 5.15.1) but 5.11.3+dfsg1-1+rpi1+deb10u4 is to be installed
>                     Depends: libqt5widgets5 (>= 5.15.1) but 5.11.3+dfsg1-1+rpi1+deb10u4 is to be installed
>                     Depends: librlottie0-1 (>= 0~git20200305.a717479+dfsg) but it is not going to be installed
>                     Depends: qtbase-abi-5-15-2 but it is not installable
>                     Depends: qtwayland-client-abi-5-15-2 but it is not installable
>                     Recommends: fonts-open-sans but it is not going to be installed
> E: Unable to correct problems, you have held broken packages.
> ```

Welcome to dependency hell Itai 😆. packages.debian.com is your friend for this one.

**Comment by Itai-Nelken** [comment] 2021-04-26 14:59
>Welcome to dependency hell Itai 😆. packages.debian.com is your friend for this one.

didn't find the packages there...
and I don't want to get into dependency hell gagain (already happened to me a few times...)

**Comment by Itai-Nelken** [comment] 2021-04-26 15:03
@Botspot to download and extract a snap:
**Download it:**
```bash
snap download snap-name
```
**Extract it:**
```bash
sudo mkdir /dev/snap/
sudo mount -t squashfs -o ro /path/to/app.snap /dev/snap
```
**Unmount it:**
```bash
sudo umount /dev/snap
sudo rmdir /dev/snap/
```

**Comment by cycool29** [comment] 2021-09-28 00:46
This should be closed since Telegram is in pi-apps now. @Botspot

**Closed** 2021-09-28 17:13 UTC
Labels: App Request
