### ISSUE TITLE
Add Atom text editor

### ISSUE THREAD

**Issue by kerem700916** [Botspot/pi-apps#932] opened 2021-08-25 12:23 UTC

**Comment by Itai-Nelken** [comment] 2021-08-25 12:35
Duplicate of #617

**Comment by Itai-Nelken** [comment] 2021-08-25 12:38
@kerem700916 it isn't possible to install atom on the rpi, at least currently.

**Comment by Itai-Nelken** [comment] 2021-08-25 12:38
Tou could try to compile it if you want, maybe it works now.

**Comment by kerem700916** [comment] 2021-08-25 12:39
Oh!
My bad

**Comment by kerem700916** [comment] 2021-08-25 12:41
By the way I'm trying to changing the some apps icon with sudo nano <app pat>. But I can't find the apps path that I downloaded via pi-apps. Can you tell me the apps default directory?

**Comment by Botspot** [comment] 2021-08-25 12:45
> By the way I'm trying to changing the some apps icon with sudo nano **app path**. But I can't find the apps path that I downloaded via pi-apps. Can you tell me the apps default directory?

~/pi-apps/apps
Learn all about each file in the pi-apps folder [here](https://github.com/Botspot/pi-apps/wiki/Directory-tree).

**Closed by Botspot** 2021-08-25 12:45 UTC
Labels: duplicate, App Request

**Comment by kerem700916** [comment] 2021-08-25 12:59
Thanks @Botspot @Itai-Nelken

**Comment by ryanfortner** [comment] 2021-11-30 18:49
I just came across this repository: https://github.com/bcurnow/atom-arm64-pi

I'm not sure if it works but I'll try in a bit.

**Comment by Crilum** [comment] 2021-12-01 04:08
It appears to me that this doeesn't work:

<i>From the README:</i>
>Wouldn't it be nice if this worked?
